mathjax/MathJax-src

v3/TexParser/ts/map_handler.ts

I personally think `as` is more readable, especially since `<>` already has another meaning in the very same expression. See the bottom of https://www.typescriptlang.org/docs/handbook/basic-types.html.

Use 'as' for typecasting

---

v3/TexParser/package.json

Typescript minor versions may not be compatible with other minor versions, so it's better to pin the minor version the code is compatible with.

Pin Typescript to 2.1.x

---

v3/mathjax/legacy/jax/element/JSON.js

This should resolve the JSON problem that Volker reported with msub in place of msup.
Test case:
node load.js samples/json.js "x'"
should not produce msup rather than msub.

Fix checking for msub/msup and munder/mover

---

mathjax3-ts/core/MathDocument.ts
mathjax3-ts/core/MmlTree/MmlFactory.ts
mathjax3-ts/core/MmlTree/MmlNode.ts
mathjax3-ts/core/MmlTree/MmlNodes/mfenced.ts
mathjax3-ts/core/Tree/Factory.ts
mathjax3-ts/core/Tree/Node.ts
mathjax3-ts/core/Tree/NodeFactory.ts
mathjax3-ts/core/Tree/Visitor.ts
mathjax3-ts/input/mathml/MathMLCompile.ts

This implements factories for generic types, as the `Factory` object in `mathjax3-ts/core/Tree/Factory.ts`.
Most of the functionality of `NodeFactory` has been moved to `Factory` and made generic.  `Factory<N, C>` takes a node type `N` and a node class `C` which give the interfaces for the node instance and the node constructors.  We need both for two reasons:  first, you can't use `typeof N` to get `C`, since `N` is a type not an object, and if `N` has static members, we may want to access them from the results of `getNodeClass(kind)` (this is done in MmlNodes, for example).
Most of `MmlFactory` can now be removed, since it is in the generic `Factory<MmlNode, MmlNodeClass>` object and was only in `MmlFactory` to set the types from `Node` to `MmlNode` and `NodeClass` to `MmlNodeClass`, …

Make Factory object use generic types

---

mathjax2/legacy/jax/element/MmlNode.js
mathjax3-ts/core/MmlTree/Attributes.ts
mathjax3-ts/core/MmlTree/MmlNodes/mi.ts
mathjax3-ts/core/MmlTree/MmlNodes/mstyle.ts

This fixes up a few minor issues:
* In legacy TeX input jax, the class wasn't being passed along
* In MmlNode attributes, the global attributes need to be part of the lookup chain (and some comments were wrong)
* For mi elements, the mathvariant should be set only if it isn't being inherited
* For mstyle elements, they should set the displaystyle if it is explicitly included.

Minor fixes

---

mathjax3-ts/util/HTMLNodes.ts

This is a utility for creating HTML nodes in a particular document.  The document is cached, since HTML elements are created via `document.createElement()` and `document.createTextNode()`, so we need to know the document in order to create HTML elements.  The output jax will instantiate an HTMLNodes object for the document it is working on in order to generate the needed HTML output.

Add utility for constructing HTML nodes

---

mathjax3-ts/core/Tree/Factory.ts
mathjax3-ts/core/Tree/Wrapper.ts
mathjax3-ts/core/Tree/WrapperFactory.ts
mathjax3-ts/output/chtml.ts
mathjax3-ts/output/chtml/BBox.ts
mathjax3-ts/output/chtml/TeX.ts
mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/WrapperFactory.ts
mathjax3-ts/output/chtml/Wrappers.ts
mathjax3-ts/output/chtml/Wrappers/TextNode.ts
mathjax3-ts/output/chtml/Wrappers/mfrac.ts
mathjax3-ts/output/chtml/Wrappers/mspace.ts
mathjax3-ts/util/HTMLNodes.ts
mathjax3-ts/util/lengths.ts
mathjax3-ts/util/string.ts
samples/tex-document.js
tslint.json

This is the main framework for the CHTML output jax.  It implements a "Wrapper" object that is the solution to not being able to add methods to the MmlNode objects.  It is essential a shadow hierarchy that mirrors the MmlNode hierarchy, so that you can inherit methods, but not modify the MmlNode classes themselves.  I added generic `Wrapper` and `WrapperFunction` classes in `core/Tree`, and the CHTML-specific ones in `output/chtml`. 
The `CHTMLWrapper` is the base class for CHTML output, and includes all the generic functionality needed to produce CHTML output.  The node-specific methods are in the `output/chtml/Wrappers` directory.  There are only three at the moment, as examples (and the mfrac is just a preliminary version, as more needs to be done there).
This doesn't include the …

Beginnings of CHTML output jax

---

mathjax3-ts/output/chtml.ts
mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/Wrappers.ts
mathjax3-ts/output/chtml/Wrappers/TextNode.ts
mathjax3-ts/output/chtml/Wrappers/mfrac.ts
mathjax3-ts/output/chtml/Wrappers/mo.ts
mathjax3-ts/output/chtml/Wrappers/mrow.ts
mathjax3-ts/output/chtml/Wrappers/mspace.ts

This PR adds preliminary support for stretchy characters.  It adds mrow, inferred mrow, and mo classes.  An `mrow` look for vertically stretchy children and determines the size to stretch them to before laying out the HTML for the row.  The core `mo` of a stretchy element determines the size of the stretchy character and produces the properly sized output (currently only for the fixed-size variants; the multi-character stretchy versions are still to come).
Because the sizes can actually be determined up front (not at typesetting time), the `WHD` parameters for `toCHTML()` and `computeBBox()` that I expected to use for stretchy characters are no longer needed, and have been removed.
This is just the framework; the font data needed for full functionality will come in a later pull request. …

Add preliminary support for stretchy-characters

---

mathjax2/legacy/jax/input/TeX/jax.js

This moves the fix from mathjax/MathJax#1829 to the mathjax2 directory.

Update TeX input jax to latest v2 develop version

---

mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/Wrappers.ts
mathjax3-ts/output/chtml/Wrappers/TeXAtom.ts
mathjax3-ts/output/chtml/Wrappers/TextNode.ts
mathjax3-ts/output/chtml/Wrappers/mo.ts
mathjax3-ts/output/chtml/Wrappers/mpadded.ts
mathjax3-ts/output/chtml/Wrappers/mroot.ts
mathjax3-ts/output/chtml/Wrappers/ms.ts
mathjax3-ts/output/chtml/Wrappers/mspace.ts
mathjax3-ts/output/chtml/Wrappers/msqrt.ts
mathjax3-ts/output/chtml/Wrappers/semantics.ts
mathjax3-ts/output/chtml/fonts/tex.ts
samples/mml-bbox.js

This PR implements several more MathML node types:  ms, mpadded, msqrt, mroot, semantics, annotation, annotation-xml, and (the MathJax-specific) TeXAtom nodes.  Note that some of the support for annotation-xml as the first element of semantics is not yet in place, and will be added later.

Support more mml nodes

---

mathjax3-ts/core/MmlTree/MmlNode.ts
mathjax3-ts/output/chtml.ts
mathjax3-ts/output/chtml/CssStyles.ts
mathjax3-ts/output/chtml/FontData.ts
mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/Wrappers/TextNode.ts
mathjax3-ts/output/chtml/Wrappers/mfrac.ts
mathjax3-ts/output/chtml/Wrappers/mo.ts
mathjax3-ts/output/chtml/Wrappers/mpadded.ts
mathjax3-ts/output/chtml/Wrappers/msqrt.ts
mathjax3-ts/output/chtml/Wrappers/semantics.ts
mathjax3-ts/output/chtml/fonts/tex.ts

This pull request adds support for generating the CSS styles needed for CHTML output.
The various Wrapper classes each can add their own CSS, and the main Wrapper class includes some generic CSS used by CHTML.  The TeX font object now creates the CSS for the characters and delimiters automatically (in `tex.ts`), and some font data was moved from `Wrapper.ts` and `FontData.ts` to `tex.ts`.
I took Volker's suggestion of moving the skew and italic-correction data from the `CharData` array to the options object, and have made a `CharOptions` for that, now that the data needed for the CSS creation has been worked out.  The `DelimiterData` has been updated to include some additional information that was needed for the CSS as well.  (There is still a bit more to come, as there need to be some …

Create css styles for CommonHTML

---

mathjax3-ts/output/chtml/FontData.ts
mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/Wrappers/mfrac.ts
mathjax3-ts/output/chtml/Wrappers/mo.ts
mathjax3-ts/output/chtml/Wrappers/mrow.ts
mathjax3-ts/output/chtml/Wrappers/msqrt.ts
mathjax3-ts/output/chtml/fonts/tex.ts

This PR converts the stretchy directions to an `enum` (as per Volker's earlier request), and adds the missing `bold-italic` css to some bold variants (needed for lower-case greek to fallback to bold-italic greek in those cases).  Sorry for combining the two unrelated things, I missed it when I was committing, and it was too late afterwords.

Convert stretchy directions to an enum

---

mathjax3-ts/output/chtml/BBox.ts
mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/Wrappers/mfrac.ts
mathjax3-ts/output/chtml/Wrappers/mo.ts
mathjax3-ts/output/chtml/Wrappers/mroot.ts
mathjax3-ts/output/chtml/Wrappers/mspace.ts
mathjax3-ts/output/chtml/Wrappers/msqrt.ts

Add `drawBBox()` method (for debugging), and fix a number of bounding box problems that it was able to demonstrate.
It turns out we don't want to replace the original bbox created for a wrapper (as it can cause loss of other data, like the `L` property), so we don't use `BBOX.empty()` in `computeBBox()` but instead add an `empty()` method to the bbox to set the `w`, `h`, and `d` values appropriately in the already existing BBoxes.
We use a new `getSpace()` method to compute `bbox.L` (the left spacing) when the object is created (since some bbox computations need it).
Since the `bbox.L` value is already computed, we use that to set the `space` attribute rather than the old `SPACE` array (which is no longer needed).
The rest of the changes are tweaks to get the bounding boxes or placement …

Add drawBBox() method, and fix a number of BBox problems.

---

mathjax3-ts/output/chtml/FontData.ts
mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/Wrappers.ts
mathjax3-ts/output/chtml/Wrappers/munderover.ts
mathjax3-ts/output/chtml/Wrappers/scriptbase.ts
mathjax3-ts/output/chtml/fonts/tex.ts

This PR adds preliminary support for `munderover`, `munder` and `mover`.  The wrappers for these subclass the ones for `msubsup`, `msub`, and `msup` because when they have the `movablelimits` attribute, and the `displaystyle` is false, we want to set the under-over as sub-sup.  This subclassing lets us call the super class in that car etc get sub-sup formatting.
This PR modifies `scriptbase` class to add the needed common functions for under-over (and moves one function in order to group things better).
We also fix an issue in the CSS generated for the TeX font (where negative values for height or depth would lead to invalid `padding` values).
This implementation doesn't yet take the `accent` and `accentbelow` attributes into account (which change the spacing), and doesn't do the …

Add support for munder/mover/munderover

---

mathjax3-ts/output/chtml/FontData.ts
mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/Wrappers.ts
mathjax3-ts/output/chtml/Wrappers/msubsup.ts
mathjax3-ts/output/chtml/Wrappers/munderover.ts
mathjax3-ts/output/chtml/Wrappers/scriptbase.ts
mathjax3-ts/output/chtml/fonts/tex.ts

This PR adds support for `msubsup`, `msub`, and `msup` elements.  It currently doesn't handle italic correction (so positions relative to something like an integral sign will be bad).
There is a base class `CHTMLscriptbase` that is the basis for all three elements.  It will also be the basis for the `munderover`, `munder` and `mover` elements, since the `movablelimits` attribute can cause the under-over elements to render as sub-sup elements in non-display modes.  So the latter under-over elements will be subclasses of the sub-sup classes, and the common under-over methods will be added to the `CHTMLscriptbase` class when under-over support is added.

Add support for mub/msup/msubsup

---

mathjax3-ts/output/chtml/FontData.ts
mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/Wrappers.ts
mathjax3-ts/output/chtml/Wrappers/mfrac.ts
mathjax3-ts/output/chtml/Wrappers/msubsup.ts
mathjax3-ts/output/chtml/Wrappers/munderover.ts
mathjax3-ts/output/chtml/Wrappers/scriptbase.ts
mathjax3-ts/output/chtml/fonts/tex.ts

Make fractions conform to TeX spacing, for all styles (display, text, script, and scriptscript).  Also, properly handle `\large` and other sizing macros.  Still need to handle linethickness (particularly linethickness=0), and beveled fractions, but good enough for now.
This also includes a change to the CHTMLWrapper's `handleScale()` which allows you to set the scale on any node (not just the top-level one).  This was originally going to be needed for the struts that enforce some spacing rules, but it ended up not being needed.  But I left the change in since it might be useful to break out the setting of the scale as a separate function.
Some of the constants used in the bounding box computation should be taken from the font parameters, but for now those values are hard-coded into the …

Make mfrac use TeX layout.

---

mathjax3-ts/output/chtml/Wrappers/mtable.ts

[I deleted the branch the original PR was being merged to, and the old PR it was closed automatically.  So I'm making a new one.  It already addresses Volker's comments from the old one.  Again, sorry for the error.]
This PR adds support for `mtable`/`mtr`/`mtd`.  Not all `mtable` attributes are supported (so far, only `columnspacing`, `rowspacing`, `columnalign`, `rowalign`, `columnlines`, `rowlines`, `frame`, and `framespacing`).  This is enough for most of the TeX requirements.  Labeled rows are handled, but the label is dropped for now.  Still to be done are things like setting column widths, forcing equal columns and rows, label support, and setting the table width (in particular, percentage width tables).  Note that partial frames (possible within LaTeX's array environment) rely on …

Table support

---

mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/Wrappers.ts
mathjax3-ts/output/chtml/Wrappers/math.ts
mathjax3-ts/output/chtml/Wrappers/mrow.ts
mathjax3-ts/output/chtml/Wrappers/mtable.ts

This PR adds a wrapper for the math tag that handles display math as a block-style element.  It also adds support for percentage-width tables (which have to bubble the 100% percent width up through the parent elements to the containing math element).  The TeX input uses percentage-width tables for the multline environment.  You can also specify a fixed width for tables.

Math tag support

---

mathjax3-ts/output/chtml/Wrappers/msqrt.ts

Make sqrt line overlap with tall surd top corner glyph for better attachment.  Only affects very tall roots that requires multi-character surd.  The top corner has always been difficult to align properly with the overline, and this can improve the look (originally suggested in MathJax issue 1838).

Better tall square roots

---

mathjax3-ts/core/MmlTree/MmlNodes/mo.ts
mathjax3-ts/core/MmlTree/OperatorDictionary.ts

This PR adds the full operator dictionary, as a separate module, loaded by the `MmlMo` class.  So the original operator table from the `MmlMo` has been removed, and the module loaded instead.  That's basically all it is.

Add full operator dictionary, and move it to a separate file.

---

mathjax3-ts/output/chtml/BBox.ts
mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/Wrappers.ts
mathjax3-ts/output/chtml/Wrappers/TeXAtom.ts
mathjax3-ts/output/chtml/Wrappers/TextNode.ts
mathjax3-ts/output/chtml/Wrappers/mi.ts
mathjax3-ts/output/chtml/Wrappers/mo.ts
mathjax3-ts/output/chtml/Wrappers/msqrt.ts
mathjax3-ts/output/chtml/Wrappers/msubsup.ts
mathjax3-ts/output/chtml/Wrappers/munderover.ts
mathjax3-ts/output/chtml/Wrappers/scriptbase.ts
mathjax3-ts/output/chtml/fonts/tex.ts

This PR adds support for italic correction, based on TeX's rules.  We use the difference between a characters right-bearing and its width as a surrogate for italic-correction (since we don't have the actual TeX metrics for this).
The italic correction is added to the last character in `mi` and `mo` nodes (and should probably be added in `mn` as well, but numbers are usually in roman and so don't have italic correction).  So an `mi` wrapper is added and the `mo` wrapper modified to do that.  The italic correction is added via the CSS.
Italic correction is *not* to be used in some superscript and under-over situations.  So there is CSS set up to remove the italic correction when needed in those cases.
Also, the italic correction is used to properly place super- and subscripts and under-over …

Italic correction

---

mathjax3-ts/output/chtml/Wrappers/msqrt.ts

This fixes a problem with the bounding box for msqrt.  It didn't take the base bounding box height into account correctly.  (This happened when renaming bounding boxes for Volker's request — I missed one in the renaming.)

Fix bbox for msqrt.

---

mathjax3-ts/output/chtml.ts
mathjax3-ts/output/chtml/fonts/tex.ts

This allows you to specify a font URL for the CHTML fonts when you create the CHTML output object.  E.g.
```
const chtml = new CHTML({fontURL: 'http://mysite.com/mathjax-3/fonts'});
```
The URL should have subdirectories `woff` and `otf` containing the MathJax v3 fonts.

Allow configuration of the URL to use for fonts.

---

mathjax3-ts/handlers/html/HTMLDomStrings.ts
mathjax3-ts/output/chtml.ts

Only push sibling node onto the stack when it exists, and make sure `node.document` is set for stylesheets, even if no typesetting occurred (i.e., not math was found).  Resolves issue #78.

Fixes HTMLDOMStrings find() for problems with nesting.  Resolves #78.

---

mathjax3-ts/output/chtml/Wrappers/mo.ts
mathjax3-ts/output/chtml/Wrappers/mtable.ts
mathjax3-ts/output/chtml/Wrappers/mtr.ts
mathjax3-ts/output/chtml/Wrappers/scriptbase.ts
mathjax3-ts/output/chtml/fonts/tex.ts
samples/mml-bbox.js

This PR adds support for horizontal and vertical stretchy characters in table cells.  Only rows or columns with actual stretchy characters will have their bounding boxes computed.

Add support for stretchy cells in tables

---

mathjax3-ts/output/chtml/Wrappers/mtable.ts

Resolves issue #74 by adding initial values to the `reduce()` calls.

Add initial value to reduce() calls to avoid problems with empty arrays. #74

---

mathjax3-ts/output/chtml/Wrappers/mo.ts
mathjax3-ts/output/chtml/Wrappers/mtable.ts
mathjax3-ts/output/chtml/fonts/tex.ts

This adjusts the CSS to avoid the gaps pointed out by Neil in #64, and improves the situation for horizontal placement of extenders in Firefox (though not for Chrome).

Improve CSS for stretchy braces in IE and Edge

---

load.html
mathjax3-ts/util/AsyncLoad-disabled.ts
mathjax3-ts/util/AsyncLoad.ts
mathjax3-ts/util/Entities.ts

This updates the `asyncLoad()` function to work no matter where the `mathjax3` directory is located (so in `v3`, or in `node_modules/mathjax3`, for example).  The path fort he file whose name is passed to `asyncLoad()` is now relative to the `mathjax3` directory (rather than the application directory, as it used to be).
This also provides a "disabled" version of `asyncLoa()` that does not try to load the file but simply reports a failure immediately.  This is for use with webpack, which produced warnings for the current version.  The disabled one is selected in the webpack configuration using
```
new webpack.NormalModuleReplacementPlugin(
/\/AsyncLoad\.js/,
function (resource) {
resource.request = resource.request.replace(/AsyncLoad/,"AsyncLoad-disabled");
}
)
```
in the `plugins` array …

Update asynchronous loading

---

mathjax3-ts/core/MmlTree/MML.ts
mathjax3-ts/core/MmlTree/MmlNodes/mathchoice.ts

This is an implementation for the `mathchoice` object needed by TeX's `\mathchoice` macro.  This object is only temporary, in that it removes itself from the tree during the finalization of the MmlNode tree leaving only the proper subtree for the TeX class in effect for the node.  This is accomplished during the `setInheritedAttributes()` call on the parent, when the `displaystyle` and `scriptlevel` are being set, as these are what determine the TeX style in effect (displaystyle, text style, scriptstyle, or scriptscriptstyle).

Add a mathchoice MmlNode type

---

lib/Mml-lab.js
lib/TeX-lab.js
mathjax3-ts/core/MathItem.ts
mathjax3-ts/core/MmlTree/MmlNodes/mtable.ts
mathjax3-ts/core/MmlTree/MmlNodes/mtr.ts
mathjax3-ts/output/chtml/Wrappers/mtable.ts
mathjax3-ts/output/chtml/Wrappers/mtd.ts
mathjax3-ts/output/chtml/Wrappers/mtr.ts
mathjax3-ts/util/numeric.ts
mathjax3-ts/util/string.ts

This PR implements a number of previously unimplemented attributes for `mtable` elements, including `equalrows`, `equalcolumns`, `columnwidth` and `align`, with improvements to `rowalign` and `columnalign`.  This required some reorganization (which I think is an improvement anyway), so there are some pieces being moved around and indentation changes that might make it look like more changes than are actually significant ones.
The `mtable.js` file has the most changes, but it is not being displayed by default, so you will have to open that by hand.
There are some changes to the `core/MmlTree/MmlNodes` for `mtable` and `mtr` to get some of the inheritance working for `rowalign` and `columnalign`.  I also changed the labs to set the container width to something more reasonable (20em, since …

Implement more mtable attributes

---

mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/Wrappers/mo.ts
mathjax3-ts/output/chtml/Wrappers/scriptbase.ts

This fixes the problem with `\xrightarrow` not stretching reported by Volker.  This was due to the `<mo>` being asked to stretchy both horizontally (by the `<munderover>`) and vertically (by the enclosing `<mrow>`, since it is an embellished operator in that row).
The resolution is to only allow stretching in one direction (since we don't support bi-directional stretching), that being the first direction for which stretching was requested and possible.
This also properly scales the maximum width computations in `munderover` so the size of the arrow is correct.

Fix problem with \xrightarrow not stretching.

---

mathjax3-ts/adaptors/chooseAdaptor.ts
mathjax3-ts/adaptors/liteAdaptor.ts
package-lock.json
package.json
samples/asciimath-document.js
samples/mml-bbox.js
samples/mml2html.js
samples/tex-document.js
samples/tex-multi-document.js
samples/tex2html.js
samples/tex2mml.js

This PR removes `jsdom` (and `web pack`) as dependencies.  This means we have no (non-developer) dependancies, and this will prevent the (incorrect) security vulnerability message from GitHub (due to a version of a package in the dependencies of `jsdom`).
The `chooseAdaptor` now picks between browser and lite adaptors (rather than browser and jsdom adaptors).  The samples have been fixed to use the adaptor to access the DOM properties (since lite adaptor doesn't produce HTMLElements).
There is also a fix for an error in the lite adaptor's `split()` function that was spotted during the updating of the samples.
Finally, I added more keywords to the `package.json` file.

Remove jsdom (and webpack) as dependencies

---

mathjax3-ts/core/MmlTree/MML.ts
mathjax3-ts/core/MmlTree/MmlNodes/mglyph.ts
mathjax3-ts/output/chtml/Wrappers.ts
mathjax3-ts/output/chtml/Wrappers/mglyph.ts

This PR adds preliminary support for mglyph elements.
Currently, you need to give explicit `width` and `height` attributes (they default to `1em` otherwise), because loading images may be asynchronous, and for node-based use, you might want to read from files rather than from the network to find the images, so that would require additional configuration and name mapping.  I'm going to leave those for future extensions.

Add support for mglyph

---

mathjax3-ts/core/MmlTree/MmlNodes/mo.ts

* Removes `form` attribute test from `hasSpacingAttributes`
* Removes  setting of `texclass=none` from `setTeXclass` method.
* Comments out incorrect `range` setting in `setInheritedAttributes`

Fixes as discussed f2f.

---

mathjax3-ts/output/chtml/Notation.ts
mathjax3-ts/output/chtml/Wrappers.ts
mathjax3-ts/output/chtml/Wrappers/menclose.ts

This PR adds support for the `menclose` element, including all the notations defined in the MathML spec.  (Version 2.x doesn't do all the arrows, but this version includes them all.)  It would be possible to add additional notations using `CHTMLmenclose.Notations.add()` if you wanted to create non-standard ones.  Also, the padding, line thickness, and arrowhead values can be modified using `data-padding`, `data-thickness` and `data-arrowhead` attributes on the `menclose` element (version 2.x used non-standard `padding` and `thickness` attributes, but these should be `data-*` attributes instead; I don't recall if the TeX input jax ever set these non-standard attributes).

Add support for menclose

---

mathjax3-ts/output/chtml/Wrappers/mtable.ts
mathjax3-ts/output/chtml/Wrappers/mtd.ts

Force label heights to size properly, and handle row spacing and row lines properly, as well as the placement of the baseline in the label itself.  The largest change is to move the code that sets the cell baseline into a separate routine so that it can be called on the label itself separately.
This should fix the problem the underlies the issue @zorkow raised F2F concerning a tagged split environment inside an align environment.

Fix placement of table labels

---

load.mjs
mathjax2/legacy/extensions/TeX/AMSmath.js
mathjax2/legacy/extensions/TeX/AMSsymbols.js
mathjax2/legacy/jax/input/TeX/jax.js
package-lock.json
package.json

This PR adds a `load.mjs` file that will trigger node's esm module (in version 10+) so that ES6 files can be loaded directly into node without the need of `system.js`.  That is, you can use `import` and `export` directly without down compiling.  I tested it with the `ES6` target for Typescript, and it works nicely, though I haven't changed that in this PR.  The only real changes needed was to make sure the imports use relative file names rather than root-level filenames.

Update to work with node 10's esm module rather than system.js

---

mathjax3-ts/core/MmlTree/MmlNode.ts
mathjax3-ts/core/MmlTree/MmlNodes/mtable.ts
mathjax3-ts/output/chtml/BBox.ts
mathjax3-ts/output/chtml/Wrapper.ts
mathjax3-ts/output/chtml/Wrappers/math.ts
mathjax3-ts/output/chtml/Wrappers/mrow.ts
mathjax3-ts/output/chtml/Wrappers/mtable.ts
mathjax3-ts/output/chtml/Wrappers/mtr.ts

This PR adds support for `indentalign` and `indentshift`, which control the alignment and indenting of displayed equations.  This is handled in the `math` wrapper, and also in the `mtable` wrapper since tables with labels are in full-width elements, and the alignment of the actual table must be inside the full-width container.  Stylesheet CSS handles the alignment, but the shifting requires explicit styles.  Because tables rely on the `indentalign` and `indentshift` values, they need to be added to the mtable inheritance.
This PR also includes fixes for the bubbling up of full-width element, like tables with labels.  So if a table is inside another element (e.g., `mstyle`, or `semantics`), that won't disrupt the label positioning.  This was being done by hand in `mrow`elements, but that …

Add support for indentalign and indentshift

---

mathjax3-ts/adaptors/lite/Parser.ts

Don't escape contents of PCDATA elements, like `<style>` and `<script>`.
Resolves issue #127.

Don't escape contents of PCDATA elements. #127

---

mathjax3-ts/output/chtml/Notation.ts
mathjax3-ts/output/chtml/Wrappers/menclose.ts
mathjax3-ts/output/common/Notation.ts
mathjax3-ts/output/common/Wrappers/menclose.ts

This PR improves the CHTML implementation of `<menclose>` so that it no longer uses SVG elements, but instead uses only CSS.  SVG used to be used for `circle`, `longdiv`, and the various arrows (`rightarrow`, `northeastarrow`, etc.), but now only CSS is used for this.  The ellipse was easy to do using a rectangle with rounded corners with `border-radius: 50%`, and this could be used for `longdiv` as well.  The arrows took more work, but ended up better than I expected.  The CSS used for placing the arrows has been simplified, so that some of the data that used to be used is no longer needed (we place the arrow in the center and rotation around the center rather than place at lower left and rotation about lower left).
This also improves the bounding box computations for arrows so that the …

Use only CSS for menclose notations in CHTML

---

lib/TeX-lab.js
mathjax3-ts/input/tex/color/ColorConfiguration.ts
mathjax3-ts/input/tex/color/ColorConstants.ts
mathjax3-ts/input/tex/color/ColorMethods.ts
mathjax3-ts/input/tex/color/ColorUtil.ts

The [color.js packages imported from v2](https://github.com/mathjax/MathJax/blob/master/unpacked/extensions/TeX/color.js)
```latex
\definecolor{salty}{named}{#888}
2bc \ { \color{blue} 1yz } \ 2\pi^2  \ldots
\textcolor[gray]{0.75}{ams} \ldots
\textcolor{#f80}{\text{Orange}} \ldots
\colorbox{green}{ams} \ldots 
\fcolorbox{green}{silver}{ Text } \ldots
\color[rgb]{0.5,0.5,1}
H_2O \ldots
\color{salty}
NaCl \ldots
```

Color.js package

---

mathjax3-ts/output/svg/Wrappers/mo.ts

This uses nested `<svg>` elements to do the clipping (via `overflow` CSS) rather than `clip-path` attributes, since IE doesn't implement `inset()` paths (it only handles `url()` references), and Safari requires CSS with `-webkit` prefix, not attributes.
Resolves #153.

Handling clipping for the extenders of stretchy characters in IE and Safari.  #153

---

mathjax3-ts/output/chtml/Wrappers/mo.ts
mathjax3-ts/output/chtml/fonts/tex.ts
mathjax3-ts/output/common/Wrappers/mo.ts
mathjax3-ts/output/common/fonts/tex.ts
mathjax3-ts/output/common/fonts/tex/delimiters.ts

Fix problem with stretchy character minimum width when there are no single-character versions, and update the minimum sizes to be correct (those values were taken from the v2 font data, but are incorrect -- the new ones have been computed from the widths of the pieces used).  Also improve placement of glyphs in CHTML stretchy characters, and add the missing fonts to the stretchy font list.  Resolves issues #156 and #152.

Fix stretchy characters in SVG and CHTML.  #156 and #152.

---

mathjax3-ts/output/chtml/Wrappers/math.ts
mathjax3-ts/output/svg.ts
mathjax3-ts/output/svg/Wrapper.ts

Allow svg elements to overflow (so that `\llap`, `\rlap`, `\smash`, etc will not cause clipping at the border of the svg).  That is, `$\llap{x}$ will have the x overlaps the text to the left of the math.
This also makes things like `$x\hskip -2em y$` show up and have the correct width in both SVG and CHTML.
Resolves issue #157.

Allow svg elements to overflow.  #157

---

mathjax3-ts/output/chtml/Wrapper.ts

Add css for mstyle so bounding box is correct.  (This was supposed to have been in the beta.2 release, but I lost it along the way somewhere, probably when I was unraveling some changes near the end.)
Resolves issue #137.

Add css for mstyle so bounding box is correct.  #137.

---

mathjax3-ts/output/common/Wrapper.ts

The problem was that when `variantForm` was set, the wrong variant name was being used.
Resolves issue #178.

Fix output for \hbar and other variant forms.  #178.

---

mathjax3-ts/output/common/OutputJax.ts
mathjax3-ts/output/common/Wrapper.ts

Add `displayAlign` and `displayIndent` parameters for CHTML and SVG output, as in version 2.
Resolves issue #186.

Add displayAlign/displayIndent configuration as in v2.  #186

---

mathjax3-ts/adaptors/lite/Parser.ts

This is a trivial fix to makes sure that all quotes are escapes in serialized HTML produced from the lite parser.

Make sure ALL quotes are escaped

---

mathjax3-ts/core/MmlTree/MmlNode.ts

Use proper `displaystyle` for `inheritAttributeFrom()`, and don't set `mathsize` unless it is actually needed.  This is in response to a report from Volker.

Fix values set by inheritAttributesFrom()

---

mathjax3-ts/output/chtml.ts
mathjax3-ts/output/svg.ts
mathjax3-ts/output/svg/FontCache.ts
mathjax3-ts/output/svg/FontData.ts
mathjax3-ts/output/svg/Wrapper.ts
mathjax3-ts/output/svg/fonts/tex.ts

This PR provides a new option for the SVG output jax that lets you use a global or local font cache (global means global to all expressions on the page, local means a cache that is specific to a single expression), or no cache (all glyphs are given as SVG paths directly).
This mirrors the v2 font-caching options.

Add support for svg font caching (global, local, or none)

---

mathjax3-ts/core/MmlTree/SerializedMmlVisitor.ts

This fixes a problem with serialization of `<annotation>` elements that was causing additional line breaks before and after the annotation.  This patch keeps the whitespace as it was in the original.  It also fixes some jsdoc problems (`@return` => `@returns`).

Handle annotation elements better.

---

mathjax3-ts/util/Options.ts

Add ability to make blocks of options that are open-ended (expandable).  You need these for things like the `Macros` configuration for TeX input, for example.
Also, make the APPEND variable a string so that it can be included in the user configuration object without having to load MathJax modules to get access to this variable.

Add ability to make blocks of options that are open-ended

---

mathjax3-ts/a11y/Explorer.ts
mathjax3-ts/a11y/complexity.ts
mathjax3-ts/a11y/explorer.ts
mathjax3-ts/a11y/explorer/Explorer.ts
mathjax3-ts/a11y/explorer/Region.ts
mathjax3-ts/a11y/semantic-enrich.ts
mathjax3-ts/a11y/sre.ts

This PR adds an explorer extension that uses the proper mechanism for extending the handler, document, and math item classes.  It also updates the existing extensions to register themselves with the new render-action list, and hook into the `STATE` values properly.

Update a11y and add explorer

---

mathjax3-ts/ui/menu/MJContextMenu.ts
mathjax3-ts/ui/menu/Menu.ts
mathjax3-ts/ui/menu/MenuHandler.ts
mathjax3-ts/ui/menu/MmlVisitor.ts
mathjax3-ts/ui/menu/SelectableInfo.ts

This PR adds support for the contextual menu.  It uses an extension (`MenuHandler.ts`) similar to the ones in the `a11y` directory to hook itself into the rendering action list.  If the `startup` component has been loaded, it will allow the loading of the explorer and complexity extensions on the fly.
The configuration submenu for the explorer module is present, but the values are not respected, as the mechanism for changing the explorer configuration in `Explorer.ts` doesn't seem to be present yet.  There are also some issues with restarting the explorer when an `maction` is triggered, and a few other issues with the explorer.  @zorkow, if you want to work on the explorer, either use this branch, or better yet, the `v3-lab` branch as your starting point.

Context menu

---

mathjax3-ts/output/chtml/FontData.ts
mathjax3-ts/output/chtml/Wrappers/mo.ts

Fix horizontal stretchy characters in CHTML.  This apparently was broken in the adaptive-css branch (the `width:0` for the `mjx-c::before` was the main culprit, but I reorganized a few other bits of CSS as well.

Fix horizontal stretchy characters in CHTML

---

mathjax3-ts/util/Options.ts

This PR adds a `REMOVE` option similar to the `APPEND` one so that if an option's default value is an array, you can use `prop: {[REMOVE]: [items]}` to remove the given items from the default values.  You can include both `APPEND` and `REMOVE` if you want, in order to remove some entries and then add others.

Add a REMOVE option for arrays, corresponding to APPEND

---

mathjax3-ts/ui/menu/Menu.ts

This makes it possible to load components that include the menu code into node.  Though you won't be able to use the menus there, at least you will be able to load and use the components themselves.

Make sure window exists before using it

---

mathjax3-ts/components/loader.ts
mathjax3-ts/components/package.ts

This makes it possible to make modules that include other modules (e.g., combined modules that include both an input and an output module) and allow the loader to know that the sub-modules have been loaded.

Update loader to add a "provides" property

---

mathjax3-ts/input/tex.ts
mathjax3-ts/input/tex/AllPackages.ts
mathjax3-ts/input/tex/Configuration.ts
mathjax3-ts/input/tex/Tags.ts
mathjax3-ts/input/tex/mhchem/MhchemConfiguration.ts
mathjax3-ts/input/tex/mhchem/mhchem_parser.d.ts
mathjax3-ts/input/tex/mhchem/mhchem_parser.js

This PR makes several changes to the TeX input jax and it configuration object.
1.  The handling of options to the TeX jax is reorganized a bit in order to process the options before setting up the configuration.  This allows the `packages` option to be processed for `APPEND` and `REMOVE` values (like the arrays), rather than pulling out the `packages` option by hand initially (and not handling `APPEND`/`REMOVE`).
2. A second initialization function is added to the configuration objects, and this is called after the TeX jax and its `parseOptions` object is set up.  This allows configurations to initialize themselves based on the user-provided options (e.g., the `configMacros` extension needs access to the user-supplied `macros` option, which is not available during the …

Update TeX input jax

---

mathjax3-ts/core/MathDocument.ts
mathjax3-ts/input/tex/ams_cd/AmsCdConfiguration.ts
mathjax3-ts/input/tex/ams_cd/AmsCdMethods.ts
mathjax3-ts/input/tex/color/ColorConfiguration.ts
mathjax3-ts/input/tex/color/ColorMethods.ts
mathjax3-ts/input/tex/noerrors/NoErrorsConfiguration.ts

This updates existing TeX packages to use the new configuration functionality, and to make them work with the `\require` macro (coming in a PR shortly).  This includes moving options into sub-blocks, for example, the `amsCd` options are moved into an `amsCd` block, and you would configure the TeX jax using
```
new TeX({
packages: {[APPEND]: ['amsCd']},
amsCd: {
colspace: '10pt',
rowspace: '10pt'
}
});
```
for example.  This makes it clearer what those options refer to.  In addition to the `amsCd` options, the `color` extension's options are moved to a `color` block.
The `noerrors` package now adds a `data-mix-error` attribute that stores the actual error message (for easier retrieval), and the similar error attribute for "Math input error" messages `MathDocument` class has been moved to …

Update TeX packages

---

mathjax3-ts/input/tex/require/RequireConfiguration.ts

This PR adds a `require` package that implements the `\require` macro in situations where the `loader` component is available.  This will be the case for components loaded from the CDN, or components loaded into node, or node applications that load the loader code directly.

Require package

---

mathjax3-ts/input/tex/config_macros/ConfigMacrosConfiguration.ts

This PR adds a package that allows the TeX input jax options to include a `macros` block that declares macros to be predefined within the TeX jax.  This is similar to the `Macros` option from v2.

Config macros package

---

samples/tex-json.js
samples/tex-string.js
samples/tex2html.js
samples/tex2mml.js

Removes no longer existing TestMath from some of the files.
Before I continue, we should discuss, which of these are still useful. 
For example, it seems to me that `tex-nodes.js` does the same as `tex2mml.js`.

Rewrites some TeX sample files to remove TestMath.

---

mathjax3-ts/input/tex/autoload/AutoloadConfiguration.ts

This PR provides a TeX package that defines macros to automatically load the packages that implements them.  This is similar to the `autoload-all` extension in v2.  The extensions that it will autoload are configurable in the TeX input jax options, so you could do
```
new TeX({
packages: {[APPEND]: ['autoload'},
autoload: {
color: []
}
});
```
to autoload everything except the color extension (thus leaving the original `\color` definition from v2), for example.  You could also add autoloading of other extensions, if desired.
All the current extensions are autoloaded except for `ams` and `physics`, the former because of the large number of macros (and because it is included in the standard tex component), and physics because it redefines standard macros, so should only be included …

Autoload package

---

mathjax3-ts/input/tex/tag_format/TagFormatConfiguration.ts

This PR add the `tagFormat` extension that allows page-author control of the formatting of tags and their IDs, similar to the v2 `formatNumber`, `formatTag`, `formatID` and `formatURL` options.  This would allow page authors to include section numbers in their automatic equation numbering, for example, or to use custom IDs for the HTML tags for the numbers.
The code will subclass whatever tag class is selected by the user (in the `tags` option), so it should work for any of the tagging modes currently available.

Tag format package

---

mathjax3-ts/output/chtml/Wrappers/TextNode.ts

I found a wrong css property name in mathjax3-ts/output/chtml/Wrappers/TextNode.ts. I changed the property name from `'white space'` to `'white-space'` at `mjx-measure-text`.

Fix a wrong css property name in TextNode.ts

---

mathjax3-ts/input/tex/action/ActionConfiguration.ts

Removes imports in `ActionConfiguration.ts`. They must have come in by carelessly copying the configuration of the `extpfeil` package.

Removes unnecessary imports.

---

mathjax3-ts/util/string.ts

Computation in `unicodeChars` was incorrect as the counter was incremented after the computation only. 
Took me a while to track down.
Overall, we have the surrogate pair computation in a number of places, we should combine those at some point.

Fixes incorrect computation of surrogate pair unicode chars.

---

components/src/input/tex/extensions/all-packages/all-packages.js
mathjax3-ts/input/tex/AllPackages.ts

Move `preLoad()` from component to `AllPackages.ts` so that if `AllPackages.js` is imported directly into a node project, `\require` won't try to reload these packages.
Also, fix incorrect package name for `amsCd`, and move `configMacros` to the end so that user macros will override package macros.

Fixes to AllPackages.ts

---

mathjax3-ts/output/chtml/Wrappers/TextNode.ts
mathjax3-ts/output/chtml/Wrappers/mo.ts
mathjax3-ts/output/chtml/fonts/tex.ts

Fix problem where `\vec` did not produce the right character (the font CSS was being overriden), and where stretchy horizontal characters could be too long if the extender had to be shorter than its natural length.
The change in `TextNode.ts` was to remove a redundant CSS specification.
The change in `mo.ts` was to get horizontal stretchy characters to be the right length when the extender is shorter than the character's natural length (the older version would cause the extender to have a minimum width of the character's natural width, and so the length of the stretched character as a whole would be too long).
The change to `fonts/tex.js` is to prevent those CSS rules from overriding the ones set for the individual characters (it was preventing the `\vec` from specifying an alternate …

Fix \vec and stretchy horizontal characters in CHTML

---

mathjax3-ts/output/chtml/Wrappers/maction.ts
mathjax3-ts/output/common/Wrappers/maction.ts
mathjax3-ts/output/svg/Wrappers/maction.ts

This PR fixes some problems with tools tips in CHTML and SVG output.  In CHTML, the tooltips could fall underneath later mathematics, so this adds a `z-index` to raise the tooltip above the rest of the math.  There was also a problem in both CHTML and SVG where an expression that has multiple tooltips could leave an earlier tooltip open when the mouse moved from its trigger to another tooltip trigger.  This was because the timers for the show/hide operations were stored in a global variable; this fix tracks them by the element they are attached to, so multiple ones can operate at once, and you don't lose the hide from an earlier one when you start a show on a new one.

Give tooltips a z-index, and track tooltip show/hide separately.

---

mathjax3-ts/input/tex/base/BaseItems.ts

Make the `equation` stack item be an open item so that if it contains `\over`, it will be processed properly.
Currently,
```
\begin{equation}
x \over y
\end{equation}
```
produces an 'x' followed by an empty fraction.

Fix equation stack item to handle \over

---

mathjax3-ts/output/svg.ts

This fixes a problem in SVG output which caused the global `<defs>` element to be missing from the page when `fontCache: 'global'` is specified (the default is `'local'` font caching within each equation).

Correct name of function to produce page elements

---

mathjax3-ts/components/loader.ts

Use `src` property rather than attribute in order to get full path when determining the MathJax root URL.  The attribute is whatever was used in the page itself, but the property is the full path.

Fix detection of MathJax root URL

---

mathjax3-ts/adaptors/lite/Parser.ts

Ignore comments and text when looking for a single child after parsing an HTML string.  (This is while looking to see if the parsed string includes an `<html>` or `<head>` or `<body>` that needs to be moved into place in the `liteDocument` structure.
Before this patch, if the string was
```
<!DOCTYPE html>
<html>
...
</html>
```
then the `DOCTYPE` comment would prevent the parser from recognizing the `<html>` element, and it would not be moved (so would remain incorrectly nested in the body of the original document).

Fix problem with parsing HTML strings that include comments and text

---

mathjax3-ts/core/MathItem.ts

This adds a missing function `convert()` in the interface for MathItems and corrects the jsdoc for it.

Add missing convert() from interface and update jsdoc

---

components/src/input/tex-full/tex-full.js
components/src/input/tex/extensions/all-packages/all-packages.js
components/src/input/tex/extensions/all-packages/build.json
mathjax3-ts/input/tex/AllPackages.ts

Remove `require` from `AllPackages.ts` (since it forces loading of loader/startup code), and put it into the `tex-full` and `all-packages` components directly.  Remove `physics` from the `AllPackages` list, since it conflicts with standard definitions.  Authors who want `physics` or `require` must add them to their package list by hand, e.g.,
```
packages: [...AllPackages, 'require', 'physics']
```
Finally, remove `preload()` calls for the TeX extensions from `tex-full`, since the preload is now done in `AllPackages.ts` (when the loader has been used).

Remove dependency on loader/startup from AllPackages

---

mathjax3-ts/input/tex/Configuration.ts
mathjax3-ts/input/tex/require/RequireConfiguration.ts

This PR fixes a problem with `require` and `autoload` where packages with dependencies would cause the dependent packages to be appended a second time if they were already appended as part of the initial `packages` option when the TeX input jax was created.  This is because the require extension only kept track of the packages that it loaded, not the initial ones.  This adds the initial packages to the loaded package list.
It also fixes the configuration registration function to add the configurations StackItems to the configuration (this was accidentally left out initially).
Finally, it fixes a problem with removing the `[tex]/` prefix from extension package names when the prefix name has been changed in the configuration.

Fixes for require and autoload

---

mathjax3-ts/output/svg/Wrappers/mo.ts

Properly include depth in positioning and viewBox for horizontal stretchy characters. 
Resolves issue #264.

Fix problem with \underline.  #264

---

mathjax3-ts/input/tex/mhchem/mhchem_parser.js

This PR makes `mhchem_parser.js` a CommonJS module rather than an es6 module, so that it can more easily be used in webpack and other packaging tools.  See issue #268.

Fix mhchem_parser.js module structure.  #268

---

lib/v3-lab.js
mathjax3-ts/components/startup.ts
mathjax3-ts/core/MathDocument.ts
mathjax3-ts/output/common/OutputJax.ts

This PR adds a `getMetricsFor()` method to common output jax, and uses it in the startup code and lab.  This will make it easier to use `convert()` in some cases, such as the demos in the [node demos](https://github.com/mathjax/mj3-demos-node) repository.  See issue #269.

Add ability to get font metrics for a given element.  #269

---

mathjax3-ts/core/MmlTree/MmlNodes/mo.ts
mathjax3-ts/input/tex/NodeUtil.ts

This PR preserves the `texClass` that has been set by the TeX input jax (it was being ovewritten by the data from the operator dictionary).  To tell when TeX has set it, we set a `texClass` property on the node, otherwise we don't know if it was the value set by the constructor or the TeX input jax.
This resolves issue #121.

Prevent texClass from being overwritten.  #121

---

mathjax3-ts/components/startup.ts

This PR fixes the startup module to perfrom the `pageReady()` function when the page is ready, which was defined in the configuration, but never actually executed.  It also makes the typeset promise always be defined, even if no typesetting occurs (this makes it easier to use, as you don't have to test for a null value).

Fix missing support for pageReady() in startup module

---

mathjax3-ts/a11y/complexity/collapse.ts
mathjax3-ts/a11y/explorer/Explorer.ts

Two corrections to  allow collapsing with keyboard in explorer:
* `maction` nodes added in `collapse.ts` get a unique id.
* Does no longer map `CHTML` to old `CommonHTML` highlighter.  Note, this only works with the latest `develop` branch in SRE.

Corrects some explorer problems.

---

mathjax3-ts/input/tex/cancel/CancelConfiguration.ts
mathjax3-ts/output/common/Notation.ts

Make `northeastarrow` remove `updiagonalarrow`, and vice versa, so there won't be duplicate elements in the oputput.  Make `\cancelto` use `northeastarrow` (as well as `updiagonalarrow` and `updiogonalstrike`) since that is what is in the MathML spec.

Better handling of arrows in menclose

---

mathjax3-ts/input/tex/newcommand/NewcommandConfiguration.ts

Make newcommand `init()` check that it hasn't already been called before appending its handlers.  This is because other extensions (namely `extpfeil`) can call the newcommand `init()` function themselves, and that would mean that a new set of handlers would be added at that point.  So if macros had already been defined in the earlier handlers, those could be lost.
For example, without this patch
```
\def\x{xyz}
\require{extpfeil}
\x
```
would produce an `Undefined control sequence \x` message (if `extpfeil` hadn't been loaded already).
The PR also reformats the spacing in the configuration object.

Make newcommand init() not append handlers twice.

---

lib/v3-lab.js
v3-lab.html

Adds an optional second output region to the v3 lab. It renders the same input but with a different mathitem. This is useful for testing against interaction of stateful tools like the explorer.

Adds a second output region to the v3 lab.

---

mathjax3-ts/a11y/explorer.ts
mathjax3-ts/a11y/explorer/Explorer.ts
mathjax3-ts/a11y/explorer/Region.ts

The PR ensures compatibility when multiple explorers are used in parallel. For demo purposes there are currently 5 explorers switched on: two `SpeechExplorer`s, one `Magnifier`, two `MouseExplorer`s. It should be run with SRE compiled form the `rule_cycling` branch.
Ultimately they all should be switchable via the menu. The second `SpeechExplorer` will become the Braille explorer, with a hidden live region.
There are a still some minor glitches on collapse/expand when the DOM update is slower than the update of regions, but I can't really see how to avoid this.

Combines multiple explorers.

---

mathjax3-ts/a11y/explorer/Explorer.ts
mathjax3-ts/a11y/semantic-enrich.ts
mathjax3-ts/output/chtml/Wrappers/math.ts
mathjax3-ts/output/svg.ts
mathjax3-ts/output/svg/Wrappers/math.ts

This PR moves the `aria-label` attributes to the `mjx-container` rather than the element corresponding to the math element, and makes the internal svg `title` element optional (so that it can be included in conversions from tex to svg, for example, where the `mjx-container` is not retained.  This is controlled by the `internalSpeechTitles` option for the SVG output jax.
It also adds `role="application"` when the explorer is present (should this always be set when speech is attached?), and adds `role="img" focusable="false"` to svg elements, as in v2.

Update speech support

---

mathjax3-ts/components/startup.ts

This PR changes `MathJax.Typeset()` to `MathJax.typeset()` and similarly for two other functions, in order to follow our function naming conventions.

Change case of typeset functions created by setup.js

---

lib/v3-lab.js

The enrich and complexity checkboxes aren't properly preserved if collapsible or explorer are not also checked (this is because the menu code unsets them during the initialization of the explorer and collapsible menu items.  Moving the setting of those value to *before* when the menu callbacks are set resolves that problem.
The `autoload` checkbox isn't preserved properly by "keep"; explicitly setting values to false (not just true) during initialization resolves that issue.

Update lab to save checkboxes properly when "keep" is used

---

mathjax3-ts/a11y/explorer/Region.ts

This PR fixes the magnifier for SVG elements to have the proper bounding box.
Both the SVG and HTML magnifier doesn't get the scaling factor correct when there is scaling caused by container elements that have been removed (e.g., contents of superscripts).  Perhaps that is OK, but it does mean the magnified result may be too big (or too small in some cases) compared to the original size.
It might be possible to walk up the tree and take transformations into account.  Alternatively, the output could be modified to include scaling information (which is already being computed by both output jax) as attributes so that the explorer could pick that up.  The explorer could turn on/off an output option that controls that, for example.
Also, SVG expressions with tags don't work properly.  This is …

Fix size of SVG viewBox for magnifier.

---

mathjax3-ts/a11y/explorer.ts
mathjax3-ts/a11y/explorer/Explorer.ts
mathjax3-ts/a11y/explorer/Region.ts
mathjax3-ts/a11y/sre_browser.d.ts
mathjax3-ts/ui/menu/Menu.ts

Restores the customisation of highlighting.
* Adds appropriate `a11y` options.
* Refactors highlighting functionality common to explorers into the abstract superclass.
* Integrates with the Menu.

A11y contrast

---

mathjax3-ts/a11y/explorer.ts
mathjax3-ts/a11y/explorer/Explorer.ts
mathjax3-ts/a11y/sre_browser.d.ts

Updates the explorer to restart correctly after re-rendering events, like expand/collapse.
Note, that the way the old explorer is attached is not very elegant. Once I've added the Braille explorer, this will be handled in a more extensible way.

A11y explorer

---

mathjax3-ts/a11y/explorer.ts
mathjax3-ts/a11y/explorer/Explorer.ts
mathjax3-ts/a11y/explorer/Region.ts
mathjax3-ts/a11y/sre_browser.d.ts
mathjax3-ts/ui/menu/Menu.ts

Adds selective subtitle for speech.
Also adds options in an `a11y` category for the `Explorer` mixin that holds the custuomisable information for the different types of explorers.
I am thinking it might be cleaner to add that to a more dedicated class.  There is already a dummy type `A11yDocument` in `Region.js` that could serve that purpose. We could also add that via an `A11y` mixin (from which the `Explorer` mixin could inherit). We should discuss what the cleaner design is .
I also have not quite figured out how the initial menu selections are passed into the document options.

A11y subtitle selection.

---

lib/v3-lab.js
mathjax3-ts/components/startup.ts

Replaces `TypesetPromise` by `typesetPromise` in two places:
* Fixes the spelling in the lab.
* Fixes spelling in `startup.ts`, although I could not produce an error with the old cap spelling.

Fixes mispelled typesetPromise method.

---

mathjax3-ts/a11y/explorer/Region.ts

Fixes the problem that the magnification region is highlighted twice in CHTML that was reintroduced in PR #297.

Fixes problem with double highlighting in CHTML magnifier.

---

mathjax3-ts/a11y/explorer.ts
mathjax3-ts/a11y/explorer/Explorer.ts
mathjax3-ts/a11y/explorer/KeyExplorer.ts
mathjax3-ts/a11y/explorer/MouseExplorer.ts
mathjax3-ts/a11y/explorer/Region.ts
mathjax3-ts/a11y/sre_browser.d.ts

Major refactoring of `Explorer` and `Region` module:
* Introduces type template for regions of explorers.
* Separates mouse and keyboard explorers into their own files.
* Introduces a number of explorers (including the old hover highlighter).
* Cleans up use of `sre` methods and the type file.
* Adds all missing comments. 
* SVG/CHTML works well together without extra cases with the exception of the magnification. 
Missing bits are now listed in Issue #303

A11y explorer refactor

---

components/src/tex-chtml-full/preload.js
components/src/tex-chtml-full/tex-chtml-full.js
components/src/tex-chtml-full/webpack.config.js
components/src/tex-svg-full/preload.js
components/src/tex-svg-full/tex-svg-full.js
components/src/tex-svg-full/webpack.config.js

This adds two new components, `tex-chtml-full` and `tex-svg-full` that include the `tex-full` components (i.e., contain all the extensions).  This makes them about 120K larger than the `tex-chtml` and `tex-svg` versions, which use `\require` or `autoload` to obtain extensions that aren't included.
I didn't include full versions of `tex-mml-chtml` or `tex-mml-svg`.  Should I?

Add combined components that contain tex-full

---

components/src/input/asciimath/asciimath.js
components/src/input/asciimath/build.json
components/src/input/asciimath/webpack.config.js
components/src/source.js
mathjax2/input/AsciiMath.js
mathjax2/legacy/MathJax.js
samples/asciimath2mml.js

This PR creates an `input/asciimath` component (using the legacy v2 AsciiMath input jax).  It adjusts the legacy code in a couple of places to allow it to webpack properly.  The component is fairly large, since it includes a lot of Mathjax v2 in it, so I'm not making any combined input-output components that use it.  Authors will have to load the AsciiMath component by hand if they want to use it.
I did some (minimal) performance testing, and using a test file with 22 expressions, mathjax-node-page takes 1.4 seconds, while version 3 with this component is about .45 seconds, so I think that even with the v2 glue, it is still faster over all.

Add an AsciiMath component (using legacy v2 code)

---

mathjax3-ts/output/svg/Wrapper.ts

Make `xlink:href` attribute work properly in WebKit serialization.
Resolves issue #306

Fix problem with SVG serialization in WebKit.  #306.

---

mathjax3-ts/a11y/explorer.ts
mathjax3-ts/a11y/explorer/Explorer.ts
mathjax3-ts/a11y/explorer/KeyExplorer.ts
mathjax3-ts/a11y/explorer/MouseExplorer.ts
mathjax3-ts/a11y/explorer/Region.ts
mathjax3-ts/a11y/explorer/TreeExplorer.ts
mathjax3-ts/a11y/sre_browser.d.ts
mathjax3-ts/ui/menu/Menu.ts

PR takes care of a number of points in issue #303 
* Implements tree explorers: Instances are the Tree-coloring and the old Flamer.
* Integrates all explorers fully with the menu.
* Moves the A11y menu elements to the position we had already discussed.
* A11y options are fully set in the a11y code only.
There are still some restart issues in particular on collapse/expand actions, which will be done with custom events as discussed.

A11y tree explorer

---

mathjax3-ts/components/startup.ts
mathjax3-ts/ui/menu/Menu.ts

This PR makes `getDocument()` return the document (so that it can be used to create additional documents, if needed, e.g., for multiple iframes or web components).  It also moves the creation of the original document into the `getComponents()` function rather than the `makeMethods()` function, since that seems more natural.

Startup document

---

mathjax3-ts/components/startup.ts

Move the initial typeset call into `pageReady()` (since that is when the typeset occurs), and make a default version of it, so it is parallel to the `ready()` function.  This is a better separation of duties, and makes it easier to use the `ready()` and `pageReady()` functions.  It also removes the `pagePromise`, since it is not really necessary to have two promises, and `promise` already waits on `pagePromise`.

Refactor startup ready() and pageReady() calls

---

mathjax3-ts/input/tex/base/BaseItems.ts
mathjax3-ts/input/tex/base/BaseMethods.ts

The `NodeUtil.isType(node, type)` function uses `node.isKind(type)`, which in turn tests if node is an instance of the class for the given type, or one of its subclasses.  Since `MmlMsup` is a subclass of `MmlMsubsup`, that means `NodeUtil.isType(node, 'msubsup')` will be true when `node` is an `MmlMsup`.  This call is replacing a version 2 test of `node.type === 'msubsup'`, which fails when `node` is an `msup` node.  So the version 3 code doesn't act the same as the version 2 code.  This caused `\boldsymbol{c'}^2` to incorrectly report a double exponent.
This PR fixes the test to exclude `msup` nodes in this case, and the similar case with double primes, e.g. `\boldsymbol{c'}'`.
Resolves issue #314.

Fix use of isType() for msubsup and munderover. #314

---

mathjax3-ts/input/tex/Tags.ts

Tags are not being applied to starred environments.  This PR fixes that.  The file diff is a bit awkward; the new code is
https://github.com/mathjax/mathjax-v3/blob/ffb3591a6402817b197466b71f28ae0d91d4bc5a/mathjax3-ts/input/tex/Tags.ts#L399-L406
The old code returned `null` if there was no automatic numbering rather than checking if there was an explicit tag and returning that.
Resolves issue #316

Make tags work for starred environments.  #316

---

mathjax3-ts/core/MmlTree/MmlNodes/mrow.ts

The index wasn't being incremented, so the core element was not being properly located.  Argh!

Fix isEmbellished() to properly locate the core element in an mrow

---

mathjax3-ts/core/MmlTree/MmlNodes/mo.ts

Fixes a problem where `lspace`/`rspace` on an `mo` weren't being taken into account properly when TeX spacing is being used.  They are supposed to override the TeX spacing, but weren't.  For example, 
```
<math display="block">
<mi>x</mi>
<mrow>
<mtext>x</mtext>
<mo lspace="1em">=</mo>
<mtext>y</mtext>
</mrow>
<mi>y</mi>
</math>
```
should put 1em of space between the two x's, but didn't.  This PR resolves that.

Fix problem with explicit lspace/rspace

---

mathjax3-ts/components/startup.ts

The `texReset()` command should have a parameter that allows it to set the starting equation number.  This PR adds one.

Add start number parameter to MathJax.texReset()

---

mathjax3-ts/input/mathml.ts

Remove unused `DOMParser` option, and use the adaptor in the `parseError()` function rather than assuming that the `node` is an `HTMLElement`.

Minor fixes to MathML input jax

---

mathjax3-ts/output/chtml/Wrappers.ts
mathjax3-ts/output/chtml/Wrappers/mtext.ts
mathjax3-ts/output/common/OutputJax.ts
mathjax3-ts/output/common/Wrappers/mtext.ts
mathjax3-ts/output/svg/Wrappers.ts
mathjax3-ts/output/svg/Wrappers/mtext.ts

Add support for missing `minScale` and `mtextInheritFont` configuration options, and add new `merrorInheritFont` option.  This required adding new `mtext` wrappers (since the default wrapper actions are no longer sufficient).

Support for additional output configuration options

---

components/src/startup/webpack.config.js
mathjax3-ts/components/startup.ts

This PR updates `mathjax3-ts/components/startup.js` to have fewer dependencies (i.e., not rely on `output/common/OutputJax.js`), and to link to the core library for `core/MathItem.js` (since it is not needed until after core will be loaded).  This reduces the component size from 47KB to 18KB.

Slim down the startup component

---

mathjax3-ts/handlers/html/HTMLDomStrings.ts
mathjax3-ts/input/tex/Tags.ts
mathjax3-ts/input/tex/ams/AmsConfiguration.ts
mathjax3-ts/input/tex/ams/AmsMethods.ts
mathjax3-ts/input/tex/base/BaseMethods.ts

As per our face-to-face discussion, this PR normalizes the case of several TeX input options, includes `Html` in the names of `skipTags`, and other FindMath options, and changes the default values of `ignoreHtmlClass` and `processHtmlClass`.

Update names of some options

---

.gitignore
components/bin/makeAll
components/src/mml-chtml/test.html
components/src/mml-chtml/test.js
components/src/mml-svg/test.html
components/src/mml-svg/test.js
components/src/output/chtml/fonts/tex/copy.json
components/src/sre/copy.json
components/src/tex-chtml/test.html
components/src/tex-chtml/test.js
components/src/tex-mml-chtml/test.html
components/src/tex-mml-chtml/test.js
components/src/tex-mml-svg/test.html
components/src/tex-mml-svg/test.js
components/src/tex-svg/test.html
components/src/tex-svg/test.js
components/webpack.common.js
lib/v3-lab.js
package.json

This PR moves the `components/dist` folder to the top-level `es5` directory, as per our face-to-face yesterday.  Most of the fixes are in the various test files, which eventually will be moved to the separate development repository.  
In addition, I added an npm script for creating the components, and fixed the `makeAll` command to work on windows (see mathjax/mj3-demos-node#2).

Rename components/dist to es5

---

components/src/node-main/node-main.js
components/src/node-main/webpack.config.js
package.json

This PR adds a `node-main` component and makes it the default for node `require('mathjax-full')`.
This lets you do
```
require('mathjax-full').init({
...configuration...
}).then((MathJax) => {
...your MathJax code...
}).catch((err) => console.error(err.message));
```
to load, configure, and run MathJax code.

Add node-main component

---

components/src/output/svg/svg.js
ts/core/InputJax.ts
ts/core/MathItem.ts
ts/core/OutputJax.ts
ts/input/asciimath.ts
ts/input/mathml.ts
ts/input/tex.ts
ts/input/tex/bussproofs/BussproofsConfiguration.ts
ts/input/tex/bussproofs/BussproofsUtil.ts
ts/output/common/OutputJax.ts

This PR changes how `bussproofs` obtains a MathDocument and OutputJax.  It should use the actual MathDocument and OutputJax in use, since (in the future) these will be able to specify the font in use, and that will affect the spacing.  So we don't want to use a generic math document and output jax, but the specific one in use for the document.
Unfortunately, the InputJax doesn't have access to the MathDocument when it is created (since the InputJax is instantiated before the MathDocument), so the TeX extensions don't have access to it while they are initialized.
In order to overcome this, I've added the MathDocument to the arguments to `InputJax.compile()` function (it probably should have had that to begin with), and pass it along to the pre- and post-filters via …

Fix Bussproofs handing of document and output jax

---

package-lock.json
package.json

Moving sre v3.0.0-beta.6 in the build. 
As usual there's been some unexpected upgrades in the `package-lock.json` file. I can remove those if you think it safer.

SRE version bump.

---

ts/core/MathDocument.ts

I believe conversion should stop with the end state and not before that. 
Just as an example from our `tex2html.js` sample:
```JavaScript
let math = html.convert(process.argv[3] || '', {end: STATE.TYPESET});
console.log(adaptor.outerHTML(math));
```
Here conversion should stop with typesetting and not before. Otherwise we get the wrong element back. We want a `HTML` node (in our case a `LiteElement`) and not the `MathItem`.

Stops conversion once priority is greater than end only.

---

components/src/input/tex/extensions/ams_cd/amscd.js
components/src/input/tex/extensions/ams_cd/build.json
components/src/input/tex/extensions/ams_cd/webpack.config.js

This correctly capitalizes the `amsCd` component so that it will load properly.
Resolves issue #335.

Fix name for amsCd component.  #335

---

ts/output/chtml/Wrappers/mtr.ts

Make sure `mjx-mtr` CSS is produced when only `mlabeledtr` are used on the page, since `mlabeledtr` use `mjx-mtr` elements that are created by hand internally in CHTML.
Resolves issue mathjax/MathJax#2200.

[CHTML] Fix problem with tags being displayed horizontally. mathjax/MathJax#2200

---

ts/core/MmlTree/MmlNode.ts

Correct the default `texClass` for `AbstractMmlBaseNode` elements. It should be `TEXCLASS.ORD`, not `TEXCLASS.NONE`.  This affects the situation when the base of the exponent is not a simple symbol, like when it is `\mathbb{...}` or even just `{...}`.
Resolves mathjax/MathJax#2187

Fix spacing around super- and subscripts.  mathjax/MathJax#2187

---

ts/input/tex/tag_format/TagFormatConfiguration.ts

Because tag formats that are defined by TeX packages (like the `ams` tag format) are not installed in the TagFactory until after the packages are fully initialized and configured, the `tagFormat` package can't locate the `ams` tag format when it needs to subclass it.  Fortunately, they are available in the Configuration object.  This PR changes `tagFormat` to look in the configuration for the tag format and adds it to the TagFactory so that the format will be available when it needs it.
We set the configuration priority to 10 so that it comes after normal packages, so that any that create tag formats will already be added to the main configuration, so we can find those tag formats there.
Resolves issue mathjax/MathJax#2201

Fix tagFormat to allow it to work with ams tags.  mathjax/MathJax#2201

---

ts/handlers/html/HTMLDocument.ts

Make sure we use text nodes for the start and end locations (there can be `<br>` nodes in the list, since they are allowed inside math).  We want to make sure we skip over them.
Resolves issue mathjax/MathJax#2202

Fix problem with math following <br>.  mathjax/MathJax#2202

---

ts/output/svg.ts

This PR adds CSS to the `mjx-container` to force the direction to be `ltr` in SVG output.  This is needed for when SVG output is used in an `rtl` context, as described by issue mathjax/MathJax#2204.

Add CSS to force LTR direction for SVG output.  Resolves issue #2204

---

ts/a11y/semantic-enrich.ts

Fixes the aria-label computation in `semantic-enrich` by recursing to the semantic root node of the node if necessary.

A11y aria labels computation

---

ts/a11y/explorer.ts

Sets the `enrichspeech` option by default to `shallow` so aria labels will be computed when a11y is active.

Override for enrichSpeech option to general aria labels in A11y.

---

ts/output/chtml/Wrappers/mtable.ts

Adjust for .5ex offset in CSS `vertical-align: middle` (see the [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align#Parent-relative_values)).  This sets CSS to compensate, and removes unneeded CSS that would have overriden this.
Resolves issues mathjax/MathJax#2186 and mathjax/MathJax#2203.

Fix alignment problem with mtables.  mathjax/MathJax#2186

---

ts/output/svg.ts

Use `min-width` on outermost `svg` element when labels are present to prevent the main expression from shrinking if the window size shrinks (e.g., during zooming).
Resolves issue mathjax/MathJax-demos-web#17.

Fix scaling of zoomed multline environments with tags.  mathjax/MathJax-demos-web#17

---

ts/output/chtml/Wrappers/TeXAtom.ts
ts/output/svg/Wrappers/TeXAtom.ts

This PR adds an attribute to CHTML and SVG output for the TeXAtom elements that identifies the texClass of the element.  This was prompted by the discussion in mathjax/MathJax#2193

Add attribute to identify texClass for TeXAtom output. mathjax/MathJax#2193

---

ts/core/MathDocument.ts
ts/handlers/html/HTMLMathItem.ts
ts/output/common/OutputJax.ts

If a typeset expression has been removed from the page, typesetting again can cause an error when the metrics are being determined.  This PR checks that the location where the metrics are being taken has a parent element before trying to use it.
Resolves issue mathjax/MathJax#2191.

Check that parent is defined before getting its metrics.  mathjax/MathJax#2191

---

README.md

* Missing whitespace between words
* Consistent spelling for `JavaScript` and `TypeScript`

Fix some README typos & spelling

---

ts/core/MmlTree/SerializedMmlVisitor.ts
ts/output/chtml/Wrapper.ts
ts/output/svg/Wrapper.ts

Fix problem with handling of multiple classes being added to the output, and fix problem with multiple classes being added to TeXAtom output during serialization of the internal MathML.
Resolves mathjax/MathJax#2185.  See that issue for examples.

Fix multiple issues with handling of classlist.  mathjax/MathJax#2185

---

ts/output/chtml/Wrappers/msubsup.ts

Make sure styles for `msubsup` are output when called from `munderover` with `movablelimits`.  
Resolves issue mathjax/MathJax#2221.

Fix operator with movable limits when no other super- or subscripts are used.  mathjax/MathJax#2221

---

ts/adaptors/lite/Parser.ts

This PR fixes the liteDOM to handle self-closing tags (in particular, for MathML that has things like `<mspace width="1em" />` or `<mrow/>`).
Resolves issue #328

Handle self-closing tags in liteDOM.  #328

---

ts/output/chtml.ts
ts/output/chtml/Wrappers/TextNode.ts
ts/output/svg.ts

Improve bounding box for unknown characters (slightly smaller to make square roots work better), and properly place and scale the bbox in CHTML output.
In CommonHTML the baseline was not always right (so we add the MJXZERO font to fix that), and the `font-size` was affecting the `padding`, so compensate for that.  Finally, the CSS for the `mjx-measure-text` was not actually present at the time the measurement is being done (oops), so make the CSS explicit.

Better bbox for unknown characters

---

ts/core/MmlTree/MmlNode.ts
ts/core/MmlTree/SerializedMmlVisitor.ts
ts/input/mathml/MathMLCompile.ts

This PR modifies the `XMLnode` object (which holds the XML content of an `annotation-xml` element) so that its contents can be serialized.  To do this, we store the adaptor from the input jax in the XML node so that it can be used to serialize the xml content when needed.  The `SerializeMmlVisitor` uses the new function of the `XMLnode` to serialize it.  The MathML input jax is modified to pass the adaptor along, but it looks like more because I made a local `adaptor` variable to simplify `this.adaptor` calls.

Add support for serializing annotation-xml contents

---

ts/input/tex/FilterUtil.ts
ts/output/chtml/Wrappers/semantics.ts
ts/output/common/OutputJax.ts
ts/output/svg/Wrappers/semantics.ts

This PR provides support for measuring the contents of `annotation-xml` nodes in the browser.  It also fixes SVG output for these, which was broken since it didn't specify the size of the `foreignObject` elements.  It also fixes a problem where TeX input that includes `annotation-xml` would fail during the `cleanAttributes()` filter.
Resolves issue mathjax/MathJax#2210

Improve support for annotation-xml mathjax/MathJax#2210

---

ts/input/tex.ts
ts/input/tex/FilterUtil.ts
ts/output/common/Wrappers/scriptbase.ts

This PR adds a new post-filter to the TeX input jax that converts in-line `munderover`, `munder`, and `mover` elements with the `movablelimits` property that have a base that is not an `mo` (e.g., `\mathop{xyz}` into an explicit `msubsup`, `msub`, or `msup` element.  This means the internal MathML will be correct MathML (rather than relying on the TeX-supplied `movablelimits` property), so the output jax don't have to look for that property any more and can just go by the attribute on the core mo.  It also means the `SerializeMmlVisitor` won't have to be modified to take the property into account (it currently outputs incorrect MathML for these situations).

Improve movablelimits support

---

ts/core/MmlTree/MmlNode.ts

Use script-style spacing if either of a pair of neighboring elements is in script-style (rather than requiring both to be).  This means that `<mspace>` wrapped in `<mstyle scriptstyle="0">` (as used for the fixed-size spaces in TeX) won't include extra spaces.
Resolves issue mathjax/MathJax#2241

Fix spacing problems in superscripts.  mathjax/MathJax#2241

---

ts/core/MmlTree/MmlNodes/mo.ts
ts/input/tex/ParseUtil.ts
ts/input/tex/base/BaseMethods.ts

Remove the `mi2mo()` action for `munderover` and related constructs (since a TeX input post-filter now handles non-`mo` elements that have movable limits).  In addition, it fixes a problem where an explicitly set `texClass` could be lost if `lspace` or `rspace` was set (this was the case with `mi2mo()`, but now that that is removed).  This was a cause for some test failures from mathjax/MathJax-dev#30.  But these changes will require additional update to those tests, since the `mi` are no longer changed to `mo`.
Finally, it also adds missing jsdoc comments to one function.

Remove mi2mo action

---

ts/core/MmlTree/MmlNodes/mo.ts

Use getter/setter for `MmlMo.texClass` so that if it isn't set yet, we can look it up from the operator table.  Setting the inherited attributes will set the class, so lookups will no longer be needed.   This means, in particular, that the TeX input jax can use `texClass` internally (before inheritance) in `NodeUtil.getTexClass()` without having to worry about looking up the value itself.
Resolves issue #383.

Handle texClass for mo's before inheritance.  #383

---

ts/input/mathml/MathMLCompile.ts

Only remove actual spaces from token element contents (perserve non-breaking and other special spaces like U+2000 to U+200C).  Without this PR
```
<math>
<mi>x</mi>
<mo>&#xA0;</mo>
</mi>y</mi>
</math>
```
would remove the non-breaking space.

Preserve special spaces in token element contents

---

ts/components/package.ts
ts/util/asyncLoad/node.ts

Use node's `path` module to handle directories, so they work in Windows. 
Resolves issue #398

Better path handling.  #398

---

ts/input/tex/Stack.ts
ts/input/tex/StackItem.ts
ts/input/tex/base/BaseItems.ts

The local environment object should not be copied when pushing an array element on the stack.  This prevents fonts and other properties from being incorrectly copied into the first cell of the array.  E.g.
```
\bf \begin{array}{c} a & a\end{array}
```
should show two italic a's, not a bold one and an italic one.
Resolves issue mathjax/MathJax#2247.

Don't leak fonts and other properties to initial array entry.  mathjax/MathJax#2247

---

ts/input/tex/Tags.ts

Fix incorrect use of defaulTags, and report an error if the named tag class is not available.
Resolves (part of) issue #404

Better handling of undefined tag class.  #404

---

components/src/node-main/node-main.js

Properly obtain the `require()` command in a way that doesn't cause problems for webpack, and set the `mathjax` root path for the `loader` correctly regardless of webpacking or location of the node script.
Resolves issue #406.

Fix node-main.js to get require() and correct mathjax path.  #406

---

ts/adaptors/liteAdaptor.ts

Fix LiteAdaptor's `elementsByClass()` function so that it doesn't throw an error on `classes.find(name)`, and actually returns the elements found.  Also, fix `getElements()` to search the given `document`.
Resolves issue mathjax/MathJax#2278.

Fix LiteAdaptor's search for elements by class. mathjax/MathJax#2278.

---

ts/output/common/Wrappers/msqrt.ts

The formula to compute clearance in `sqrt` is contradicted with TeXBook definition. The result of this is that the base element is too close to the root bar. This might be a mistake in manual derivation as argued bellow unless this is purposely designed.
According to Rule 11 on TeXBook page 443 (Appendix G ).
The clearance value `psi`, which is `q` value in `getPQ`, is originally defined as `psi = t + p / 4`. 
Under condition `dy > bbox.h + bbox.d + psi`, where `dy = sbox.h + sbox.d - t`, `psi` will be changed to a new value `psi + (dy - (bbox.h + bbox.d + psi)) / 2` as stated in TeXBook.
The derivation for the condition `dy > bbox.h + bbox.d + psi` is right. 
```javascript
// since
dy = sbox.h + sbox.d - t
dy > bbox.h + bbox.d + psi
// so
sbox.h + sbox.d - t > bbox.h + bbox.d + psi …
```

Fixes a bug in msqrt when computing clearance value

---

ts/input/tex/TexParser.ts

Make `TexParser.Push()` handle inferred `mrow` by pushing the children instead of the inferred `mrow` itself.  Elements that take inferred `mrow` as children create them automatically, and inferred `mrow`s should not be pushed directly.  They are created by `ParseArg()` as a means of identifying collections of elements that need to be pushed separately, but that wasn't being done.  This PR fixes that oversight.
Resolves issue mathjax/MathJax#2261.

Make TexParser.Push() handle inferred mrows properly. mathjax/MathJax#2261

---

ts/input/tex/NodeFactory.ts

This PR prevents text and other nodes from being recorded by `addNode()` when they are created.  They were causing problems when the text was an existing property of an object (like `constructor`).
If the text really needs to be saved (and I don't see why it would), the `nodeLists` property in `addNode()` should be changes to a Map rather than an Object.
Resolves issue mathjax/MathJax#2283.

Only record actual 'node' nodes.  mathjax/MathJax#2283.

---

ts/core/MmlTree/SerializedMmlVisitor.ts
ts/input/mathml/MathMLCompile.ts

This PR exposes more internal properties via `data-mjx-*` attributes, including the `variantForm` property (mathjax/MathJax#2237) and the internal `mathvariant` values, like `-tex-calligraphic` (mathjax/MathJax#2238).  This also moves the data for TeXAtom nodes to `data-mjx-texclass` rather than using the `class` attribute for these.  Also, the xmlns attribute is added to math elements, if needed.
The MathML input jax is modified to read these and transfer the data back to the internal elements it creates.  It still looks for the corresponding values in the `class`, however, for backward compatibility with v2 output.  It also corrects the `caligraphic` misspelling.
Resolves issues mathjax/MathJax#2237, mathjax/MathJax#2238, and mathjax/MathJax#2214.
Also resolves issue from …

Add more data-mjx-* attributes to MathML serialization 

---

ts/adaptors/HTMLAdaptor.ts
ts/adaptors/liteAdaptor.ts
ts/output/svg/Wrapper.ts

This PR manages the `xlink` namespace in all adaptors so that the namespace appears in the adaptor's `outerHTML` and `innerHTML`, and also in the browser's `outerHTML` and `innerHTML`.  It also works with XMLSerializer, though the `<use>` elements will have `xmlns:xlink` attributes that are probably redundant since that is on the outer `<svg>` element.
Resolves issue #365, and replaces PR #366.

Fix duplicate xlink namespace in SVG output.  #365

---

ts/input/tex/Configuration.ts
ts/input/tex/require/RequireConfiguration.ts

Do a restart if a package loaded with `\require` has preprocessors (since they will need to run before the math is processed).  This allows `\require{bussproofs}` to be in the same expression as the proof itself.  (The Bussproofs package is the only one that uses preprocessors at the moment.)
Also, remove dupolication of pre- and post-processors from the `register()` function, since these are already added during the `config.config()` call just before that.
Without this patch, 
```
$$
\require{bussproofs}
\begin{prooftree}
\AxiomC{C}
\AxiomC{A}
\AxiomC{B}
\BinaryInfC{D}
\BinaryInfC{E}
\end{prooftree}
$$
```
would produce an error if the `bussproofs` extension was not loaded and included in the package list initially.

Make \require{bussproofs} work properly.

---

components/src/a11y/assistive-mml/assistive-mml.js
components/src/a11y/assistive-mml/build.json
components/src/a11y/assistive-mml/webpack.config.js
components/src/mml-chtml/mml-chtml.js
components/src/mml-chtml/preload.js
components/src/mml-svg/mml-svg.js
components/src/mml-svg/preload.js
components/src/source.js
components/src/tex-chtml-full/preload.js
components/src/tex-chtml-full/tex-chtml-full.js
components/src/tex-chtml/preload.js
components/src/tex-chtml/tex-chtml.js
components/src/tex-mml-chtml/preload.js
components/src/tex-mml-chtml/tex-mml-chtml.js
components/src/tex-mml-svg/preload.js
components/src/tex-mml-svg/tex-mml-svg.js
components/src/tex-svg-full/preload.js
components/src/tex-svg-full/tex-svg-full.js
components/src/tex-svg/preload.js
components/src/tex-svg/tex-svg.js
ts/a11y/assistive-mml.ts
ts/handlers/html/HTMLDocument.ts
ts/output/common/OutputJax.ts
ts/ui/menu/Menu.ts
ts/ui/menu/MenuHandler.ts

This PR implements an assistive-mml extension that corresponds to the version 2 AssistiveMML extension.  It is implemented as an a11y extension similar to how `semantic-enrich` and the other ones operate (via extensions to the MathDocument and MathItem classes to add methods for creating the hidden MathML).  Because the extension needed to be able to generate CSS styles to hide the MathML, this required extending the HTMLDocument class to allow extensions to add CSS to the document.
This also adds a menu item to to the accessibility menu to control whether assistive MathML is inserted into the page or not (default is yes), so that those who don't need it will be able to turn it off for faster rendering.
It would probably be a good idea to move the output/common/CssStyles.ts file to …

Add AssistiveMML support to v3

---

ts/util/lengths.ts

This PR makes `pt` and `pc` relative to the em size (as they were in v2).
Resolves issue mathjax/MathJax#2285

Make pt relative to em size (as it was in v2).  mathjax/MathJax#2285

---

ts/core/MmlTree/MmlNodes/maligngroup.ts

Fix problem with spacing inside `maligngroup` elements due to `MmlMaligngroup` being a subclass of the wrong abstract class.
Resolves issue mathjax/MathJax#2295.

Fix problem with spacing inside maligngroup elements.  mathjax/MathJax#2295

---

ts/input/tex/base/BaseMappings.ts
ts/output/common/Wrappers/mo.ts

Fix problem with `\to` being remapped to `\vec` when it is used alone in super- or subscripts.
Resolves issue mathjax/MathJax#2293.

Don't remap \to to \vec when used alone as a subscript. mathjax/MathJax#2293

---

ts/output/chtml.ts

This PR sets `line-height: 0` on the CHTML `mjx-container` to remove unwanted spacing following the math output so that the spacing matches v2 spacing.
Resolves issue mathjax/MathJax#2296

Fix linespacing below CHTML displayed equations.  mathjax/MathJax#2296

---

ts/core/MathDocument.ts

This PR makes sure that the MathItem created in the `convert()` command has a location in the document (by setting it to the document's body element) so that if unknown characters need to be measured, that doesn't lead to an error (see the original issue linked below).
Resolved issue mathjax/MathJax#2309

Make convert() handle unknown characters.   mathjax/MathJax#2309

---

ts/a11y/explorer.ts

Suppress Braille output by default, as some Windows screen readers try to pronounce the Unicode characters if no Braille display is attached.

Changes the default for Braille output to false.

---

components/src/dependencies.js
components/src/source.js

Convert `source.js` and `dependencies.js` to ESM modules.  This is a little cleaner, and still works with web pack, but also should allow it to work with rollup (see #420).
Resolves (part of) issue #420.

Make source.js and dependencies.js into ESM modules.  #420

---

ts/input/tex/config_macros/ConfigMacrosConfiguration.ts
ts/util/Options.ts

This PR fixes the `util/Options.ts`  `insert()` and `copy()` functions  to handle `Expandable` objects properly.  Without this patch, expandable option objects are inserted into the destination object directly rather than copied.  That can lead to changes being made in the source object (since part of it has been inserted into the destination object).  An example of this is the `configMacros` TeX package, where the `options: {macros: expandable({})}` in the definition of the configuration would cause the `macros` expandable object to be inserted into the default options for the TeX input jax, and in turn, into the options for the TeX jax instance itself.  Then when the user-supplied macros are inserted into the TeX instance options, they also are inserted into the `configMacros` …

Fix problem with options being improperly retained.  mathjax/MathJax-src#2301

---

ts/output/svg/Wrappers/mo.ts

This PR fixes a problem with the SVG output that is exhibited in the Chrome browser for the example
\overleftrightarrow{abc}
which produces errors in the console about a negative width, and displays the dash that is supposed to form the extender between the two arrows in the wrong location.
Resolves issue mathjax/MathJax#2300

Don't include extenders in SVG output if they have negative width. mathjax/MathJax#2300

---

ts/a11y/semantic-enrich.ts
ts/a11y/sre.ts

This PR fixes the problem with `semantic-enrich` not serializing the SRE output properly in IE11.
Resolves issue #386.

Allow enrichment to occur in IE11.  #386

---

components/src/dependencies.js
ts/a11y/sre.ts
ts/components/global.ts

This resolves the issue in IE where you get a stack overflow when starting up the explorer (or other tools that rely on SRE).  The issue was that the Promise polyfill would cause `combineConfig()` to loop infinitely (it apparently has a recursive reference in it).
This also lengthens the timeout from 10 to 20 seconds, since IE is slow enough to sometimes need it.

Fix problem with infinite loop with SRE component in IE.

---

components/src/node-main/node-main.js

Fix setting of the loader's root path so that it will work in both the `mathjax` and `mathjax-full` node packages, and if you check out the `MathJax-src` respository, from the `es5` or `components/src/node-main` directories.
The current version only works for the `mathjax` npm package.
Resolves issue #406.

Set loader's mathjax path to work in more situations.  #406

---

ts/a11y/assistive-mml.ts
ts/a11y/complexity.ts
ts/a11y/explorer.ts
ts/a11y/semantic-enrich.ts
ts/core/MathItem.ts
ts/ui/menu/MenuHandler.ts

This PR adds an `isEscaped` property to `MathItem` that tells if it is an escaped character (e.g., produced by `\$` in the TeX input jax), and uses that to prevent processing of escaped content via the a11y extensions and the menu extension.  The `assistive-mml` extension was causing errors by processing the escaped content.
Resolves issue mathjax/MathJax#2327.

Don't process escaped characters in a11y and menu extensions. mathjax/MathJax#2327.

---

ts/input/mathml.ts

Force reparse if either `start` or `end` nodes are empty (accommodates `convert()` calls, where `start` is defined but not `end`).
Resolves issue mathjax/MathJax#2330.

Fix problem with convert() call with MathML input. mathjax/MathJax#2330

---

ts/input/tex/ParseUtil.ts

This PR fixes a problem with the `align` environment where `\mathrel{...}` would not produce the proper spacing following `&`.  This mirrors the corresponding fix in v2.
Resolves issue mathjax/MathJax#2175.

Use proper spacing for \mathrel in align environment.  (mathjax/MathJax#2175)

---

ts/input/tex/base/BaseMappings.ts
ts/input/tex/base/BaseMethods.ts

This is the companion PR to the v2 one at mathjax/MathJax#2343.   It allows `\newline` to be used like `\\` except not allowing the bracket form (`\\[dimen]`).
Resolves issue mathjax/MathJax#2141 for v3.

Allow \newline to work like \\.  (mathjax/MathJax#2141)

---

ts/input/tex/ams/AmsMethods.ts

This PR prevents Mathjax from inserting another `\text{}` into an operator name that already has `\text{}` in it. It is not perfect, in that this does allow `-` and `*` to be rendered as mathematics in cases where LaTeX doesn't (e.g., `\operatorname{\text{a}-\text{b}}`), but is probably good enough for MathJax.
Resolves issue mathjax/MathJax#2222 for v3.
Corresponds to PR mathjax/MathJax#2350 for v2.

Don't add \text to operators whose names already include it. (mathjax/MathJax#2222)

---

ts/output/chtml/Wrappers/mglyph.ts
ts/output/common/Wrappers/mglyph.ts
ts/output/svg/Wrappers/mglyph.ts

This PR fixes the attribute name from the incorrect `voffset` to the correct `valign`, and makes sure that the direction of shift is correct (it was reversed).  It also fixes the shifting in the case of SVG, which incorrectly used `vertical-align` instead of `transform`.
Resolves issue mathjax/MathJax#2360.

Fix mglyph attribute from offset to align.  (mathjax/MathJax#2360)

---

tsconfig.json

This PR resolves a problem where `../node_modules/@types` could be read while compiling MathJax.  
Resolves issue mathjax/MathJax#2358.

Prevent reading node_modules/@types from containing directories.  (mathjax/MathJax#2358)

---

ts/input/tex/ams/AmsMethods.ts

The `mu` units were not being translated to `em`, and so were being left verbatim in the attributes of the internal MathML.  These would then be used verbatim in the assistive MathML, causing errors in the console.
Resolves issue mathjax/MathJax#2357.

Use em rather than mu units for extensible arrows.  (mathjax/MathJax#2357)

---

ts/output/chtml/Wrappers/mroot.ts
ts/output/chtml/Wrappers/msqrt.ts
ts/output/common/Wrappers/mroot.ts
ts/output/common/Wrappers/msqrt.ts
ts/output/svg/Wrappers/mroot.ts
ts/output/svg/Wrappers/msqrt.ts

The height of the root was not taking the correct depth into account (it used the depth of the surd character, but that is being shifted vertically, so doesn't correspond to the actual baseline).  This required passing some more information to the functions that compute the information used in the bounding boxes, which accounts for most of the changes here.
Without this patch, `\sqrt[n]{\Rule{.5em}{.75em}{0em}}` will have its root too low, while `\sqrt[n]{\Rule{.5em}{0em}{1em}}` will be too high.
Resolves issue mathjax/MathJax#2347.

Fix incorrect positioning of root in mroot.  (mathjax/MathJax#2347)

---

ts/output/chtml/Wrappers/mo.ts

MathJax CHTML output uses a scaling transform to stretch the extenders in multi-character stretchy delimiters.  Chrome (and Firefox) don't align these with unstretched ending characters as well as they should.  Adding a scale transform (with an insignificant scaling factor) improves the results in these browsers.  The factor must be other than 1 in Chrome to make a difference.
Resolves issue mathjax/MathJax#2311.

Improve multi-glyph stretchy characters in Chrome.  (mathjax/MathJax#2311)

---

ts/output/chtml/fonts/tex.ts
ts/output/common/FontData.ts
ts/output/common/OutputJax.ts
ts/output/svg.ts

This PR fixes a placement issue for CHTML output when undefined characters are used.  (Unfortunately, it is an old branch that I forgot to make a PR for back in October, and I don't remember the exact situation that caused the problem.)

Add ability to include MJXZERO to font-family used for undefined characters

---

ts/output/chtml/Wrappers/msubsup.ts
ts/output/common/Wrappers/msubsup.ts
ts/output/common/Wrappers/scriptbase.ts
ts/output/svg/Wrappers/msubsup.ts
ts/output/svg/Wrappers/scriptbase.ts

This PR fixes a number of script placement issues with `munderover` and `msubsup` when the base is scaled via `<mstyle mathsize="...">`.
Resolves issue mathjax/MathJax#2317.

Fix issues with munderover/msubsup when base is scaled  (mathjax/MathJax#2317)

---

ts/input/tex/require/RequireConfiguration.ts
ts/ui/menu/Menu.ts

This PR uses `components/global.js` to get the `window.MathJax` variable (in the menu code, and the `require` TeX extension) so that in case `window.MathJax` gets renamed (e.g., if you are using both v2 and v3 together), the original object will be used in these cases.
One still can't use the dynamic loading (since `window.MathJax._` is key to that process), but it should work if you have everything loaded up front before changing the variable name.

Use components/global.js to get window.MathJax 

---

ts/output/chtml/Wrappers/mfrac.ts
ts/output/common/Wrappers/mfrac.ts
ts/output/svg/Wrappers/mfrac.ts

This provides the default size when converting the `linethickness` to ems so that unitless lengths will be multiples of the default.
Resolves issue mathjax/MathJax#2381.

Make unitless linethickness be a multiple of the default size.  (mathjax/MathJax#2381)

---

ts/core/MmlTree/MmlNodes/mfrac.ts

This PR fixes an issue with fractions where some MathML rules were used (when the fraction forms an embellished operator).  
Resolves issue mathjax/MathJax#2391.

Fix spacing around some fractions.  (mathjax/MathJax#2391)

---

ts/output/common/Wrappers/mtable.ts

This PR fixes an "off by one" error when determining the row number from the bottom of the array (i.e., when negative row numbers are used).
Resolve issue mathjax/MathJax#2394.

Fix row alignment for negative row numbers.  (mathjax/MathJax#2394)

---

ts/output/svg.ts

This PR fixes the problem where SVG output doesn't take the `scale` configuration option into account.
Resolves issue mathjax/MathJax#2376.

Make SVG honor the scale configuration option.  (mathjax/MathJax#2376)

---

ts/output/chtml/Wrappers/math.ts
ts/output/chtml/Wrappers/mtable.ts
ts/output/common/OutputJax.ts
ts/output/common/Wrappers/mtable.ts
ts/output/svg.ts
ts/output/svg/Wrappers/math.ts
ts/output/svg/Wrappers/mtable.ts

This PR makes displayed equations with labels interact better with floating content, and improves treatment of `indentAlign` and `indentShift` and their affects on the minimum width for the expressions.  This means they don't cause the expressions to clear the floating content unless necessary.
It also refactors some of the functions that were getting a bit long so that they are several smaller functions.
Resolves Issue mathjax/MathJax#2351

Improve handling of displayed equations next to floating content. (mathjax/MathJax#2351)

---

ts/components/global.ts
ts/components/startup.ts
ts/core/MathDocument.ts
ts/handlers/html/HTMLDocument.ts
ts/output/common/OutputJax.ts

This PR fixes an error that occurs when the `startup` configuration block includes an `elements` array (intended to restrict the typesetting to a collection of containers).  WIthout this patch, MathJax throws an error.  (The problem was that `combineConfig()` tried to merge a `null` value into the array, thinking it was an object, since `typeof null === 'object'`).
It also turns out that the `elements` array was never used, even if specifying it didn't cause an error, so this also fixes that problem.
Finally, it simplifies the `findMath` render action, which was rather unpleasant to begin with.
Resolves issue mathjax/MathJax#2371.

Fix error with setting startup.elements in configuration.  (mathjax/MathJax#2371)

---

ts/core/MmlTree/MmlNodes/mo.ts
ts/output/common/Wrapper.ts
ts/output/common/Wrappers/mo.ts

Fix `MmlMo.coreParent()` to produce the documented element, and fix accent mapping to only remap when the (possibly embellished) `mo` is the only element in the accent position.
Resolves issue mathjax/MathJax#2380.

Fix problem with \rightarrow being converted to \vec in some cases.  (mathjax/MathJax#2380)

---

ts/ui/menu/Menu.ts

Fix name of menu to disable when components aren't being used, now that Explorer menu has been condensed.
Resolves issue mathjax/MathJax-demos-node#10.

Correct menu name being disabled.  (mathjax/MathJax-demos-node#10)

---

ts/output/common/Wrappers/scriptbase.ts

Get `texprimestyle` from the property list, not the attribute list.  Also, fix the handling of D' style (display prime), which should also be cramped.
Resolves issue mathjax/MathJax#2395.

Fix positions of superscripts in "cramped" style.  (mathjax/MathJax#2395)

---

ts/input/tex/AllPackages.ts
ts/input/tex/tag_format/TagFormatConfiguration.ts

This PR adds `tagFormat` to the AllPackages file, and updates the preloaded list to include it (and and `color_v2`, which was loaded but missing from the list.  Also, it adds `bussproofs` to the package list.
Resolves issue mathjax/MathJax#2328.

Add tagFormat to AllPackes, and update the preloaded list.  (mathjax/MathJax#2328)

---

ts/ui/menu/Menu.ts

SRE now only offers two styles for ChromeVox speech rules:
* `default` (here called Standard) which used to be `short`, and was always the default setting.
* `alternative` that gives alternative readings to some characters and rules. As before.

Adapts Menu entry to new reduced number of ChromeVox styles in SRE.

---

ts/output/chtml/Wrappers/mo.ts

The extenders were not being placed in the proper position because the display value had been checked to block, so set it explicitly to inline-block.
Resolves issue mathjax/MathJax#2400.

Fix problem with horizontal stretchy extenders.  (mathjax/MathJax#2400).

---

ts/output/common/Wrapper.ts
ts/output/svg/Wrapper.ts

This is the redo for #477, which had conflicts due to the indenting changes in the `pretty-code` merge.  This makes for a clear merge.
Since it was already reviewed in #477, I am merging with no additional review.

Fix \overbrace in SVG output. (mathjax/MathJax#2402)

---

ts/output/chtml.ts
ts/output/common/FontData.ts
ts/output/common/OutputJax.ts

Removes CHTML overrides that cause MJXZERO to be added repeatedly to the font family of unknown characters, and creates a service routine in FontData to ad the prefix, if any.  (This is why the comma was part of the prefix originally, because the SVG output doesn't have one, and we don't want the extra comma in that case.)

Fix CHTML handling of MJXZERO font prefix

---

ts/input/tex/base/BaseMappings.ts

This PR fixes the `mathvariant` for the `\partial` symbols so that it will go to bold properly.
Resolve issue mathjax/MathJax#2417.

Make \boldsymbol\partial work properly.  (mathjax/MathJax#2417)

---

ts/adaptors/HTMLAdaptor.ts
ts/core/DOMAdaptor.ts

This uses manipulations of `className` in place of `classList` when elements don't have a class list (e.g., IE11 SVG elements).  It also fixes an incorrect return type for `hasClass()` in the interface, and no longer (incorrectly) returns a value for `removeClass()`.
Resolves issue mathjax/MathJax#2411.

Handle classList when elements don't have it. (mathjax/MathJax#2411)

---

ts/a11y/speech-rule-engine.d.ts
ts/a11y/sre-node.ts
ts/util/asyncLoad/node.ts
ts/util/asyncLoad/path.d.ts

This changes two node-specific files (`a11y/sre-node.ts` and `util/asyncLoad/node.js`) that had been using `require()` to using `import` instead (to avoid typescript/tslint warnings).  In order to make that work, this also adds minimal `.d.ts` files to clear the parts that we need.

Change require() to import to avoid typescript/tslint warnings

---

ts/core/MmlTree/MmlNodes/mo.ts
ts/core/MmlTree/MmlNodes/mrow.ts

Fix issues with texClass reported by Volker.
* When an `<mo>` has `lspace` or `rspace` set, the class was changed to `NONE`, but that is not necessary (as long as `setTeXclass()` returns `null`).
* When `\left...\right` follows an operator, the `<mrow>` is being changed to `OPEN` rather than being `INNER`.  This was due to a capitalization problem.

Fix problems with texClass

---

ts/input/tex.ts

This PR makes the tex input jax's `formatError()` function configurable, in line with the `compileError()` and `typesetError()` functions already in place for the `MathDocument` object.  This allows easy trapping of TeX run-time errors (like missing braces) without having to subclass the TeX input jax itself.
It would be nice to be able to pass the `MathItem` that is being processed at the time of the error, but that is not available.  We could save it in the TeX instance so that it can be retrieved in the `formatError()` function.

Make formatError a configuration option for tex input jax

---

ts/adaptors/HTMLAdaptor.ts
ts/adaptors/liteAdaptor.ts
ts/core/DOMAdaptor.ts
ts/output/common/OutputJax.ts
ts/output/common/Wrappers/mtext.ts

This PR fixes the long-standing issues with `mtextInheritFont` (and the little-known `merrorInheritFont`) option.  To do so, we need to look up the font of the surrounding text, and so so during the process of getting the metrics of the surrounding font.  That requires an additional function for the DOMadaptor (`fontFamily()`).
Because looking up the font requires computing the styles for the container, which is expensive, new `mtextFont` and `merrorFont` options are also provided to specify an explicit font to use for `mtext` and `merror` elements, avoiding the need to look these up (this will need to be documented).  Originally, `merrorInheritFont` was set to `true`, but because of the added expense of looking up the font, this has been changed to `false`, and the `merrorFont` is set to …

Fix problems with mtextInheritFont, and provide new mtextFont option (mathjax/MathJax#2189)

---

ts/input/tex/NodeFactory.ts

This PR adds a `data-mjx-error` attribute (like the one for compile/typeset errors and like the `no errors` extension) that contains the error message.  This makes the error message consistently available via the `data-mjx-error` attribute of the `merror` element, for easier error processing later.  (E.g., the contextual menu could use this to report the error.)

Add TeX error as data-mjx-error, similar to compile/typeset errors

---

ts/core/MathItem.ts

This PR removes the `bbox` property from the `MathItem` class.  Its was never implemented, and since CHTML doesn't always compute it (for improved performance), implementing it would be a performance hit for CHTML output.  Also, there is `OutputJax.getBBox(MathItem, MathDocument)` that can be used to obtain the BBox in cases where it is needed.

Remove MathItem bbox property

---

ts/components/loader.ts
ts/components/startup.ts

This PR adjusts how the `MathJax.startup.promise` is handled so that it is now possible to use it for synchronization outside of the `startup.ready()` function.
Originally, the startup promise was created as a promise for when the page is loaded, and then modified in the `ready()` function to be a promise that resolves when the initial typesetting was complete.  But people wanted to use it for that without waiting for the `ready()` function (and it wasn't well documented).
This PR allows for that latter behavior.  That requires an additional promise (for the page loading), leaving `startup.promise()` for when the typesetting is complete.  We need to retain the functions needed for resolving and rejecting `startup.promise` so that they can be called in the `pageReady()` function when the …

Improve startup.promise so it is always valid.  (mathjax/MathJax#2307)

---

ts/core/MmlTree/MmlNodes/mo.ts

When porting of `mo.adjustTeXClass()` to v3, I messed up these lines.  I used the wrong property, (it is capitalized in the two other places it is used), so the if-then was never satisfied.  But even if it had been, I set the wrong object's TeX class.  This fixes both issues and makes the results consistent with v2.

Fix processing of texClass for multi-character <mi> elements.

---

ts/input/tex/SymbolMap.ts
ts/input/tex/autoload/AutoloadConfiguration.ts

This PR adds a `remove()` method to `AbstractParseMap` so that a symbol can be removed, if needed.  The autoload function needs that in order to remove the macros that cause the extensions to be loaded once they have caused one to load.   The extension had used a subclass to do it, but it really should be in the base class.

Add a remove() method to AbstractParseMaps, and remove subclass from autoload.

---

ts/input/tex/noundefined/NoUndefinedConfiguration.ts

This PR adds the ability to configure the `noundefined` extension's colors and size.  This brings it in line with the v2 version of the extension.

Add configuration options to noundefined extension

---

ts/core/MmlTree/MmlNode.ts

This PR allows `scriptminsize` and `scriptsizemultiplier` to be inherited to any element, since these values are used in computing the scaling factor for any element.  Currently, these attributes have no effect because they are not being inherited properly.

Properly inherit scriptminsize and scriptsizemultiplier

---

ts/core/MmlTree/MmlNodes/mo.ts
ts/core/MmlTree/SerializedMmlVisitor.ts
ts/input/tex/NodeUtil.ts
ts/input/tex/TexParser.ts
ts/input/tex/ams/AmsMethods.ts
ts/input/tex/physics/PhysicsMethods.ts
ts/output/chtml/Wrappers/mo.ts
ts/output/common/Wrappers/mo.ts
ts/output/common/Wrappers/scriptbase.ts
ts/util/Entities.ts
ts/util/string.ts

This PR updates the string-handling functions to take advantage of some ES6 string functions (`fromCodePoint()`, `codePointAt()`, and the fact that `Array.from()` splits a string into an array of unicode characters).  It also enhances the TeX parser string handling to handle unicode characters better.  E.g., you can use a (single) unicode character as a macro name (e.g., `\α`) or as an argument (e.g. `\sqrt α`) or in macro definition templates (e.g., `\def\x #1α{[#1]}` so that `\x abcα` will produce `[abc]`), and so on.

Update string handling to handle SMP unicode blocks better.

---

ts/output/chtml.ts
ts/output/svg.ts

This PR prevents the stylesheet from being replaced when it doesn't have to be, namely in the SVG output jax (since it doesn't change) and in CHTML when `adaptiveCSS` is false.
Resolves issue mathjax/MathJax#2454.

Don't replace stylesheet unnecessarily. (mathjax/MathJax#2454)

---

ts/core/MathDocument.ts
ts/input/tex.ts
ts/input/tex/noerrors/NoErrorsConfiguration.ts
ts/output/svg/Wrappers/merror.ts

This PR improves the formatting of 'Math output error' messages (to make them display like other errors, and to allow the contextual menu to be used, and to not cause errors with assistive-mml).  The message is also stored in the `inputData`/`outputData` object for easier retrieval, if needed.
It also adds tooltips to the input and output errors to give the message for the error that occurred, and adds a similar tooltip to the `noerrors` output so that it is easier to get the TeX error that caused the problem.  The SVG output jax's `merror` wrapper is modified to move the message to a `<title>` element where it will be displayed by the browser as a tool tip.
For `noerrors` output, it would be nice to be able to save the message in the MathItem's `inputData` object, but since the TeX input …

General improvements to input/output errors

---

ts/adaptors/HTMLAdaptor.ts
ts/adaptors/liteAdaptor.ts
ts/components/startup.ts
ts/core/DOMAdaptor.ts
ts/core/MathDocument.ts
ts/util/LinkedList.ts

This PR adds API calls to allow managing of math items with container elements in the DOM.  For example, if you are updating a portion of the DOM (by setting its `innerHTML` for example) and typeset math is removed, you want to be able to remove the associated MathItems from the list of MathItems held in the MathDocument.  Previously there was no API for that.
There two new main calls added to the base MathDocument class:  `clearMathItemsWithin()` and `getMathItemsWithin()`.  Both take a container element; the first removes the MathItems from the MathList that are found within the container, and the second returns an array of MathItems found within the container.
There is also a new LinkedList method, `remove()` for removing an item from the list.
Finally, there is a new DOMAdaptor method …

Add functions to manage math items within a given container. (#351)

---

ts/input/tex/ParseOptions.ts
ts/input/tex/autoload/AutoloadConfiguration.ts
ts/input/tex/color/ColorConfiguration.ts
ts/input/tex/color/ColorMethods.ts
ts/input/tex/color/ColorUtil.ts
ts/input/tex/require/RequireConfiguration.ts

This PR provides a storage area for TeX extensions to keep information that is local to the TeX input jax instance in which they are operating.  The `color` extension uses that to handle information about defined colors, and the `require` and `autoload` extensions use it to track the extensions that are loaded and configured.
In the past, this data was stored in the configurations `options` object, as the only available location, but that muddles the meaning of the `options` object, which was the default options with the user-supplied options merged in.  This PR separates out the data storage from the option specifications.

Allow TeX extensions to store data that is local to the TeX input jax.

---

components/src/source.js
components/src/ui/safe/build.json
components/src/ui/safe/safe.js
components/src/ui/safe/webpack.config.js
ts/core/MmlTree/MmlNode.ts
ts/input/mathml/MathMLCompile.ts
ts/output/common/Wrapper.ts
ts/ui/safe/SafeHandler.ts
ts/ui/safe/SafeMethods.ts
ts/ui/safe/safe.ts

This PR ports the Safe extension from v2 to v3.  It hooks into the MathML input jax via the `filterAttribute()`method that was set up for that, and via a new `filterClassList()` for handling the class attribute.  Some adjustments were made to make handling the filters a bit easier.
It hooks into the TeX input jax as a post filter.  In v2, it hooked into the TeX parser itself so that it only filtered user-supplied values, but that is hard to maintain, as it must be aware of all the extensions and when user input is allowed.  The post-filter avoids that, at the expense of having to look at all the attributes of all the elements, so it is less efficient, but more reliable.
This PR includes a component for the safe extension, so it can be loaded from the CDN.  it also corrects an error in …

Add Safe extension and component

---

ts/input/mathml/MathMLCompile.ts

This PR fixes a problem where the `verify` options for the MathML input jax could not be specified in the `mml` block of the MathJax configuration object.  The solution is simpler than the original, which is nice.  (I found this will updating documentation for v3.1.)

Allow MathML verification options to be specified in the input jax.

---

ts/input/tex/base/BaseMethods.ts

This PR forces `movablelimits` to be false on an `<mo>` that is the base of an `\underset` command.  You can't determine the default value from the operator table because the inheritance hasn't occurred yet, so force the value on any `<mo>` explicitly.
Resolves issue mathjax/MathJax#2460.

Make \underset explicitly turn off movablelimits.  (mathjax/MathJax#2460)

---

components/src/dependencies.js
components/src/node-main/node-main.js
components/src/source.js

This PR fixes the issue with the lab where the enrichment wasn't loading properly, while still allowing `node-main` to load it.

Fix sre source location to work in lab as well as node-main and components

---

ts/a11y/assistive-mml.ts

This PR resolves a problem with the assistive MathML.  If there are IDs in the MathML (e.g., from `\tag` or `\cssId` macros, or explicit tags in MathML input), those IDs will appear in the CHTML or SVG output, but also in the hidden MathML from the assitive-mml extension.  Here, we subclass the `SerilaizeMmlVisitor` to remove them in the hidden MathML.
See [this post](https://groups.google.com/forum/?fromgroups#!topic/mathjax-users/uRmJsN-LYX0) for the original complaint.

Remove ids from assistive MathML to avoid duplicates

---

ts/adaptors/HTMLAdaptor.ts
ts/adaptors/lite/Document.ts
ts/adaptors/lite/Parser.ts
ts/adaptors/liteAdaptor.ts
ts/core/DOMAdaptor.ts

I ran into this while updating the node demos.  It turns out that comments were not being output properly from the LiteDOM.  I also wanted to be able to preserve the `DOCTYPE` comment so that the full-page node commands can retain it in their output.  So this PR fixes the comment problem, and adds the `DOCTYPE` support.

Fix LiteDOM comments and add support for DOCTYPE

---

ts/a11y/explorer.ts
ts/a11y/sre_browser.d.ts

There is some unwelcome interaction with SRE's cache when changing rule sets on the fly. The cache is aimed to avoid recomputing speech values for elements that have already been recursively traversed. But for the time being it is best to disable it completely in MathJax.
The cache was originally a solution to bring computation time down before speech rules were indexed in a trie. As is it only results in minimal run-time improvement. I either have to make it smarter on the SRE side or deprecate it.

Disables SRE cache on all explorers to avoid interaction.

---

ts/input/tex/ParseUtil.ts
ts/input/tex/textmacros/TextParser.ts

Initial and trailing spaces were not being preserved by the new `textmacros` extension, so that `\text{ and }` would produce the equivalent of `\text{and}`.  This PR fixes the problem by calling the `ParseUtil.initialText()` macro, which does the quoting of those spaces.
Resolves issue #531.

Fix problem with initial/trailing spaces in textmacros extension.  (#531)

---

components/src/node-main/node-main.js

It turns out that the implementation of node's `path` module that is included by webpack doesn't know about Windows backslashes as directory separators, so the `node-main` module fails to set the MathJax root directory properly when the `mathjax` package is used under Windows.
This PR handles that situation, and simplifies the lookup a bit, also making sure that the root is properly set no matter where the `node-main.js` file was teen from.  In the past, the `es5` directory in `mathjax-full` or `mathjax` would be taken in preference to the directory where `node-main` came from, so the wrong MathJax tree could be used.  This PR makes sure that the files used for MathJax come from the same location as `node-main.js`.
Resolves issue mathjax/MathJax#2486.

Fix processing of root directory for components to work under Windows (mathjax/MathJax#2486)

---

ts/output/chtml/Wrappers/maction.ts
ts/output/svg/Wrappers/maction.ts

If an `maction` element is created by using the MathDocument's `convert()` function (as is done for `tex2chtml()`, etc.), which converts a string to DOM elements, rather than `render()`, which converts math in place in the document, then MathJax doesn't know where in the document the element may be placed, and sets its start node to the document body (so that it can use the body to do font measuring for characters that aren't in the MathJax fonts, for example), and leaves the end node `null`, indicating that the element isn't attached to the document yet.
The action item looks for this, but should check the end node instead of the start node (the start node being set to the body was changed after the `maction` code was written).
This PR fixes the CommonHTML and SVG output to look at the …

Fix problem with maction when the math is converted from a string.  (mathjax/MathJax#2490)

---

ts/input/tex/ams/AmsMappings.ts

This PR fixes the `\ncong` macro to map to U+2247 instead of (the incorrect) U+2246.  Version 3 fixes the incorrect font mapping from version 2, but we didn't change the macro to correspond to that.
Resolves the first issue from mathjax/MathJax#2497.

Fix mapping of \ncong (mathjax/MathJax#2497)

---

ts/output/chtml/Wrappers/TextNode.ts
ts/output/common/Wrappers/TextNode.ts
ts/output/svg/Wrappers/TextNode.ts

The PR fixes a problem where a stretchy delimiter that turns out to be rendered as a single character might be remapped to another character inadvertently.  Stretchy characters should not be remapped, which is handled here by moving the test for the stretchy character to outside the remapping.
Resolves the second part of mathjax/MathJax#2497.

Don't remap stretchy characters (mathjax/MathJax#2497)

---

components/src/node-main/node-main.js

This PR improves the mechanism for getting the root directory for the version of `node-main` that is running.  It uses `eval()` to get access to the actual node version of the `path` library and the `__dirname` variable rather than the webpack versions of them, which was what was causing problems before.  This means we don't have to do all the hacks to handle Windows or use the error object to look up the path; we can use use `eval('__dirname')` and `path` as we would expect to.  This works since `node-main.js` is only for use in node, not sin the browser itself, where those values don't exist.

Better handling of root location and async loading in node-main

---

ts/core/MathDocument.ts

Update `convert()` to accept `family` parameter, and use it for the inherited font, when requested.  This fixes an error message produced when you pass the result of `getMetricsFor()` as the options for `MathJax.tex2svg()` and related functions.
Resolves issue mathjax/MathJax#2512.

Update convert() to accept 'family' parameter (mathjax/MathJax#2512)

---

ts/input/tex/autoload/AutoloadConfiguration.ts

This PR fixes a problem with the `autoload` extension when the auto-loaded macro or `\begin` is followed by spaces.
Resolves issue mathjax/MathJax#2511.

Fix autoload to handle macro or \begin followed by spaces.  (mathjax/MathJax#2511)

---

ts/input/tex/amscd/AmsCdMethods.ts

This PR changes two uses of `mu` units for their corresponding `em` units, so that `mu` units don't end up in the internal MathML.

Convert mu to em in CD environment.  (mathjax/MathJax#2513)

---

components/src/input/asciimath/asciimath.js
ts/input/asciimath.ts
ts/input/asciimath/mathjax2/input/AsciiMath.js
ts/input/asciimath/mathjax2/legacy/jax/element/MmlNode.js

This PR fixes two issues with AsciiMath:
1.  The AsciiMath component configuration was not properly handled (it was being processed too late, after AsciiMath had already been configured, and the AsciiMath parameters were being flagged as having no default value (they are only defined in the legacy code, not the new Typescript code).
2.  The conversion from the legacy internal format was not properly handling boolean values, which caused the `displaystyle` configuration option to be always treated as false.
Resolves issue mathjax/MathJax#2520.

Handle AsciiMath configuration properly, in particular, displaystyle.  (mathjax/MathJax#2520)

---

components/src/input/tex-full/tex-full.js

This PR makes sure the configuration blocks for the renamed TeX extensions are renamed in the components ending in `-full` (the individual components did the renaming, but in the `-full` files, the components aren't loaded, the original source code is).
Resolve issue mathjax/MathJax#2516.

Make sure configuration renaming is performed for *-full components. (mathjax/MathJax#2516)

---

ts/input/tex/textmacros/TextParser.ts

This PR fixes a problem where inferred mrows were being improperly included in the contexts of `text{}` when mathematics is also within the text.  This issue affected SVG output primarily.  The fix is to convert the inferred mrow into a real mrow.
Resolves issue mathjax/MathJax#2524.

 Fix issue with textmacros in SVG mode. (mathjax/MathJax#2524)

---

ts/input/tex/TexParser.ts

In `textmacros`, the spacing counts, so we need to follow LaTeX rules poperly:  only skip a space after an alphabetic control sequence, not ones that are a single special character.
Resolves issue mathjax/MathJax#2527.

Only ignore space following alphabetic control sequences.  (mathjax/MathJax#2527)

---

ts/input/tex/textmacros/TextMacrosMethods.ts
ts/input/tex/textmacros/TextParser.ts

This PR adds missing support for `\ref` and `\eqref` in the `textmacros` extension.  The macros were mapped, but the method for them was missing, and the `TextParser` needed to use the `tags` object from the original `TexParser` in order to be able access the correct tagging data.
Resolves issue mathjax/MathJax#2528.

Add missing support for \ref and \eqref in textmacros.  (mathjax/MathJax#2528)

---

ts/input/tex/textmacros/TextMacrosMappings.ts

This PR adds two macros to `textmacros`: `\’` and `\‘` that mirror the `\'` and `` \` `` macros, but with "smart quote" characters (U+2019 and U+2018) rather than the usual ascii characters.  The is because some content-management systems do automatic substitution of smart quotes, and would convert `\'` to `\’`, perhaps without the user's knowledge.
Resolves issue mathjax/MathJax#2526.

Add 'smart quote' version of acute and grave accents. (mathjax/MathJax#2526)

---

ts/a11y/explorer/KeyExplorer.ts

Problem: 
When only one `KeyExplorer` attaches itself, one of the others might remove the `role="application"` attribute.
Solution:
`KeyExplorer` only alters attributes during detachment when they are active.

 Remove role application on detach only if active.

---

components/bin/pack
components/webpack.common.js

The webpack configuration didn't handle Windows path separators properly, which caused the building of components to fail on windows.  This PR resolves the issues by using `path.sep` and fixing `quoteRE()` to properly quote the special characters like `\`.
Resolves issue mathjax/MathJax-demos-web#30.

Fix webpack.common.js to handle windows paths correctly (mathjax/MathJax-demos-web#30)

---

ts/core/MmlTree/MmlNodes/mspace.ts

Currently, `mspace` elements have `TEXCLASS.ORD`, but this causes spacing issues in some instances, for example `A=\!=B`.  This PR sets the `texClass` to `TEXCLASS.NONE` and overrides `setTeXclass()` so that the spacing will be based on the elements surrounding the space, as it is in actual TeX.
Resolves issue mathjax/MathJax#2576.

Make mspace elements have TEXCLASS.NONE (mathjax/MathJax#2576)

---

ts/input/tex/autoload/AutoloadConfiguration.ts

If an autoloading macro is followed by a space, the space is lost when the macro name is reprocessed, and so the macro can become incorrect if it is followed by other tex.  For example, `\ce C` ends up as `\ceC` after the autoload.  This PR replaces the missing space (that was removed during the initial parsing for the macro name, and will be removed again when it is re-parsed).
Resolves issue mathjax/MathJax#2580.

Fix autoloading when macro name is followed by a space.  (mathjax/MathJax#2580)

---

ts/output/chtml/FontData.ts
ts/output/chtml/Wrappers/mo.ts

It turns out that the zero height boxes used for the characters in the stretchy horizontal extenders in CHTML are not placed properly in Safari (but are in Firefox and Chrome).  If the height is non-zero, they they are, so this PR forces a non-zero height.
Resolves issue mathjax/MathJax#2598.

Make sure strechy character extenders have non-zero height in CHTML for Safari (mathjax/MathJax#2598)

---

ts/output/svg.ts

SVG elements are not displayed if their height (or width) is 0.  We already had a test for 0 width, but not for zero height.  So `\smash{X}` would no display properly.  This PR resolves that issue.

Don't let height of final SVG be 0 (mathjax/MathJax#2605)

---

components/bin/makeAll

Not sure why this was changed, but I used the full list to check that everything is packing from the proper locations.  If that is a problem, perhaps we need to make a command-line option to control it.

Show all modules during packing

---

ts/output/common/Wrappers/mfrac.ts

This PR makes sure the `/` used for bevelled fractions is centered on the math axis.  This didn't matter with the MathJax TeX fonts, whose glyphs are centered already, but for STIX2, the slash isn't centered, so this makes a difference.

Make sure bevelled fraction is symmertically placed (needed for STIX2 fonts)

---

ts/input/mathml/MathMLCompile.ts

This PR resolves an issue reported by Peter where enrichment causes spacing differences with parentheses following a function, e.g. `f(x)` gets treated like `f\left(x\right)` after enrichment.  This is due to the extra `<mrow>` that is put around the `(x)`, which in turn is treated by the MathML input jax as a fenced group, which gets `texClass` of `INNER`, and so gets extra space.
This PR changes the heuristic for marking fenced groups so that they are marked only if the fences are actually stretchy (e.g., could have come from `\left...\right`), and not otherwise.  That should preserve the spacing from TeX output that gets enhanced.  It might still alter MathML output unless it is marked carefully, but that was the case in the past as well, since putting the `<mrow>` around the …

Don't mark mrows as fences if the parens aren't stretchy

---

ts/input/tex/textmacros/TextMacrosConfiguration.ts

This PR corrects the problem mentioned in mathjax/MathJax#2622:  that any undefined macros used in text mode when textmacros is in effect will end up being placed before the text material, regardless of where the undefined macro appears.

Use the correct parser for noundefined (mathjax/MathJax#2622)

---

ts/input/tex/textmacros/TextParser.ts

This PR prevents an unwanted inferredMrow from being used for the content of text-mode material that produces more than one element.  This prevents overlaps in the rendering in SVG.
Resolves issue mathjax/MathJax#2577.

Use mrow rather than inferredMrow if text mode produces more than one. (mathjax/MathJax#2577)

---

ts/input/tex/textmacros/TextMacrosConfiguration.ts

This PR exports the `textmacros` configuration (as per @pkra's request).
Resolves issue mathjax/MathJax#2623.

Add exported configuration constant (mathjax/MathJax#2623)

---

ts/core/MmlTree/MmlNodes/mspace.ts

This PR fixes the mspace internal node to work with Tyepscript v4.  This would have been part of #560, except the addition of the `texclass` was created before that, but merged after that, so it was not part of that PR.
This should allow `mspace` to compile properly now.

Update texClass to texclass for tsc v4.

---

ts/a11y/explorer/KeyExplorer.ts
ts/a11y/sre_browser.d.ts

Pass the shift key to the table walker as modifier. This allows table walking similar to v2.

Fixes table walking by setting modifier key.

---

ts/core/MmlTree/MmlNodes/mrow.ts

This PR removes the check that there either be no previous element or that it be marked as `fnOP` in order for an `mrow` to be marked as `TEXCLASS.INNER`.  That was incorrectly preventing `\left...\right` constructs from being treated as the correct class.
With this PR, `f\left(x\right)` will be spaced as it is in actual TeX (with a bit of extra space between the `f` and the open parenthesis).  It also means that 
``` xml
<math>
<mi>f</mi>
<mrow>
<mo>(</mo>
<mi>x</mi>
<mo>)</mo>
</mrow>
</math>
```
will also be spaced the same way.  Some may object to that.  There are several ways to prevent it.  One would be to set the `mathMLSpacing` property to `true` on the output jax.  Alternatively, you can modify the input to be
``` xml
<math>
<mi>f</mi>
<mrow data-mjx-texclass="ORD">
<mo>(</mo> …
```

Fix handling of mrows that look like \left...\right to be texClass INNER.  (mathjax/Mathjax#2584)

---

ts/adaptors/liteAdaptor.ts

This PR improves the LiteAdaptor's handling of full-width characters.  There is now a separate width used for CJK characters from normal characters, and these are now customizable via options to the adaptor itself.

Update LiteAdaptor to handle full-width characters better. (mathjax/MathJax-demos-node#29)

---

ts/output/chtml/FontData.ts
ts/output/common/FontData.ts
ts/output/svg/fonts/tex.ts

This PR provides a new output jax parameter that specifies the font family to use for unknown characters (it defaults to `serif` as int eh past, but makes it easier to change the default to `monospace` when the LiteAdaptor is used.
This required moving support for `FontData` options from `chtml/FontData.ts` into `common/FontData.ts`, and making sure all the constructors passed the options on properly.

Add support for setting the unknown character family for output jax

---

ts/output/svg/Wrapper.ts

This PR resolves the issue with hit-boxes for the SVG output when an element in the middle of an `mrow` has an `href` attribute.  The hotbox was not placed properly, so this patch causes the box to be translated properly.
(I had fixed this some time ago, but apparently didn't push the branch or make the PR).
Resolves issue mathjax/MathJax#2530.

Make sure hitbox is translated along with the hit-able element. (mathjax/MathJax#2530)

---

components/bin/makeAll
components/bin/pack

OK, I see now why you changed the `--display-modules` option, since it has been removed in web pack v5.  This PR adjusts the `pack` and `makeAll` commands to display the modules again using information from `webpack --json` (which was the only way I could find to get the information reliably).  Because the data is so large, I had to change from `execSync` to `spawn` and use promises to handle the IO.

Fix pack and makeAll to display the modules

---

components/bin/build
components/bin/makeAll
components/bin/pack
components/webpack.common.js

This PR adjusts the component building tools to make it easier to create custom components (like tex extensions) outside of the `MathJax-src/components` directory.  The main changes are in the `webpack.common.js` file, and allow for better control over the libraries that are linked.  It also now supports imports like
```
import {MathItem} from 'mathjax-full/js/core/MathItem';
```
where `mathjax-full` will be found in `node_modules`, and the `.js` is omitted.  (Our v3-lab doesn't handle that, but node and webpack do, so it is useful to allow it.)
Most of the other changes are to make the output easier to read (more directory prefix collapsing, and separate indicators for MathJax's components and js code as compared to local components and local js code).

Improve build tools to make it earlier create custom components

---

ts/core/MmlTree/MmlNodes/mroot.ts

This PR implements the `setTeXclass()` method for `mroot` elements, which was missing (argh!).
Resolves issue mathjax/MathJax#2630.

Add setTeXclass support for mroot elements.  (mathjax/MathJax#2630)

---

ts/core/MmlTree/MmlNodes/TeXAtom.ts

This PR adjusts the TeXAtom node to save the node's TeX class in the property list so that it will be included in the `data-mjx-texclass` attribute when serialized MathML is generated, even if the TeX class is just the default `ORD` class.  This allows the serialized MathML to preserve the TeXAtom even when the property was not set explicitly.
For example, `f{\left(x\right)}` currently produces
``` xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
<mi>f</mi>
<mrow>
<mrow data-mjx-texclass="INNER">
<mo data-mjx-texclass="OPEN">(</mo>
<mi>x</mi>
<mo data-mjx-texclass="CLOSE">)</mo>
</mrow>
</mrow>
</math>
```
and since the outer `<mrow>` does not include a TeX class, the spacing is that of `INNER` when this MathML is read into MathJax (but the spacing is `ORD` when the TeX input is …

Update TeXAtom to save the texClass in the property list, so it appears in MathML output.  (mathjax/MathJax#2585)

---

ts/core/MmlTree/MmlNodes/mtable.ts
ts/core/MmlTree/SerializedMmlVisitor.ts
ts/input/mathml/MathMLCompile.ts
ts/input/tex/base/BaseItems.ts
ts/output/chtml/Wrappers/mtable.ts
ts/output/chtml/Wrappers/mtd.ts
ts/output/common/Wrappers/mrow.ts
ts/output/common/Wrappers/mtable.ts

This PR implements the proper table layout for the `smallmatrix` and `subarray` environments.  These use the `useHeight` property that is supposed to to change how the matrix is laid out (by not adding extra height and depth to make sure rows are full height, as usual).  That feature was not implemented, so this PR adds support for `useHeight`.
These environments are typeset in script style, which had been handled by adding an `mstyle` around the table with `scriptlevel="1"`, but this had the side-effect of making the math axis be the script-size math axis (too low).  So the script level is now set through an internal property instead (which causes the table to scale down its children).  That required handling the relative size change of children in the bounding box computations.
The …

Updates to handle smallmatrix properly

---

ts/adaptors/jsdomAdaptor.ts

This PR allows the jsdom adaptor to handle undefined characters and `mtextFontInherit` better (in the same way that the liteDOM does).  It also adds options for the jsdom adaptor so that you can specify the widths and heights to use for the unknown characters.
Resolves issue mathjax/MathJax#2550.

Handle measuring of elements as in liteDOM, since jsdom doesn't do measurements.  (mathjax/MathJax#2550)

---

ts/core/MmlTree/OperatorDictionary.ts
ts/input/tex/base/BaseMappings.ts

Semantic enrichment together with certain TeX input can cause `\|` to be stretchy when it shouldn't.  For example, `\|X^X\|_x,` can cause the problem.  This is due to the fact that `\|` produces U+2225, which normally is not stretchy, but should be when used as delimiters with `\left` and `\right`.  In order to accommodate that, the operator dictionary added U+2225 in prefix and postfix positions with `stretchy="true"`, making the stretchy attribute different in infix from the other positions.
Because the TeX input jax removes attributes that are the defaults for the given nodes, the expression `\|X^X\|_x,` has `\|_x` in infix position (as an embellished operator), and so the U+2225 has `stretchy="false"` and `fence="false"` as defaults, and so these attributes that had been added …

Fix problem with \| being stretchy when it shouldn't be.  (mathjax/MathJax#2632)

---

ts/core/MmlTree/MmlNode.ts
ts/input/tex/NodeFactory.ts
ts/input/tex/ParseUtil.ts
ts/input/tex/textmacros/TextParser.ts

Inferred mrows are used to hold multiple MathML nodes in situations where a single node is expected (e.g., they act as MathML fragments).  For example, the TexParser's `ParseArg()` function can return an inferred mrow.  These should not appear as children of normal MathML elements, and so historically the code had to be careful to check the return value of such functions in order to handle inferred mrows as a special case.  While this was done in many places, some situations still slipped through.  An unexpected inferred mrow did not affect CHTML output, but it does cause problems for SVG output, with mathjax/MathJax#2554, mathjax/MathJax#2624, and mathjax/MathJax#2577 being examples.
Rather than try to patch each new occurrence as it appears, this PR resolves it at the lowest lever:  the …

Handle appending of inferred rows in MmlNode.appendChild() (mathjax/MathJax#2554)

---

ts/input/tex/ams/AmsMappings.ts
ts/input/tex/ams/AmsMethods.ts
ts/output/chtml/Wrappers/mo.ts

This PR improves the positioning of the content above and below stretchy arrows generated by xArrows to make it match TeX positioning better.  It also adjusts the bounding box to accommodate the `voffset` amounts (in the past, elements could fall outside the bounding box).
This also fixes a regression with short stretchy arrows in CHTML caused by #571 (the extensible piece ends up with a minimum size of the size of the extension character, so would not "overlap" the end piece to make short extensions).  For example, without this fix, `\xrightarrow{xx}` would be too long in CHTML (on the develop branch).  This puts back the pre-571 handling of the size of the extension.

Improve xarrow spacing, and fix CHTML output for short extensible arrows.

---

ts/core/MmlTree/MmlNodes/mi.ts
ts/core/MmlTree/MmlNodes/mo.ts
ts/input/mathml/MathMLCompile.ts

This PR improves the assignment of TeX class OP to multi-character `mi` elements, and to elements followed by invisible apply.  This improves spacing of enriched content where invisible apply has been inserted after a single-character identifier (e.g., `fR(s)`).
It also refactors the MathML input to not need the `texAtom()` method, and to remove `xmlns` attributes that appear on serialized MathML from SRE.

Handle automatic tex class of OP better.

---

ts/output/chtml/Wrappers/mo.ts
ts/output/common/FontData.ts
ts/output/common/Wrappers/mo.ts
ts/output/common/fonts/tex.ts
ts/output/svg.ts
ts/output/svg/Wrappers/mo.ts
ts/util/Styles.ts

This PR includes changes needed to support the STIX2 fonts.  (It is cherry-picked from the first commit on the `stix2` branch, but is needed for other changes that will be made in a separate PR.  The `stix2` branch can be rebased off this branch, if needed, when we make the PR for stix2.)
Most of the changes here are to allow specifying the variant to use for stretchy characters, so there are a lot of places where a variant needs to be passed into a function that was not the case before.  There is also some refactoring of some duplicate code into `getCenterOffset()`, and simplification of of scaling transforms (e.g., `matrix(1 0 0 0 -1 0)` is replaced by `scale(1,-1)` which does the same thing more transparently).

Updates needed to support STIX2 fonts

---

ts/output/chtml/Wrappers/mmultiscripts.ts
ts/output/chtml/Wrappers/msubsup.ts
ts/output/chtml/Wrappers/munderover.ts
ts/output/chtml/Wrappers/scriptbase.ts
ts/output/common/Wrappers/mmultiscripts.ts
ts/output/common/Wrappers/msubsup.ts
ts/output/common/Wrappers/munderover.ts
ts/output/common/Wrappers/scriptbase.ts
ts/output/svg/Wrappers/mmultiscripts.ts
ts/output/svg/Wrappers/msubsup.ts
ts/output/svg/Wrappers/munderover.ts
ts/output/svg/Wrappers/scriptbase.ts

This PR refactors the handling of the base core element for munderover and msubsup elements so that super- and subscripts can be placed properly after SRE enrichment.  It also lays the groundwork for better TeX emulation for accents and over- and underlines (which will be in separate PRs).  
The base core element, along its italic correction and relative scaling factor, are now found during the `constructor()` rather than calling them (multiple times) when needed.  The base core is used for vertical positioning of super- and subscripts, but the actual base for width and bounding box computations.  The handling of the base core BBox and script BBoxes have been moved to the common wrappers, where possible.
For consistency, the `script` property has been change to `scriptChild`, to be …

Refactor handling of baseCore, and take enrichment into account (zorkow/speech-rule-engine#462)

---

ts/output/svg/Wrapper.ts

This PR fixes a regression due to #589 that affects the SVG output when `\not` is followed by a letter, as in `\not a`.  This generates `<mi>a&#x338;</mi>`, and the contents of the `<mi>` is actually two text items, due to how the TeX input jax adds the U+0038.  The second text item needs to be placed with a non-zero *x* value, and causes the change from #589 to attempt to access the node's `attributes` value, which doesn't exist on a text node, causing an error.  This PR prevents that.

Fix problem with SVG output crashing when \not is used with a letter

---

ts/output/chtml/FontData.ts
ts/output/chtml/Wrappers/mi.ts
ts/output/chtml/Wrappers/mo.ts
ts/output/chtml/Wrappers/msubsup.ts
ts/output/chtml/Wrappers/munderover.ts
ts/output/chtml/Wrappers/scriptbase.ts
ts/output/common/Wrappers/mi.ts
ts/output/common/Wrappers/mo.ts
ts/output/common/Wrappers/msubsup.ts
ts/output/common/Wrappers/munderover.ts
ts/output/common/Wrappers/scriptbase.ts
ts/output/svg/Wrappers/msubsup.ts
ts/output/svg/Wrappers/munderover.ts
ts/output/svg/Wrappers/scriptbase.ts

This PR refactors some fo the previous accent code to better handle the italic correction differences in the bases of some constructs (`msub`, `msubsup`, and math-accent `munderover` nodes).  The previous code included some hacks that were competing with each other, and caused complications in handling the interactions between `munderover` and `msubsup` nodes.  This refactors some of the code to make that work more reliably, and moves more to the common wrappers so that the specific output routines are more uniform.
In the past, the italic correction was removed from the base character when it was output, and had to be added back in later, which made for complicated checking of whether the italic correction needs to be taken into account and when it needs to be added again.  The new …

Fix handling of italic correction for munderover and msubsup combinations.

---

ts/core/MmlTree/SerializedMmlVisitor.ts
ts/input/mathml/MathMLCompile.ts
ts/input/tex/NodeUtil.ts
ts/input/tex/base/BaseMethods.ts
ts/output/chtml/Wrappers/mo.ts
ts/output/common/FontData.ts
ts/output/common/Wrappers/mo.ts
ts/output/common/Wrappers/munderover.ts
ts/output/common/Wrappers/scriptbase.ts
ts/output/svg/Wrappers/mo.ts

This PR combines what was the `tex-accents` and `stretchy-accents` into one, based on the `sre-fences` branch.
It adjusts the algorithm used to stretch accents like those used in `\widehat` to better match the one used by TeX. Prior to this, the accents used the horizontal stretchy character algorithm, which takes the smallest version that is larger than the needed size, but TeX's algorithm for accents uses the largest that is smaller than the width of the base.
Here, we mark math accents with a new `mathaccent` property, and when one is stretched, it uses the largest version that is smaller than the base. We use the fudge-factors (`delimitershortfall` and `delimiterfactor`) as for other stretchy characters because we don't really have the proper italic corrections, and so the sizes turn …

Handle accents more like TeX does (better sizes and placement) (mathjax/MathJax#712, mathjax/MathJax#2474)

---

ts/core/MmlTree/MmlNodes/mi.ts

This PR doesn't sound combining characters when counting the length of the content of an `mi` element in order to determine the `mathvariant` to use.  This allows things like `\not a` to render as an italic "a" rather than an upright one.
Resolves issue mathjax/MathJax#2617.

Allow 'single-character' mi's to include trailing combining characters (mathjax/MathJax#2617)

---

ts/output/chtml/Wrappers/msubsup.ts
ts/output/common/FontData.ts
ts/output/common/Wrappers/scriptbase.ts

This PR modifies the super- and subscript positions to leave a small amount of space between the base and the scripts.  In TeX, this is handled by italic correction values (that are different for each character), but we don't have that information in the font tables.  We may be able to add that during the font update this summer, so this is a bit of a hack to improve the layout until then.  It's not perfect, but it helps.  See, for example `\beta^p` before and after:
Before:  <img width="58" alt="before" src="https://user-images.githubusercontent.com/432782/111667669-55b63180-87eb-11eb-9827-e57be81002f9.png">
After: <img width="54" alt="after" src="https://user-images.githubusercontent.com/432782/111667969-9c0b9080-87eb-11eb-9f18-a63cc08f4a5d.png">
I also moved the comments that …

Add a small separation between base and scripts.  (mathjax/MathJax#2406)

---

ts/input/tex/base/BaseMethods.ts

This PR causes the `\\` command to ignore a following asterisk, if there is one.  (The asterisk is for controlling page breaks, but it makes sense for MathJax to just ignore it.)
Resolves issue mathjax/MathJax#2433.

Ignore * in \\* and \\*[...] constructions.  (mathjax/MathJax#2433)

---

ts/input/asciimath/mathjax2/legacy/jax/input/AsciiMath/jax.js

This PR brings the legacy AsciiMath input jax up to the version currently in MathJax v2 (adding missing commands, etc.).

Update AsciiMath to current v2 version. (mathjax/MathJax#2640)

---

ts/output/svg/Wrapper.ts
ts/output/svg/Wrappers/TextNode.ts

This PR uses more specific CSS selectors for the SVG glyphs paths, and makes sure they apply to both `path` and `use` elements.
Resolves issue mathjax/MathJax#2618.

Better selectors for SVG path widths.  (mathjax/MathJax#2618)

---

ts/a11y/assistive-mml.ts

This PR removes the unneeded `role="presentation"` attributes that are inserted by the assistive MathML extension.  Since these were being applied to custom element that had no role to begin with, there is no need for these.
Resolves issue mathjax/MathJax#2608.

Remove role='presentation' attributes.  (mathjax/MathJax#2608)

---

ts/ui/menu/Menu.ts

This PR trims TeX code and annotations before copying to the clipboard.
Resolves issue mathjax/MathJax#2574.

Trim TeX and annotations before copying to clipboard.  (mathjax/MathJax#2574)

---

ts/ui/menu/Menu.ts

Updates menu entry to reflect renaming of ChromeVox rule set in SRE (>= v3.2.0-beta.1).

A11y menu update

---

ts/ui/menu/Menu.ts

This PR forces TeX to reset the tags when an A11Y menu item causes the page to re-render.
It may be good to abstract this so that the MathDocument has a `reset` method that can just be called, and that would call resets on the input jax (and output jax?), which would be empty for ones with no reset, but would do the TeX reset for the TeX input.
It may also be appropriate to save the expression labels and ids for each expression so that if it is re-rendered, it clear those labels and ids, and start auto-numbering at the right place.  That would allow proper rerendering without making assumptions about where the numbering starts on the page, or what labels need to be cleared.
Resolves issue mathjax/MathJax#2597

Reset the tex labels and ids when A11y changes force rerendering.  (mathjax/MathJax#2597)

---

ts/input/tex/Tags.ts

This PR resolves an issue where the tagging information was not fully cleared when an equation begins.  This caused a problem if there were TagInfo objects on the stack when an extension is autoloaded (causing the equation to be rerendered).  The extra TagInfo would end up setting the initial `currentTag` item when the *next* equation is processed.  See the example at mathjax/MathJax#2643.

Fully clear tagging on equation start.  (mathjax/MathJax#2643)

---

ts/output/chtml/Wrappers/mtable.ts
ts/output/common/Wrappers/mtable.ts
ts/output/svg/Wrappers/mtr.ts

This PR fixes the `smallmatrix` environment by properly handling the scaled mrows so that the widths and separations are correct.  The problem was particularly apparent in SVG output, but also affected the separations in CHTML output.  In addition the colored backgrounds for cells and rows in SVG matrices were not always properly sized, and this fixes that as well.

Handle scaled table rows (for smallmatrix) properly in CHTML and SVG

---

ts/output/common/FontData.ts
ts/output/common/Wrappers/mo.ts
ts/output/common/fonts/tex.ts
ts/output/common/fonts/tex/delimiters.ts

This PR fixes the stretchy data for several characters where it was incorrectly translated from the v2 data.  In particular, this fixes the data for `\widehat` and `\widetilde`, as well as U+00AF (MACRON) and U+003D (EQUAL SIGN).
See also the comment below for additional changes that were added in a second commit.

This PR corrects errors in the horizontal stretchy data for several characters.

---

ts/input/tex/boldsymbol/BoldsymbolConfiguration.ts

This PR adds data so that `\boldsymbol` will interact properly with `\mathit`.  So `\boldsymbol{\mathit{1}}` should produce `<mi mathvariant="bold-italic">1</mi>`.  Note, however, that the MathJax TeX fonts only include bold-italic alphabetic characters, so this will still not show a bold-italic 1.  That would require a font with more bold-italic coverage, such as STIX2.
Resolves issue mathjax/MathJax#2502

Add bolding data for the -tex-mathit variant (mathjax/MathJax#2502)

---

ts/handlers/html/HTMLDocument.ts
ts/output/chtml.ts
ts/output/svg.ts

This PR allows the `MathJax.svgStyleSheet()` or `MathJax.chtmlStyleSheet()` functions to return the stylesheet properly even after it has been created already, while still preventing the stylesheet from being updated unnecessarily.
Resolves issue mathjax/MathJax#2542.

Allow stylesheet to be obtained even after it was created.  (mathjax/MathJax#2542)

---

ts/output/common/FontData.ts
ts/output/common/Wrappers/mo.ts
ts/output/common/fonts/tex/delimiters.ts

This PR adds the ability to make stretchy multi-character assemblies only use the full size of the extenders.  In TeX, this is used by stretchy surds, for example, to make them grow at a standard rate.  E.g., 
``` latex
\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{\sqrt{1-x^2}}}}}}}}}}
```
now produces
with this PR (which is consistent with LaTeX), but used to produce
without it (which is not consistent with LaTeX).
Resolves issue mathjax/MathJax#2658.

Improve heights of successively larger multi-character surds. (mathjax/MathJax#2658)

---

ts/output/svg/Wrappers/mglyph.ts

Replaces invalid alt and title with aria-label attribute.
Re-resolves mathjax/MathJax#2065 (which was fixed the same way in 2.x)

svg mglyph: set valid alttext

---

ts/core/MmlTree/OperatorDictionary.ts

This updates the operator dictionary to include some new characters that were not in Appendix C back when the data was created for v2.  There is also a correction to U+2032 (which looks like a deletion and addition since there are other characters added around it), and one character removed (not sure why they did that).
Not much to check, here, really.

Update operator dictionary to the current state of Appendix C of the spec

---

components/src/input/mml/mml.js
ts/components/loader.ts
ts/components/package.ts

This PR adds a function list to use for resolving the path to a component file (i.e., package), and populates it with several default filters (the ones that were in the original `resolvePath()` method).  This allows extensions to add or remove the filters as needed, and is used by the MathML input component to handle loading entity files when needed.
In the past, the Entities object would try to load entity definitions when an entity wasn't found in its default table.  That works for node applications, but for in-browser use, which requires components, not just files, that caused MathJax to fail.  (Fortunately, the browser usually handles the entities, but it could cause problems with entities not known in the browser, and in some other edge cases).
This PR resolves that problem by adding …

Make path resolving more flexible, and don't fail when loading entity files. (mathjax/MathJax#2650)

---

ts/input/tex/configmacros/ConfigMacrosConfiguration.ts

This PR adds the ability to pre-define environments (just like macros) to the configmacros extension.  It adds a new configuration option `environments` like the `macros` one for the `tex` block.  
Resolves issue mathjax/MathJax#2505.

Add ability to pre-define environments like for macros.  (mathjax/MathJax#2505)

---

ts/core/MmlTree/MmlNodes/TeXAtom.ts
ts/core/MmlTree/MmlNodes/mo.ts
ts/core/MmlTree/MmlNodes/mstyle.ts
ts/core/MmlTree/SerializedMmlVisitor.ts

This PR allows the `MmlMo` object to mark itself as having a math-accent so that MathML input will display the same as TeX input for these accents, without the need for the `data-mjx-accent="true"` attribute.  That attribute is no longer applied in serialized MathML output, but you can still use it on MathML input to control this internal setting (either to prevent an accent from getting it, or to force one that isn't usually marked that way).
This also fixes a problem with the `TeXAtom` and `mstyle` element's `notParent()` methods to have them not be parents only if they contain a single element (otherwise, they ARE the parent, effectively as an `mrow`).  Without this, something like `\lim_{n\to\infty}` would incorrectly mark the arrow as a mathaccent, as the group `n\to\infty` is in a …

Allow MathML to mark mathaccents, so output is the same as TeX input.

---

ts/input/tex/ParseUtil.ts
ts/input/tex/base/BaseMethods.ts
ts/util/Entities.ts

This PR adds the few entities needed by the TeX input jax into the main entity table so that we don't have to load the auxiliary tables for just one or two entities.  Also, replace the undefined `rquote` entity with `rsquo`.

Add the entities needed by TeX into the main entities table.

---

ts/core/MmlTree/MmlNodes/mo.ts
ts/output/common/Wrapper.ts

This PR modifies the MathML spacing rules for `<mo>` (and embellished `<mo>`) to correspond to Neil's explanation of the rules in mathjax/MathJax#2392.  This means that space is only added when the (embellished) operator is inside an mrow (or inferred mrow) that has more than one element.  This also makes the spacing between two successive `<mo>` elements be the maximum of the `rspace` of the first and the `lspace` of the second (as opposed to the sum of the two, as in the past). 
This only affects when MathML spacing has been selected for the output jax, not the TeX spacing.
Finally, this also fixes the `coreParent()` function, which used to skip over `<mstyle>` elements, and so would incorrectly report the parent for `<mstyle><mo>+</mo></mstyle>` as the `<mo>` element rather than the …

Fix MathML spacing rules for mo elements.  (mathjax/MathJax#2392)

---

ts/output/svg.ts

This PR attempts (again) to fix the problem with SVG element disappearing if they have 0 height or width.  This uses CSS `min-height` and `min-width` to make sure the SVG has some width and height, and also makes sure the `viewBox` has non-zero width and height (this time using the em-size to make it what should be one pixel minimum.

Better handling of min height and width for SVG (so they don't disappear).

---

ts/adaptors/HTMLAdaptor.ts
ts/handlers/html/HTMLDomStrings.ts

This PR arranges for the HTMLDomStrings object to skip node types that it doesn't recognize (it can handle text, comments, and Elements).  This fixes the problem reported in mathjax/MathJax#2662 where ProcessingInstructions would cause MathJax to crash.
Resolves issue mathjax/MathJax#2662.

Have HTMLDomStrings skip node types that it can't process. (mathjax/MathJax#2662)

---

ts/output/chtml/Notation.ts
ts/output/chtml/Wrappers/menclose.ts
ts/output/common/Notation.ts
ts/output/common/Wrappers/menclose.ts
ts/output/svg/Notation.ts
ts/output/svg/Wrappers/menclose.ts

This PR improves the placement of horizontal and vertical strikes and arrows, and makes sure diagonal arrows fit the actual box used.  This addresses the issues in mathjax/MathJax#2571, but we don't fully follow the spec, since we do allow notations to affect each other (e.g., top by itself and top with right will be different width.
The PR also adds a couple of new types for some arrays that are used.
Resolves issue mathjax/MathJax#2571 (for now).

Fix issues with placement of menclose notations. (mathjax/MathJax#2571)

---

ts/input/tex/Tags.ts

PR #630 was too aggressive about clearing the tag environment so that environments that allow multiple tags no longer worked.  This puts back the original `clearTag()` code, but resets the tag at the beginning of the equation so that it still solves the issue from mathjax/MathJax#2643.

Fix regression in tagging caused by #630

---

ts/output/chtml/Wrappers/mtable.ts
ts/output/common/Wrapper.ts
ts/output/common/Wrappers/mtable.ts
ts/output/svg/Wrappers/mtable.ts

This PR fixes a number of issues with table output:
* Labels in CHTML could not align with their rows (mathjax/MathJax#2601).  This was due to accumulated round-off problems, which is resolved by explicitly setting the row heights regardless of whether they should already be correct or not.
* When rows have `rowalign` specified, the height and depth weren't properly computed (it was always computed as though alignment were `baseline`).
*  Cells with `rowalign` set to `top`, `bottom`, or `center` could cause the height and depth of the row to be too large (the sizes were always computed as through the alignment were `baseline`).
* The `center` alignment was incorrectly called `middle`, so didn't work properly in SVG.
* The positioning of a row label in CHTML wasn't always correct when …

Fix several issues with tables (label alignment in CHTML, lines in SVG, centering). (mathjax/Mathjax#2601)

---

ts/input/tex/Tags.ts
ts/input/tex/tagformat/TagFormatConfiguration.ts

This PR changes the tag id from `mjx-eqn-XXX` to `mjx-eqn:XXX`.  This is needed in order to get links to work in SVG in Safari.  I don't know exactly why that is needed, but it seems to need a character that requires escaping in URLs.  Go figure.
Resolves issue mathjax/MathJax#2586.

Use a colon in link anchor ids so that links work in Safari in SVG output.  (mathjax/MathJax#2586)

---

ts/input/tex/ParseUtil.ts
ts/input/tex/StackItem.ts
ts/input/tex/base/BaseConfiguration.ts
ts/input/tex/base/BaseItems.ts
ts/input/tex/base/BaseMappings.ts
ts/input/tex/base/BaseMethods.ts

The current implementation for `\middle` only works when there are no open style or color changes, and so it fails with
```
\left( \color{red} x \middle| y \right)
```
for example.  This PR introduces a `MiddleItem ` stack item that acts as a close item, so it will close any pending and style items.  The `LeftItem` looks for a `MiddleItem` and processes it (by adding the needed `mo`) without closing itself so that it will remain open until the following `RightItem` occurs.
In addition, the `\middle` and `\right` delimiters now save the color that they should be in, since `\left(\color{red}x\right)` colors the right brace red in actual LaTeX (and similarly for `\middle`), and apply those properly (they didn't before).
Finally, I made the `LeftRight` constructor take the actual delimiter …

Allow \middle to work when a style or color is open.  (mathjax/MathJax#2663)

---

ts/output/chtml/FontData.ts
ts/output/chtml/Wrappers/mo.ts

This PR adjusts the CSS used for multi-glyph horizontal and vertical stretchy delimiters to make the pieces match up better.  It does this by making sure all the pieces are given the same height and depth (for horizontal) and width (for vertical).  The horizontal ones were the worst offenders, particularly for arrows, and this seems to resolve the problems, even when zoomed in or out.  I have tested in Firefox, Chrome, and Safari.
Resolves issue mathjax/MathJax#2547 and mathjax/MathJax#2642.

Improve positioning of extenders for stretchy characters.  (mathjax/MathJax#2547)

---

ts/ui/menu/MenuHandler.ts

This PR adds the a11y "enable" options to the menu handler so that a page author can include them in the MathJax configuration even if the extensions aren't loaded yet.  Without this, having `enableExporer`, for example, in the configuration would lead to an error about the option not being defined.  This defines them when the menu component is loaded, since it may load the a11y extensions later.
Resolves issue mathjax/MathJax#2651.

Add a11y enable options to menu handler so that they can be configured (mathjax/MathJax#2651)

---

ts/core/MmlTree/MmlNodes/mo.ts

This PR makes sure the parent element is not null before querying it.
This also fixes a second problem, where the base of an `mover` could be marked as a math accent.

Fix mathaccent regression reported by Peter

---

ts/adaptors/HTMLAdaptor.ts
ts/adaptors/browserAdaptor.ts
ts/adaptors/lite/Parser.ts
ts/adaptors/liteAdaptor.ts
ts/core/DOMAdaptor.ts
ts/core/MmlTree/MmlNode.ts

This PR adds a `serializeXML()` method for the DOMadaptor, and implements it in the HTML and Lite adaptors.  This is then used by the `XMLNode` class to get its serialized version for output in serialized MathML.  This allows `<annotation-xml>` element that contain HTML content with self-closing tags like `<input>` that don't usually produce valid XML to produce a serialized version that can be parsed by SRE as well as by MathJax.  This allows `<annotation-xml>` to be used with the assistive tools.

Add ability to serialize annotation-xml content.

---

ts/a11y/explorer/KeyExplorer.ts
ts/a11y/sre_browser.d.ts

This solves the issue when a key walker looses focus due to mouse interference. E.g., if a subtree is collapsed at the root while the key explorer is focused on one of the nodes in the subtree.

A11y refocus on mouse collapse

---

ts/output/chtml/Wrappers/mtable.ts

This PR fixes a problem reported in WeBWorK (which is moving to v3).  The math was inside a larger table that had `border-spacing: 10px; border-collapse: separate`, and the arrays generated by MathJax within that outer table inherited those properties, making the spacing wrong for the math.   So I've added some CSS to the `mjx-mtable` element to reset these values.

Prevent border-spacing and border-collapse from being inherited from an outer table

---

ts/a11y/explorer/KeyExplorer.ts
ts/a11y/sre_browser.d.ts

Hitting return on the node that announces itself to be a link will trigger the link.
Unfortunately, this only works for CHTML, not in SVG.
I've tried by setting focus on the anchor element and continue propagating the event. 
Unfortunately, that only works sporadically. 
Also dispatching a new event like below did not do the trick.
``` javascript
let event = new KeyboardEvent('keydown', {code: '13', bubbles: true});
node.parentElement.dispatchEvent(event);
```

Triggering links from the explorer.

---

package-lock.json
package.json
ts/input/tex/mhchem/MhchemConfiguration.ts
ts/input/tex/mhchem/mhchemparser/mhchemParser.d.ts
ts/input/tex/mhchem/mhchemparser/mhchemParser.ts
tsconfig.json

This PR resolves the problem with using the` mhchemparser` npm package (which is compiled to ES6) within node modules that call MathJax modules directly.  It includes the `mhchemparser` source files in the MathJax-sc/ts tree (as Martin originally asked), and compiles them along with the rest of MathJax.
The real solution is to have MathJax down-compile to ES5 rather than ES6.
Resolves issue mathjax/MathJax#2673.

Move mhchem files to ts/input/tex/mhchem and down-compile to ES5 (mathjax/MathJax#2673)

---

ts/adaptors/lite/Parser.ts

This PR fixes a problem with HTML serialization (as opposed to XML serialization) where empty non-self-closing tags would not be properly closed.
Resolves issue mathjax/MathJax#2674.

Fix problem with not closing empty tags in HTML serialization (mathjax/MathJax#2674)

---

ts/adaptors/jsdomAdaptor.ts
ts/output/common/OutputJax.ts

This PR fixes a regression in 3.1.3 that causes liteDOM and jsdom adapters to get the ex-height badly wrong.  This was due to changes made to process CJK characters that also added some default height, which confused the test to see if the `exFactor` needed to be used.
There are also some problems with jsdom's implementation of `getComputesStyle()`, which doesn't actually inherit styles, it only lists the ones explicitly on the given element.  The CSSStyleDeclaration implementation is broken in a number of ways, and I've had to patch it before, but this issue would take some work.  This PR adds options to the jsdom to set the font size and family to use (just as we do with the LiteDOM), since `getComputedStyle()` can't be trusted.
Resolves issue mathjax/MathJax#2694.

Fix problem with detecting whether ex-height can be computed, and work around jsdom problems

---

ts/adaptors/HTMLAdaptor.ts
ts/adaptors/lite/Document.ts

This PR fixes a problem where `adaptor.doctype()` could fail if the original document doesn't have a `<!DOCTYPE>` comment (in HTML and jsdom adaptors).  It also prevents the LiteDOM from returning a doctype if the original didn't have one.

Only return a DOCTYPE if there is one

---

ts/input/tex.ts
ts/input/tex/Configuration.ts
ts/input/tex/require/RequireConfiguration.ts
ts/input/tex/textmacros/TextMacrosConfiguration.ts

This PR adds a parser name to each configuration (default is `tex`) and uses an array of names to indicate which packages are allowed for the given `ParserConfiguration` instance.  This allows the `text-base` configuration to be marked as for the text parser, so it will be rejected if included in the `tex.packages` list.
Pros:  This is easy to implement, and allows mixing and matching for packages with parsers, even if the package's parser is not a superclass of the given parser.
Cons:  You need to list all the superclasses explicitly if you want them to be allowed.  So to allow configuring the `TextParser` to accept TeX packages, you must indicate `['tex', 'text']` when creating the `ParserConfiguration` for the `TextParser`.
This is one proposal for how to handle this.

Add support for restricting packages to particular named parsers (A)

---

ts/output/chtml.ts
ts/output/svg.ts

This PR makes sure the output jax clear its internal stylesheet pointer when it is used in a new document.
Resolves issue mathjax/MathJax#2678.

Clear the stylesheet when used in a new MathDocument.  (mathjax/MathJax#2678)

---

ts/output/chtml.ts
ts/output/svg.ts

Reverts mathjax/MathJax-src#693, which was incorrectly targeted to master.

Revert "Clear the stylesheet when used in a new MathDocument.  (mathjax/MathJax#2678)"

---

ts/output/common/FontData.ts
ts/output/common/Wrapper.ts
ts/output/common/Wrappers/TextNode.ts
ts/output/common/Wrappers/scriptbase.ts
ts/util/BBox.ts

This PR adds code to allow combining characters to be properly places as accents (both above and below).  It introduces a new item of font data for an offset to apply, and then passes that through the BBox to the under-over methods that determines the positioning.  Since accents are centered and combining characters have zero width (the data doesn't identify the actual size or placement of the character), we add a shift that moves the center of a combining character to the horizontal origin.
This resolves an issue Peter pointed out with combining-character accents in the STIX2 fonts.

Add support for shifting combining-character accents into place

---

components/src/node-main/webpack.config.js

This PR updates the `webpack.config.js` file for the node-main component (which is what you get when you `require('mathjax')`) to work with the latest version of webpack to which we updated in 3.1.4.  This fixes the error that occurs when you do `require('mathjax')` with the `mathjax` npm package.  (The `mathjax-full` package works fine because it uses the source version rather than the webpacked version).
Resolves issue mathjax/MathJax#2683.

Update node-main for webpack 5

---

ts/input/tex/TexParser.ts
ts/input/tex/base/BaseMethods.ts

This PR fixes some issues reported by Peter.
1. `\bigg{\uparrow }` indicates an error (the trailing space was not being removed).
2. `\mathbf{x^x}^x` produces an error (the `\mathbf{...}` should be in a TeXAtom of type ORD.
Resolves issue mathjax/MathJax#2688 and mathjax/MathJax#2689.

Trim delimiter for \big and friends, and put \math* in a TeXAtom (mathjax/MathJax#2688, mathjax/MathJax#2689)

---

ts/output/chtml.ts
ts/output/chtml/Wrappers/TextNode.ts

This PR worked around a bug with WebKit that mis-measures regular text (like error messages) and so produces the wrong bounding boxes.  For example, a TeX error message will get the yellow background size wrong.  The problem is that the MJXZERO font seems to confuse WebKit (that is also the source of the problem with parts of characters disappearing).  I'd like to fix this during the font update this summer, but for now, this is a work-around.
The fix is to remove the MJXZERO font during the measuring process, and then specify the width explicitly on the final text element.  Not great, but it works for now.
You can test in Safari by causing any TeX error (e.g., `\end` with no name, or `\begin{xyz}`).

Force width of -explicitFont text (work around Safari bug)

---

ts/output/common/Wrappers/mo.ts

A change in 3.1.4 to make stretchy delimiters that end up using a different untied point produce the correct character had a side effect of making them unstretchable after the first use.  The `\Vert` double bar is one such, and so the second (and subsequent) uses of `\Vert` will not stretch.  E.g. `\left\Vert \frac 1 2 \right\Vert` will have the right-hand delimiter un-stretched.  This PR resolves the problem.
Resolves issue mathjax/MathJax#2697.

Fix error where a second use of \| delim causes the wrong size to be used.

---

ts/input/tex.ts
ts/input/tex/Configuration.ts
ts/input/tex/require/RequireConfiguration.ts
ts/input/tex/textmacros/TextMacrosConfiguration.ts

This PR adds the ability to specify additional packages to be loaded in the textmacros text parser.  Use
``` javascript
MathJax = {
tex: {
textmacros: {
packages: {'[+]', [...]}
}
}
}
```
to specify the packages to include, e.g., `textmacros: {packages: {'[+]': ['bbox']}` to allow `\bbox` inside '\text{}`.
This also makes the main `textBase` configuration a named one rather than a local one, so that it can be included in the package list (as `text-base`, just like `base` for the main TeX base package).   That means it will show up as a package in the Lab package list, so `v3-lab.js` should probably be modified to not create a checkbox for it, since it is not appropriate outside of `\text{}`.

Add ability to specify additional textmacros packages.

---

ts/input/tex/FilterUtil.ts
ts/input/tex/ParseOptions.ts

The `ParseOptions.nodeLists` object contains lists of elements generated during TeX input processing, and these are used by the post filters in order to do things like fix up `munderover` elements and combine `mo` relations.  Sometimes this means an element is removed and another put in its place.  When this happens, the element isn't currently being removed from its list, so later filters may try top process the removed element again.  This happens with the `cleanSubSup` and `moveLimits` filters.  If an `munderover` has been cleaned, it is still processed by `moveLimits`, sometimes leading to an error when the `munderover` has an empty child.
This PR adds a `removeFromList()` method to `ParseOptions` class that allows elements to be removed from its list.  Because the `for-of` loop will …

Remove munderover elements that have been cleaned.  (mathjax/MathJax#2691)

---

ts/adaptors/HTMLAdaptor.ts
ts/adaptors/liteAdaptor.ts
ts/core/DOMAdaptor.ts
ts/output/chtml.ts
ts/output/chtml/FontData.ts
ts/output/chtml/Usage.ts
ts/output/chtml/Wrapper.ts
ts/output/chtml/Wrappers/TextNode.ts
ts/output/chtml/Wrappers/mo.ts
ts/output/chtml/Wrappers/msubsup.ts
ts/output/chtml/Wrappers/mtr.ts
ts/output/chtml/Wrappers/munderover.ts
ts/output/common/OutputJax.ts
ts/util/StyleList.ts

The lazy-typeset extension causes equations to be updated frequently, and for CHTML, that means updating the CHTML stylesheet.  It turns out that that can be expensive on large pages.  This PR improves the updating of the CSS by inserting individual rules into the stylesheet rather than replacing it outright.  That means the browser only has to update a few rules rather than think they *all* have changed.  This brings the performance of the lazy-typesetting for CHTML to nearly the same as for SVG.
This also updates the way that usage information for the CSS rules is stored.  It introduces a new Usage class for holding the data and uses that for keeping track of the wrappers and characters that need to be included in the stylesheet.  This moves that information out of the wrappers and …

Update the CHTML adaptive CSS process to insert new rules rather than replacing the stylesheet entirely.

---

ts/output/chtml.ts
ts/output/chtml/FontData.ts

This PR fixes the problem with CHTML output where the initial typeset fails to show the formulas (the CSS was missing the needed character data).

Properly produce initial CSS when stylesheet is loaded. 

---

ts/components/startup.ts
ts/util/Options.ts

This PR changes invalid-option messages from fatal to warning (so MathJax will still run when a bad option is specified).  New configuration options are added to the `startup` block to control whether the message is a warning or a fatal one, and to provide a function that is called when there is an invalid option (so that you can trap these easier, and handle them in whatever way is desired).

Provide switch for warn/error for invalid options

---

ts/components/loader.ts

This PR adds the ability to include path filters in the `loader` configuration block.  It is difficult to make changes to the loader that affect the loading, since the startup `ready()` function isn't called until after loading occurs, and there is no pre-load function, so a configuration option for the pre-filters is the most convenient way to adjust the filters.

Add ability to configure loader path filters

---

ts/core/MmlTree/MmlNodes/mo.ts

This PR removes a heuristic that was supposed to turn multi-letter function names into operators with `texClass` of `OP` rather than `ORD` when followed by U+2061, but it turns out to be too aggressive, and ends up causing spacing problems, especially after enrichment (which adds the U+2061).  There are other heuristics that produce the same result, so this one really isn't needed, and should be removed.
For example:  `\Big| \mathcal{P}_a(x) \Big|` will have too much space between the first `|` and the `P` when enriched (to have the U+2061).

Remove heuristic for U+2061 forcing previous item to be texClass=OP

---

ts/input/tex/base/BaseConfiguration.ts
ts/input/tex/base/BaseItems.ts
ts/input/tex/base/BaseMappings.ts
ts/input/tex/base/BaseMethods.ts

This PR implements the `\nonscript` command, which removes the following spacing command (like `\hskip`, `\kern`, `\hspace`, etc.).  This is used int macro definitions to handle not use spacing in scripts, when given explicitly.
This is handled by using a new StackItem for the `\nonscript` that checks what is pushed after it, and if an `mspace` (or an `mspace` inside an `mstyle`, as produced by `\,` and similar macros), then we add the space into a list to be post-filtered (once the `scriptlevel` is known).   The case of am `mstyle` containing an `mspace` is handled by wrapping it in an `mrow` so that we can test the `scriptlevel` (since the `mstyle` will have `scriptlevel="0"` set).  The `mrow` is removed in the post-filter if the space is being retained (otherwise the `mrow` together …

Add \noscript command

---

ts/output/chtml/Wrappers/TextNode.ts

This PR applies a CSS fix to the clipped character bug in Safari with CHTML.  This is a long-standing bug, and it s great to have a fix for it.  This was suggested by @mt4c in mathjax/MathJax#2435.

Work around WebKit bug with CHTML characters.  (mathjax/MathJax#2435)

---

ts/output/chtml/FontData.ts
ts/output/chtml/Wrappers/TextNode.ts
ts/output/chtml/Wrappers/mo.ts

This PR fixes several issues with how the CHTML output handles character usage information and the adaptive CSS for the ones used.
* The recent changes to how the usage data is recorded caused an error if a character that isn't in the MathJax fonts was used.  This PR prevents known characters from being recorded, and so prevents the later error when trying to set up the CSS for those characters (for which we don't have data).
You can test this by typesetting `\unicode{x3333}`.  Without this PR, MathJax will produce an error and crash.  With the PR, it should generate the usual output.
* For stretchy characters that are aliased to other characters (e.g., U+2015 is aliased to U+2013 when stretched), the CSS wasn't properly tied to the correct character, and so the stretchy character didn't …

Fix several issues with CHTML adaptive CSS.

---

package-lock.json
package.json
ts/a11y/explorer.ts
ts/a11y/explorer/KeyExplorer.ts

Upgrades SRE by
* Including `v3.3.3` (see issue [528](https://github.com/zorkow/speech-rule-engine/issues/528) for version jump!) in `package.json` and `package-lock.json` files.
* Integrates Hindi into the context menu.
* Fixes a minor issue in the explorer, where Braille could bleed into the speech after a locale change.

Updates to latest version of SRE.

---

ts/adaptors/HTMLAdaptor.ts
ts/output/chtml/Wrappers/mo.ts

This PR changes the overflow property used for the extenders in stretchy characters so that they clip only in the direction of the stretching.  This avoid accidentally clipping thin horizontal and vertical lines, for example.
It also adds the index to the `insertRule()` call in the HTMLadaptor so that it works in IE (which seems to require it), and wraps the call in `try/catch` so that rules that are only valid in modern browsers won't cause problems in IE (or other older browsers).
Resolves issue mathjax/MathJax#2701.

Use 'overflow: clip visible' for stretchy characters to avoid unwanted clipping. (mathjax/MathJax#2701)

---

ts/input/tex/ParseUtil.ts
ts/input/tex/base/BaseMethods.ts

This PR adds a `ParseUtil` method for determining if a base needs to have `movablelimits` set to false, and then uses it in `\oerset`, `\underset`, `\overundetset`, and `ParseUtil.underOver()` (used by `\overbrace` and similar macros).  This makes sure all these situations work the same (currently there are three different criteria being used).
Resolves issue mathjax/MathJax#2709.

Fix setting of movablelimits to false for \overset and similar macros.  (mathjax/MathJax#2709)

---

CONTRIBUTING.md

The "reduced test case" link in the bug reports section was pointing to a 404 error page.
This brings it back to life.

CONTRIBUTING: Fix broken CSS-Tricks link

---

ts/components/startup.ts

See https://github.com/mathjax/MathJax/issues/2774

Add defaultPageReady() to MathJaxObject interface

---

components/src/a11y/complexity/build.json
components/src/a11y/explorer/build.json
components/src/a11y/explorer/webpack.config.js
components/src/a11y/semantic-enrich/build.json
components/src/a11y/semantic-enrich/webpack.config.js
components/src/a11y/sre/webpack.config.js

The PR should resolve the problem you were having with loading the are components in the lab.
The main issue is that SRE was being included in both the semantic-enrich and explorer modules, and that caused duplication of the modules that seems to have triggered the export problem.  The reason this was happening is that the `build.json` files included `a11y/sre.ts` as targets, which is no longer necessary since the `a11y/sre` module is self-contained (it may be that it wasn't necessary before, but including the old `a11y/sre.ts` wasn't a problem since it was just a small file with no need for shared code).  So I've removed the `a11y/sre.ts` from all the targets.
The other issue was that the webpack files needs to refer to `components/a11y/sre/lib` not `node_modules/speech-rule-engine/js`. …

Update component files for changes to sre component

---

ts/input/mathml.ts
ts/input/mathml/mml3/mml3-node.ts
ts/input/mathml/mml3/mml3.ts

This PR move the MML3 filter from being a `preFilter` to being an `mmlFilter`.  That way it will always run and you don' have to specify `forceReparse: true`.  It also means that (in the browser) you don't have to serialize the math and then re-parse it, as is currently done, since the browser's XSLT parser can work on any DOM fragment.  The node version must serialize and re-parse, however.
There is a new `enableMml3` configuration option that controls whether the filter is added or not (so that if the extension is packaged with a combined configuration, it can be disabled).
This also make the `mmlFilters` public, as it should have been originally.
Resolves issue mathjax/MathJax#2718.

Move mml3 filter to an mmlFilter so that forceReparse isn't needed. (mathjax/MathJax#2718)

---

ts/input/mathml/MathMLCompile.ts

This PR makes sure that MathML input only tries to process the `MJX-TeXAtom-*` class names (from v2 output) when they appear on `mrow` elements.
Resolves issue mathjax/MathJax#2822

Only process MJX-TeXAtom classes on mrow elements.  (mathjax/MathJax#2822)

---

ts/input/tex/base/BaseMethods.ts

If the top or bottom of `\overset`, `\underset` or `\overunderset` is a single `mo` element whose operator-dictionary entry indicates it is an accent by default, then the output is incorrect (the display uses accent size and spacing, and accent substitution can be performed).  This PR resolves that buy explicitly marking `mo` elements with `accent="false"`.  This will be filtered out if that is the operator dictionary default, but will be retained otherwise.
Resolves issue mathjax/MathJax#2800

Mark mo as not accent if used in \overset and friends. (mathjax/MathJax#2800)

---

components/bin/build
components/bin/makeAll
components/bin/pack
components/webpack.common.js

This PR update the build tools (and the web pack configuration in particular) to handle the situation for building an extension (like the fonts) more easily, and to handle imports that use node modules rather than relative paths.  This allows extensions to import from `mathjax-full` (or the future `@mathjax/src`) directly, and still have it work properly with the packing tools.
It also adds a `--no-subdirs` option to `makeAll` so that it won't build extensions from subdirectories.

Update build tools to work with extensions better

---

ts/output/chtml/Wrappers/msubsup.ts

This PR fixes an issue in CommonHTML output where `msubsup` output when the subscript is empty shows the superscript in the subscript position in some instances (see the initial issue mathjax/MathJax#2765).  This was caused by CSS that was overriding the `display` property for the super- and subscript elements, when it really only needed to be for the spacer.  The order in which the CSS for the msubsup and the scripts are output also affected the results.  The fix is to limit the CSS to just the spacer.
Resolves issue mathjax/MathJax#2765.

Fix problem with msubsup when subscript is blank (#2765)

---

ts/output/svg/Wrappers/msqrt.ts

This PR fixes a problem in SVG output for `mroot` when the height of the root extends above that of the surd itself, as in
```
\sqrt[\frac{1}{2}]{1}
```
In that case, the root symbol was too high.  This PR positions it correctly.
Resolves issue mathjax/MathJax#2764.

Fix placement of surd when root extends above the horizontal line (mathjax/MathJax#2764)

---

components/src/input/tex/extensions/cases/webpack.config.js
components/src/input/tex/extensions/empheq/webpack.config.js

This PR corrects the location for the `empheq` and `cases` extensions, which were being put into the wrong place.
Resolves issue mathjax/MathJax#2762.

Update webpack files for empheq and cases (mathjax/MathJax#2762)

---

ts/output/chtml.ts
ts/output/chtml/Wrappers/TextNode.ts

In order to work around a bug in Safari, when text is taken from an unknown font (e.g., when there is a character not in the MathJax fonts, or when `mtextInheritFont` is used, or when an `style` attribute sets the font explicitly), MathJax's CHTML output sets the width of the text explicitly, and uses `px` units to avoid potential px-to-em conversion issues.  But that means the width is not affected bu font-size changes, and that leads to the bounding-box for the text to be the wrong size when used in script or script-script styles.  For example, 
\scriptstyle\sqrt{\style{font-family:Arial}{\text{Text in explicit font}}}
would get the wrong width for the line over the radicand.  This PR resolves that issue by including the relative scaling in its width computations.
Note that this PR is …

Take relative scaling into account for CHTML output of non-MathJax fonts (mathjax/MathJax#2818)

---

ts/input/tex/FilterUtil.ts
ts/input/tex/base/BaseMethods.ts

This PR modifies `\mmlToken` to make sure the attributes specified by it are not removed but the `cleanAttributes` filter, even if their values are the default values.  This was causing the spacing for `\bmod` to be lost (and so it failed to have the proper space in super and subscripts).
Resolves mathjax/MathJax#2806.

Make sure explicit attributes added by \mmlToken are not removed. (mathjax/MathJax#2806)

---

ts/input/mathml.ts

This PR trims whitespace from the ends of the serialized MathML sting before parsing it (so that we don't get unwanted text nodes on either side that cause MathJax to indicate multiple nodes were produced).
Resolves issue mathjax/MathJax#2805.

Trim MathML string before parsing it.  (mathjax/MathJax#2805)

---

ts/output/chtml/Wrappers/munderover.ts
ts/output/chtml/Wrappers/scriptbase.ts
ts/output/common/Wrappers/munderover.ts

This makes the output for `mover` and `munderover` consistent with TeX when used for accents, and brings v3 in line with v2 output.
Resolves issue mathjax/MathJax#2766.

Add a minimum height for accented characters.  (mathjax/MathJax#2766)

---

ts/ui/safe/SafeMethods.ts

The Safe extension was returning a number rather than a string when it filters the `scriptlevel` (and `scriptSizeMultipler`) attributes, and so a script level of 0 would end up reading as false rather than a string consisting of 0, and so the script level was filtered out.  This PR returns strings for these attributes.
Resolves issue mathjax/MathJax#2745.

Make safe extension properly handle scriptlevel of 0. (mathjax/MathJax#2745)

---

ts/input/tex/textmacros/TextParser.ts

This PR forces the math that is typeset within text to be of TeX class ORD when the texmacros extension is in use (making it consistent with when textmacros is *not* in use).
Resolves issue mathjax/MathJax#2828.

Make sure math-in-text forms an ORD atom with textmacros. (mathjax/MathJax#2828)

---

ts/input/tex/base/BaseMethods.ts

Fixes typos introduced in #763 that have the wrong attributes for `accentunder`.
See [this comment](https://github.com/mathjax/MathJax-src/pull/757#issuecomment-1029298636) and the following discussion.

Fix typo in accentunder in #763.

---

ts/core/MmlTree/OperatorDictionary.ts
ts/input/tex/base/BaseConfiguration.ts

This PR adds an optional variant specification for the `RANGES` array that specifies how to handle raw unicode input in the TeX input jax.  This allows the CJK letters to be upright van when placed into an `mi` with one character.
This resolves mathjax/MathJax#2744.

Add ability for TeX input to force normal variant for CJK input.  (mathjax/MathJax#2744)

---

ts/input/tex/mhchem/MhchemConfiguration.ts

This PR isolates the call to `mhchemParser` and in order to handle the different error format used by the TeX parser and the mhchem parser, as reported in mathjax/MathJax#2835.
Resolves issue mathjax/MathJax#2835.

Fix problem where errors during mhchem argument collection are not properly handled.  (mathjax/MathJax#2835)

---

ts/core/MmlTree/MmlNodes/mo.ts
ts/output/common/Wrappers/scriptbase.ts

This PR fixes a problem where super- and subscript were placed in the position for the UN-centered content, rather than the centered content.

Place super- and subscripts properly around \vcenter elements.

---

ts/adaptors/linkedomAdaptor.ts

This PR adds an adaptor for the [linkedom](https://github.com/WebReflection/linkedom) node-based DOM implementation.
Resolves issue mathjax/MathJax#2833.

Add a linkedom adaptor (mathjax/MathJax#2833)

---

ts/adaptors/NodeMixin.ts
ts/adaptors/jsdomAdaptor.ts
ts/adaptors/linkedomAdaptor.ts
ts/adaptors/liteAdaptor.ts

This PR introduces a `NodeMixin` function for adding common methods and properties to a base DOM adaptor.  These methods are the ones that implement features that aren't available in node DOMs, like `getComputedStyles()` and measuring of DOM elements.
The jsdom and linkedom adaptors are refactored to use this mix-in, as is the liteDOM, though that is a bit more complicated, as the mix-in can't be used with an abstract class, and so we need to make a base lite class to use with the mix-in to get the full adaptor.  This means that the last four methods in `LiteBase` will be overridden by the mix-in, but I don't see any way around that.

Refactor node-based DOM adaptors to use a mixing for common code

---

ts/ui/menu/Menu.ts

This PR adds some initialization to the menu code that makes sure that the initial settings of the menu take effect on a page reload.  This was not the case for the in-tab-order, assistive MML, renderer, and scale settings (argh!).
Resolves issue mathjax/MathJax#2786, and similar problems with the other settings.
@zorkow, activating the explorer seems to override the in-tab-order setting.  Is that intentional?

Fix problem where some menu settings weren't sticky  (mathjax/MathJax#2786)

---

components/src/a11y/sre/webpack.config.js
components/src/mml-chtml/mml-chtml.js
components/src/mml-svg/mml-svg.js
components/src/node-main/node-main.js
components/src/startup/init.js
components/src/startup/startup.js
components/src/tex-chtml-full/tex-chtml-full.js
components/src/tex-chtml/tex-chtml.js
components/src/tex-mml-chtml/tex-mml-chtml.js
components/src/tex-mml-svg/tex-mml-svg.js
components/src/tex-svg-full/tex-svg-full.js
components/src/tex-svg/tex-svg.js
ts/a11y/sre.ts

The addition of the paths, dependencies, etc, was being added in the `components/src/startup.js` file, which was loaded last by the combined components like `tex-chtml`.  This means that that data wasn't available to other components that are imported into the combined components (like SRE4).  This PR separates adding of paths, etc, into a startup init file, so that they can be added before other imports, making the default paths, etc, available to imported files, as they should be.  It also makes it easier to make combined configuration files by loading the init file rather than the lib/startup.js file, which wasn't very intuitive.
It also, fixed the sre webpack `libs` definition so that it shares the startup code.
Finally, I removed a closure function in `sre.js` that wasn't needed, …

Allow SRE to use resolverPath during startup

---

ts/core/MmlTree/SerializedMmlVisitor.ts
ts/input/mathml/MathMLCompile.ts
ts/input/tex/ams/AmsMappings.ts
ts/input/tex/ams/AmsMethods.ts
ts/output/chtml/Wrappers/mmultiscripts.ts
ts/output/svg/Wrappers/mmultiscripts.ts

This re-implements the `\sideset` macro to use `mmultiscripts` rather than as a replacement macro that has a phantom duplicate of the base with super- and subscripts.  In order to produce the same output as LaTeX, a new property was added to allow `mmultiscripts` to control the alignment of the pre- and post-scripts; `\sideset` has the pre-script left-aligned, but `mmultiscripts` has them right-aligned, so this property is needed to allow left-alignment to be specified.  That required changes to the CHTML and SVG output to support the new property, and to the MathML serializer to output the property to MathML, and the MathML input jax to read the property on input.  For the latter, since the number of such properties is getting larger, the old if-then-else-if construction was replaced by …

Re-implement \sideset using mmultiscripts.  (mathjax/MathJax#1217)

---

ts/input/tex/physics/PhysicsConfiguration.ts
ts/input/tex/physics/PhysicsItems.ts
ts/input/tex/physics/PhysicsMappings.ts

This PR causes nested delimiters to be handled properly (not closing the delimiters until the inner ones are also closed).  It also fixes the spacing issue around the delimiters (the physics package prevents the stretchy delimiters from getting TeX class INNER, so I've removed the properties that cause `setTeXclass()` to mark it as INNER so that it will be handled as a normal `mrow` with an OPEN at the front and a CLOSE at the end).  Also, some operators were being enclosed in `mi` rather than `mo`, producing the wrong spacing (e.g., in `\div` and `\curl`), so I've changed that as well to match the LaTeX output.  Finally, an expression that is missing its final delimiter would produce a math input error, so I've added the missing error message so that the missing close delimiter will be …

Have physics package match nested parentheses, fix spacing issues (mathjax/MathJax#2760, mathjax/MathJax#2831)

---

ts/output/chtml/FontData.ts

This PR fixes a problem introduced in v3.2.0 where setting `adaptiveCSS` to `false` would not produce the full CSS; it included all the wrapper CSS, but left out the unused character CSS.  This fixes that problem.
Resolves issue mathjax/MathJax#2724.

Make sure all character data is included when adaptiveCSS is false.  (mathjax/MathJax#2724)

---

ts/core/MmlTree/MmlNodes/mglyph.ts
ts/output/chtml/Wrappers/mglyph.ts
ts/output/common/Wrappers/mglyph.ts
ts/output/svg/Wrappers/mglyph.ts

This PR adds support for using the `fontfamily` and `index` attributes on `mglyph`, to bring it more in line with v2.  This does not do the check that the requested character is actually in the specified font, however, which was done in the HTML-CSS output jax of v2, so the `alt` attribute will not be used in this case.
The common glyph output wrapper now creates a TextNode for the character indicated by `index`, and uses that to produce the SVG or CHTML output (and to compute its bounding box).
It now reports an error if the `mglyph` doesn't have a `src` attribute and is also missing either the `fontfamily` or `index` attributes.
Resolves issue mathjax/MathJax#2298.

Add support for mglyph use of fontfamily/index.  (mathjax/MathJax#2298)

---

ts/core/MmlTree/MmlNode.ts
ts/core/MmlTree/MmlNodes/mtable.ts
ts/core/MmlTree/MmlNodes/mtr.ts
ts/core/Tree/Node.ts

This PR produces better results for repairing and reporting issues with malformed mtables.  There are verification options available that are supposed to control the error messages produced for bad MathML, and one controls whether tables should be repaired silently or produce `merror` elements to report the problem.  The `fixMtables` option did not work well, as it did not produce proper messages in some cases, and didn't always produce a repaired table.
The fixes here include:
*  Correct interface for return value of error (it was listed as `void` but returned an `error` node).
*  Make sure that errors for missing `mtr` or `mtd` elements are in a valid `mtable`, and produce the right output (a colored `mtd` when used outside an `mtr`, or a colored `mtr` when used outside a table, and a …

Fix problems with verification and repair of malformed mtables.

---

ts/input/tex/ParseMethods.ts
ts/input/tex/StackItem.ts
ts/input/tex/ams/AmsConfiguration.ts
ts/input/tex/ams/AmsMappings.ts
ts/input/tex/ams/AmsMethods.ts
ts/input/tex/base/BaseMethods.ts

This PR improves the implementation of `\operatorname` (and `\DeclareMathOperator`) to work more like in true LaTeX.  In the past, the macro replaced `-` and `*` by `\text{-}` and `\text{*}` in order to handle what LaTeX dues using `\catcode`.  Here, we take advantage of features added to `ParseMethods.variable` to get `\mathrm{}` to produce multi-character `mi` elements to get `\operatorname` to do the same.  The `multiLetterIdentifiers` environment value has been replaced by a regular expression for the characters to use (and `EnvProp` is extended to allow that).  Then we make a new map that matches `-` and `*` and checks whether we are in an `\operatorname`, and if so, parses the characters like variables, otherwise parses them as usual.
The `\operatorname` macro is rewritten to parse …

Update \operatorname to work more like in LaTeX.  (mathjax/MathJax#2830)

---

ts/input/tex/textmacros/TextMacrosMappings.ts

the `\textup` and `\textnormal` macros were left out of `textmacros` (since they were added after `textmacros` was created).  This PR added them in alongside the other `\textXYZ` macros.
Resolves issue mathjax/MathJax#2846.

Add \textup and \textnormal to allowed textmacros. (mathjax/MathJax#2846)

---

ts/output/chtml/Usage.ts

The CHTML adaptive CSS currently adds CSS rules for characters multiple times if they are used in multiple typeset calls.  I.e., typesetting `$$x$$`, then adding another `$$x$$` to the page and typesetting again will cause two copies of the CSS for the italic "x" to be added to the CHTML stylesheet.
This is due to the fact that the usage tracking for the characters uses a `Set()` object with arrays that represent the variant and the character in that variant, but since two arrays are different even if they contain the same content, the fact that `["italic", 0x1D465]` was already in the set was not being taken into account.
This PR fixes the problem by using a string rather than the array as the element in the set.  The original array is JSON stringified so that two copies of the arrays …

Prevent CHTML adaptice CSS from adding character CSS multiple times

---

ts/output/chtml/Wrappers/math.ts

This PR resolves the issue raised in mathjax/MathJax#2861 where attribute settings on a surrounding `<table>` can bleed into MathJax CHTML output.  It adds CSS to prevent that.

Include CSS to reset border-collapse in CHTML output.  (mathjax/MathJax#2861)

---

ts/output/chtml/Wrappers/TextNode.ts
ts/output/svg/Wrappers/TextNode.ts
ts/output/svg/Wrappers/mtext.ts

This PR resolves an issue where SVG output of token nodes with more than one child would get the horizontal position of the children incorrect.  This was due to the incorrect handling of the `element` property.  The fix is to wrap the children in a `<g>` tag when there is more than one, and position that, rather than assuming the last child is the only child, as was previously done.
There is also a comment typo fix, and a set in the CHTML output to avoid empty nodes when there are no children in a token node with an explicit font.
Resolves issue mathjax/MathJax#2836.

Update svg output to properly handle token elements with multiple child nodes. (mathjax/MathJax#2836)

---

ts/output/chtml/Wrappers/math.ts
ts/output/chtml/Wrappers/msqrt.ts
ts/output/chtml/Wrappers/munderover.ts
ts/output/common/OutputJax.ts
ts/output/common/Wrapper.ts
ts/output/common/Wrappers/maction.ts
ts/output/common/Wrappers/mfenced.ts
ts/output/common/Wrappers/mfrac.ts
ts/output/common/Wrappers/mmultiscripts.ts
ts/output/common/Wrappers/mroot.ts
ts/output/common/Wrappers/mrow.ts
ts/output/common/Wrappers/msqrt.ts
ts/output/common/Wrappers/msubsup.ts
ts/output/common/Wrappers/munderover.ts
ts/output/common/Wrappers/scriptbase.ts
ts/output/svg.ts
ts/output/svg/Wrapper.ts
ts/output/svg/Wrappers/maction.ts
ts/output/svg/Wrappers/math.ts
ts/output/svg/Wrappers/mfrac.ts
ts/output/svg/Wrappers/mmultiscripts.ts
ts/output/svg/Wrappers/mroot.ts
ts/output/svg/Wrappers/msqrt.ts
ts/output/svg/Wrappers/munderover.ts
ts/util/BBox.ts

This PR allows CHTML and SVG output to handle border and padding CSS values properly.  In the past, CHTML would show the borders and padding, but didn't take it into account in its bounding boxes, so things like square roots and stretchy delimiters would not produce the correct sizes, and sub- and super-scripts would be misplaced.  SVG did not handle these properties at all.
We fix the problem by introducing a new `getOuterBBox()` function that gets the bounding box taking borders and padding into account (the original `getBBox()` gets the size of the content without borders or padding, and is needed in that form to handle the internal layout properly).  This new method is called when a layout needs the size of a child node in elements that don't have inferred rows, which never have …

Handle border and padding CSS in CHTML and SVG output

---

package-lock.json
package.json
ts/a11y/explorer.ts

These are the final adaptations to SRE's new locale handling. In particular,
* We ignore bad locale options provided by local settings. While non-existent locales are handled by SRE falling back to an existing default (e.g., English), currently each explorer retains the incorrect locale. Now the first explorer will correct the options to contain the default locale. 
* This also ensures that there will always be a valid locale selected in the `Accessibility > Speech > Language` menu.
* SRE now has its own mapping for locales from iso to language name. We make use of this now in MJ.
Note, that this currently works only with the next patch release of SRE. I'll do that tonight, and will push one more commit with the correct version number in `package.json`.

Locale cleanup

---

ts/input/tex/mathtools/MathtoolsMethods.ts

This is a small PR to remove a fix in the mathtools package that compensated for not having proper border support.  This is no longer needed since the border code has been merged into develop.

Remove old compensation for not handling borders propoerly

---

ts/input/tex/SymbolMap.ts

This PR fixes a problem introduced by #788 that was originally to the html-in-tex branch, and relied on changes in that branch that affect the processing of SymbolMaps.  This PR adds those needed changes so that a parser method that returns false will cause further symbol lookups to occur.  This is needed by the changes for `\operatorname` to work properly.

Allow return value of false to be used in SymbolMap parsers to continue the lookup process.

---

ts/a11y/sre.ts

This PR exposes SRE's `toSpeech` API method in the `sre.ts` module. Although the method itself is not used elsewhere in `mathjax-src` it is used quite frequently in our demo files. 
Previously, this was not an issue, as we imported all of `sre_browser` via the global `SRE` variable, which made all API methods available there. However, now only API methods that are explicitly exported can be used, which only leaves `toEnriched`.
I would not regard this as a breaking change and therefore it would be helpful if we could include it in 4.2.1.

Expose SRE's toSpeech

---

ts/input/tex/base/BaseMethods.ts

If the base of an accent comes from `\operatorname`, for example, it will have the `movablelimits` property set to `true`, and so will convert to `msup` in in-line mode, causing incorrect rendering.  This PR makes sure `movable limits` is removed from an accent base to prevent that.

Remove movablelimits property if the accent base has it set

---

ts/input/tex/amscd/AmsCdMethods.ts

This PR corrects the width of an `mpadded` element used in the `amscd` extension so that it is an addition to the width rather than the width itself.  This was lost reign the v2 to v3 translation, apparently.  It also fixes some indentation problems in the code.

Fix relative width in mpadded, and correct indentation

---

ts/input/tex/ParseUtil.ts
ts/input/tex/empheq/EmpheqUtil.ts

This PR fixes a problem in `EmpheqUtils` where an `mtd` element is created and inserted into an `mtr` child list without properly setting the parent node.  There was a line that was supposed to do that, but apparently wan't working.  This PR replaces that line with one that sets the parent explicitly (not sure why I didn't do that originally).
It also fixes an issue where nodes could be added to the ParseOptions' `nodeList` for a list with an empty name (when the `in-lists` string is empty, the `split(/,/)` produces an array with an empty entry).
This resolves the issue Peter was having with his `subnumcases` environment.

Properly set parent for newly created mtd

---

ts/core/MmlTree/OperatorDictionary.ts

This PR makes the TeX class for U+2061 through U+2064 be class NONE rather than ORD so that when SRE inserts these, the spacing doesn't change.

Make U+2061 through U+2064 have TeX class NONE so they don't affect spacing.

---

.travis.yml
components/bin/version
components/webpack.common.js
ts/components/version.ts

This PR resolves the build issue that was reported with v3.2.1 due to the dynamic lookup of the version number by creating the `version.ts` file via `components/bin/version`, which is run during the travis-ci publish process (and can be run by hand at any point).
Resolve issue #818

Make version.ts use a constant and create the file during the build process.  (#818)

---

ts/input/mathml/mml3/mml3.ts

It turns out that the XSLTProcessor produces different results in Firefox and Chrome, and the code that obtained the `<math>` element didn't work in both, leading to an error message about `div` elements.  This PR uses a more robust approach to finding the `<math>` element.  We know here will be one (and only one) because this runs after the initial parsing of the math string, which checks for a single `<math>` element.
Resolves issue mathjax/MathJax#2879.

Make sure we get the <math> element from mml3 conversion.  (mathjax/MathJax#2879)

---

ts/ui/lazy/LazyHandler.ts

The changes to the lazy typesetting in v3.2.1 introduced an error where previously typeset expressions were re-typeset when they shouldn't be.  This lead to errors about labels already existing, in addition to the overhead caused by re-typesetting expression that didn't need it (more and more as you scroll).
This was caused by the fact that setting the document's state forced the math elements to be set to that state as well, whereas we only want to change the sate of the elements that have appeared on screen.  This is fixed here by restoring the `state()` method that was removed in 3.2.1.  It uses `restore === null` to determine whether the state is being changed by the lazy loader (and so prevents state changes on MathItems that should not be updated).
We also ignore non-TeX expressions …

Fix issue where lazy typesetting would re-typeset expressions unnecessarily.  (mathjax/MathJax#2873)

---

ts/ui/safe/SafeMethods.ts

https://github.com/mathjax/MathJax/issues/2885
If a href protocol contains `\n` or `\r` characters before `:`, the ui/safe newline parsing will interpret the protocol as `''`  and allow it. However, the browser will ignore the newline characters and interpret the protocol as the full word, allowing users to submit MathJax links with `javascript:` hrefs.
This commit updates the protocol-parsing regex to include new line characters, just as the browser does.
Example codepen that shows the bug: https://codepen.io/sgoedecke/pen/KKQJyPw
<details>
<summary>Example notebook</summary>
```
{
"cells": [
{
"cell_type": "markdown",
"metadata": {},
"source": [
"$\\href{java\nscript:alert(1)}{Click Me}$"
]
}
],
"metadata": {
"kernelspec": {
"display_name": "Python 2",
"language": "python",
"name": …
```

Parse link protocol containing newlines correctly in ui/safe

---

ts/ui/menu/Menu.ts

This PR resolves an issue where enabling the explorer for the first time causes an error (due to the dynamic loading of maps?).  The retry caused by SRE needs to be trapped by `handleRetriesFor()`, which is what this PR does.

Use handleRetries() to handle issue with rerender after explorer is enabled

---

ts/a11y/explorer.ts

This PR fixes a problem where the explorer domain and style menus are not initialized when first activated.  The problem is that the `a11y.speechRules` option, which is a compound of the `sre.domain` and `sre.style` options, is not initialized.  The fix is to initialize it during the creation of the explorer document based on the `sre` options.

Make sure a11y.speechRules in initialized

---

ts/input/tex/ams/AmsMethods.ts

This PR updates the aligned and alignedat environments to handle the optional bracket argument consistent with current versions of LaTeX, where no spaces are allowed before the bracket argument.
Resolves issue mathjax/MathJax#2888.

Update handling of brackets in algined environments to current LaTeX behavior (mathjax/MathJax#2888)

---

ts/core/MmlTree/MmlNode.ts

This PR adds logic to identify attributes that should not be inherited into child nodes.  The current values are to prevent `columnalign`, `rowalign` and `groupalign` from an outer table from being applied to nested tables.
Resolves issue mathjax/MathJax#2890.

Prevent inheritance of align attributes in nested tables (mathjax/MathJax#2890)

---

ts/input/tex/autoload/AutoloadConfiguration.ts
ts/input/tex/html/HtmlConfiguration.ts
ts/input/tex/html/HtmlMethods.ts
ts/input/tex/textmacros/TextMacrosMappings.ts

This PR is a continuation of #791 (which incorrectly committed to the master branch). It adds the `\data` command to the HTML extension to allow adding `data-*` attributes to MathJax content. Documentation is in https://github.com/mathjax/MathJax-docs/pull/299 (`MathJax-docs` doesn't seem to have a `develop` branch).

Add \data to html extension

---

ts/output/chtml.ts
ts/output/chtml/FontData.ts
ts/output/chtml/Wrappers/TextNode.ts
ts/output/chtml/Wrappers/mo.ts
ts/output/common/FontData.ts

This PR updates the CHTML output jax to use actual character data rather than CSS `content` rules to insert the characters used for display.  This allows the content of CHTML output to be selected and copied, as in v2 (note, however, that because the height/depth of the MathJax TeX fonts are near zero, the selection will not show very well -- this will be fixed as part of the update to the TeX fonts).  
This also changes the CHTML `TextNode` implementation to combine unknown characters into a single `utext` element rather than having a separate one for each character.  This allows combining characters to combine (e.g., multiple-character emoji or flags) when they are entered directly as text, even without `\text{}`).

Make CHTML use actual characters rather than CSS content specifications

---

ts/adaptors/HTMLAdaptor.ts
ts/adaptors/NodeMixin.ts
ts/adaptors/liteAdaptor.ts
ts/core/DOMAdaptor.ts
ts/core/MmlTree/MML.ts
ts/core/MmlTree/MmlNode.ts
ts/core/MmlTree/MmlNodes/HtmlNode.ts
ts/core/MmlTree/SerializedMmlVisitor.ts
ts/input/mathml/MathMLCompile.ts
ts/output/chtml/Wrappers.ts
ts/output/chtml/Wrappers/HtmlNode.ts
ts/output/common.ts
ts/output/common/Wrapper.ts
ts/output/common/Wrappers/HtmlNode.ts
ts/output/svg/Wrapper.ts
ts/output/svg/Wrappers.ts
ts/output/svg/Wrappers/HtmlNode.ts
ts/output/svg/Wrappers/mfenced.ts

This PR implements the ability to include HTML within token elements in MathML (as allowed in HTML5).  It does so by implementing an HtmlNode class that holds the HTML tree.  This is inserted into the MathML token node child array whenever a non-MathML node is found.  Thus `<mtext>abc<input type="button" value="Push Me">def</mtext>` is allowed, and would produce an `mtext` element containing a button surrounded by some plain text.
Because the HTML is not currently sanitized (something that could be added to the `safe` extension), allowing HTML in token elements would be a security issue for sites that allow user-entered MathML.  For this reason, the MathML input jax has a new option `allowHtmlInTokenNodes` to control whether to allow it, and it is false by default.
The `makeNode()` method …

Implement HTML in MathML token nodes.  (mathjax/MathJax#1128)

---

ts/input/tex/Tags.ts

This PR allows labels nested within `aligned`, `split`, and `gather` environments to apply to the outer equation.  It does so by bubbling the `label` property up to the outer `TagInfo` object in the `end()` method, if there isn't already a label in that one (and carrying a label down into the new `TagInfo` in the `start()` method), and clearing the label when a tag is assigned to it.
This resolves issue mathjax/MathJax#2889.

Handle labels nested in aligned environments (mathjax/MathJax#2889)

---

ts/input/mathml/FindMathML.ts

This PR prevents MathML that is the result of the AssistiveMML extension from being processed by the MathML input jax (in the event that the page is retypeset).  It also switches some `let` commands to `const`, and uses `set.values()` rather than `Array.from(set)` for efficiency.
Resolves issue mathjax/MathJax#2892.

Don't typeset mathml inserted by the AssistiveMML extension. (mathjax/MathJax#2892)

---

ts/core/MmlTree/OperatorDictionary.ts

This PR fixes a typo in the operator dictionary RANGES array that causes output errors for characters in the range U+20000 to U-2FA1F.
Resolves issue mathjax/MathJax#2893.

Correct typo in RANGES array affecting CJK characters in U+20000 to U-2FA1F.  (mathjax/MathJax#2893)

---

ts/output/chtml/Wrappers/munderover.ts
ts/output/chtml/Wrappers/scriptbase.ts

With CHTML's dynamic CSS handling, the CSS needed for properly handling the `scriptspace` font parameter was only being output when `msubsup` or `mmultiscripts` was used.  This PR make sure the CSS is present for any script-based class (`msub`, `msup`, `munderover`, etc.).

Make sure the scriptspace CSS is included for any script class

---

ts/input/tex/newcommand/NewcommandMethods.ts

If a macro definition has a template, but requires no arguments (e.g., `\def\a\b{...}`) then the template is not checked and not properly removed.  This PR makes sure the template matches its usage, and removes it.
Resolves issue mathjax/MathJax#2901.

Fix handling of template macros with no actual arguments. (mathjax/MathJax#2901)

---

ts/a11y/semantic-enrich.ts

Fix problem with semantic-enrich's `getSpeech()` method.  It currently only checks the first child node (recursively to the bottom of the tree), as the termination condition will end the loop when the child node returns an empty string, so the second and subsequent children are never checked.
Resolves issue mathjax/MathJax#2911.

Properly locate speech string when not in first child element. (mathjax/MathJax#2911)

---

ts/input/tex/ParseUtil.ts
ts/input/tex/ams/AmsMethods.ts

This PR corrects #832 for mathjax/MathJax#2888 so that the behavior is more consistent with LaTeX.  It's not that the bracket is only scanned if it is immediately after the environment name (as in #832), but rather than it is only removed and used for alignment when it is exactly one of `[t]`, `[b]`, or `[c]`.  Otherwise, it is retained and processed normally.
The fix is handled in `setArrayAlign()` by adding `parser` and `i` arguments that, if present, will cause `parser.i` to be set to `i` if the bracket is not one of the allowed values.
There is also a typo (in two places) in an error message that is corrected here.

Handle bracket arguments for align environments more like LaTeX.

---

components/src/dependencies.js
components/src/input/tex/extensions/texhtml/build.json
components/src/input/tex/extensions/texhtml/texhtml.js
components/src/input/tex/extensions/texhtml/webpack.config.js
components/src/source.js
ts/core/MmlTree/MmlNodes/HtmlNode.ts
ts/core/Tree/Visitor.ts
ts/handlers/html/HTMLDomStrings.ts
ts/input/tex/AllPackages.ts
ts/input/tex/require/RequireConfiguration.ts
ts/input/tex/texhtml/TexHtmlConfiguration.ts

This PR adds a `texhtml` extension for the TeX input jax that allows HTML within TeX input.  This is done by enclosing the HTML in a special tag, `<tex-html>...</tex-html>` that is processed specially by the TeX input jax:  it inserts `\texHTML{...}` around a serialized version of the HTML so that it can be part of a TeX string.  The `\texHTML` macro then turns the HTML into the internal `mtext` node containing an `HtmlNode` that handles the HTML in the internal MathML representation.  So for example:
```
$$3 + <tex-html><input type="text" id="answer" size="10"></tex-html> = 10$$
```
When used in an HTML page, the HTML will already be in the page as actual DOM nodes, but when used with `MathJax.tex2chtml()` or `MathJax.tex2svg`, the DOM elements will not be parsed as HTML, so you should …

Add support for HTML within TeX

---

ts/input/tex/ParseUtil.ts
ts/input/tex/ams/AmsMethods.ts
ts/input/tex/mathtools/MathtoolsMethods.ts

This PR fixes a problem reported by Peter where `alignedat` would typeset its number argument when there is no bracket argument.  It also handles invalid bracket arguments like LaTeX does (the number argument is parsed after the brackets, then the brackets are typeset).  These issues were introduced by #842, which would reset the `parser.i` value to before the brackets when they were empty to invalid.  Now we re-insert the bracket argument if it is non-empty and invalid (like LaTeX does).
After #842,
``` latex
\begin{alignedat}{2} a \end{alignedat}
```
would typeset as `2a` when it should just be `a`.  This PR should resolve that.
Also,
``` latex
\begin{alignedat}[x]{2} a \end{alignedat}
```
would produce `[x]2a`, but now should produce `[x]a` as LaTeX does.

Handle missing and invalid brackets in alignedat like LaTeX does.

---

components/src/ui/safe/safe.js
ts/adaptors/lite/Parser.ts

This PR removes the `CDATA_ATTR` array for the LiteDOM and always translated entities both during parsing of attributes and during serialization.  It also allows the `safe` extension to be used with the LiteDOM (not sure why it was excluded before, as it seems to work just fine).

Update lite DOM

---

ts/input/tex/physics/PhysicsMethods.ts

This PR make sure closing parentheses get the proper `mathvariant`.
Resolves issue mathjax/MathJax#2921.

Use the correct font for closing parentheses in physics package. (mathjax/MathJax#2921)

---

ts/util/Styles.ts

Today I have created a library to render Mathjax LiteDOM into React element tree.
https://github.com/rhysd/react-mathjax-component
One problem I'm facing is that there is no way to access to the key-value pairs of style value stored in `Styles` object. Since React element requires to specify styles through an object like `{maxWidth: '100px'}`, CSS text does not work. But `Styles` object only provides a way to get CSS styles as string. Currently my package [re-parses](https://github.com/rhysd/react-mathjax-component/blob/721b674b236786ad0517f897797df3b81f5bc8c5/litedom.ts#L14) the CSS text returned from `Styles` object but this is redundant (`Styles` generates a CSS string and my package restores the original key-value pairs of style object).
This PR fixes the problem by exposing the …

Expose `StyleList` value contained in `Styles` object

---

components/src/output/chtml/fonts/tex/tex.js
components/src/output/svg/fonts/tex/tex.js
ts/output/chtml/fonts/tex.ts
ts/output/common.ts
ts/output/common/FontData.ts
ts/output/common/Wrappers/mo.ts
ts/output/common/fonts/tex.ts

This PR reorganizes some properties from the `FontData` object and its subclasses so that TeX-specific information is in the TeX font subclass, and the common data is in `FontData`.  This includes:
* Moving `getDelimiterData()` to the CHTML TeX font subclass.
* Moving the `-tex-*` variants that are used by the TeX input jax into the common `FontData` so that they don't have to be repeated in every subclass.
* Moving the MathJax-TeX-font specific remappings into the TeX font subclass (they aren't the same for STIX and other fonts).
In addition, the `font` option for the output jax is extended to allow the specification of a FontData class rather than just an instance.  That simplifies the components that set up the fonts for CHTML and SVG, which used to have to create a font instance but …

Refactor some FontData properties, and allow specifying a FontData class rather than instance

---

ts/input/tex/base/BaseMappings.ts

This PR removes the explicit use of `thickmathspace` in `\bmod` and uses the numeric equivalent instead.  It also makes a variable for `em(MATHSPACE.thickmathspace)` and uses that so that it doesn't have to be computed multiple times.
Resolves issue mathjax/MathJax#2902.

Change usage of thickmathspace to numeric value in \bmod.  (mathjax/MathJax#2902)

---

ts/ui/menu/Menu.ts

This PR makes sure the SVG global font cache is set up when you switch renderers using the contextual menu.  It does so by calling the `initialize()` method for the output jax when it is first loaded.
To test, use the lab and set the font cache to global in the SVG output options, then go back to CHTML and "keep" the page.  Switch to SVG after it is released.  Without the patch, there should be an error message in the console, but with the patch, the change of renderers should occur properly.
Resolves issue mathjax/MathJax#2924.

Initialize the output jax when switching renderers for the first time. (mathjax/MathJax#2924)

---

components/src/input/mml/entities/entities.js

This PR adds the version check to the entities component (which is usually added in the `lib` file from the `build.json` file, but this component doesn't have one, so it must be added manually).  This will avoid a warning message about the component not having a version number.
This resolves part of mathjax/MathJax-demos-node#51.

Add version check to entities component.

---

ts/input/tex/texhtml/TexHtmlConfiguration.ts

This PR fixes a problem where an infinite loop occurs when `<tex-html>...</tex-html>` is used more than once in an equation.
Resolves issue mathjax/MathJax#2948.

Fix infinite loop when <tex-html> is used more than once (mathjax/MathJax#2948)

---

ts/input/tex/physics/PhysicsItems.ts

This PR fixes the parsing of `|` delimiters in the physics package.  The code that tests for nested delimiters was considering the closing `|` to be the opening delimiter of a nested set of `|` delimiters, leading to an error about missing close delimiters.  The solution is to put the check for nested delimiters *after* the check for closing delimiter to allow for open and close delimiters to be the same character.
Resolves issue mathjax/MathJax#2973.

Fix parsing of vertical bar delimiters in physics package (mathjax/MathJax#2973)

---

ts/input/tex/ams/AmsMethods.ts

Currently, `\operatorname{atan2}` renders with a space between `atan` and `2`.  This is due to the multi-letter identifier getting TeX class OP automatically.  This PR adds the `noAutpOP` flag to the processing of the operator name to avoid that.
Resolves issue mathjax/MathJax#2991.

Better handling of multiple children from \operatorname{} (mathjax/MathJax#2991).

---

ts/core/MmlTree/MathMLVisitor.ts
ts/core/MmlTree/MmlVisitor.ts
ts/core/MmlTree/SerializedMmlVisitor.ts
ts/ui/menu/MmlVisitor.ts

This PR makes the MathMLVisitor work more like the SerializedMmlVisitor in terms of handling of attributes and converting TeXAtom nodes to mrows.  Common code has been moved to the common MmlVisitor class that is the root for both.  This invalid moving the static data items from SerializedMmlVisitor to MmlVisitor, as well as the protected methods for managing the attribute lists, so the big chunk of additions to MmlVisitor is just moving the code from SerializedMmlVisitor.  The handling of TeXAtom nodes as a special case has been removed in favor of a translation table for the node kind.  Support for the new HTML nodes has been added to the MathMLVisitor.
Resolves issue mathjax/MathJax#2920.

Refactor MathML visitors to make MathMLVisitor work like SerializedMml. (mathjax/MathJax#2920)

---

ts/adaptors/linkedomAdaptor.ts

This PR changes how the missing `HTMLCollection` is added to windows for linkedom.  In the past it was added to the Window class's prototype, but that seemed to interfere with SRE for some reason.  This is changed to add it to the window instance itself, as that is really all MathJax needs (it is used in `mathjax.document()` to determine if the data passed to it is an `HTMLCollection` as one of the options).

Add HTMLCollection to Window instance not constructor prototype

---

ts/input/mathml.ts

The `linkedom` adaptor fails to parse MathML as an HTML snippet, so this PR adds tags to the MathML to make sure it is parsable as HTML.  This should not interfere with parsing in the browser or in LiteDOM, and is probably a good idea in any case.

Add <html>, <head>, and <body> tags to mathml when parsing as HTML

---

components/src/a11y/semantic-enrich/semantic-enrich.js

This PR prevents errors on re-parsing the enriched MathML when the original MathML includes embedded HTML.

Allow semantic-enrich to enrich HTML-in-MML

---

ts/output/chtml/Wrappers/scriptbase.ts
ts/output/common/Wrappers/munderover.ts
ts/output/common/Wrappers/scriptbase.ts

The placement of top and bottom in `munderover` and related constructs were not correct if the `munderover` is scaled, as in `\huge\vec x`.  This was due to the use of the wrong scaling factors in determining the height of the base and the horizontal position of the super- or subscript.  This PR uses the correct scaling factors.
Resolve issue mathjax/MathJax#2983.

Use proper scaling factors for placement of top and bottom when scaled (mathjax/MathJax#2983)

---

ts/input/tex/ams/AmsMappings.ts
ts/input/tex/base/BaseMappings.ts

This PR corrects the unicode value for `\models` and removes the variant form from `\vDash` (this will be correct once we go to the mathjax-modern font).
Note, however, that the TeX/LaTeX version of `\models` does not appear the same as the U+22A7 glyph in the mathjax-modern font.  TeX uses the equivalent of `\def\models{\mathrel{|\!=}}`; should we do that as well?
Resolves issue mathjax/MathJax#2543.

Map \models to correct Unicode point, and don't use variant form for \vDash (mathjax/MathJax#2543)

---

ts/input/tex/textmacros/TextMacrosMappings.ts
ts/input/tex/textmacros/TextMacrosMethods.ts

This PR adds `\underline`, `\llap`, `\rlap`, the phantom and `\smash` macros, and `\mmlToken` to the `textmacros` package so they can be used in text mode, as they are allowed in LaTeX text-mode.
Resolve issue mathjax/Mathjax#2969.

Add \underline and several other macros to textmacros. (mathjax/MathJax#2969)

---

ts/input/tex/ParseUtil.ts

This PR makes sure that newlines in text-mode are treated as spaces.  Currently they are preserved as newlines, but that isn't how TeX would treat them.
Resolves issue mathjax/MathJax#2993

Handle newlines as spaces in text mode. (mathjax/MathJax#2993)

---

ts/output/chtml/FontData.ts

This PR fixes a problem where some accents are misplaced.  Combining accents like U+0302 are handled in some fonts by making zero-width characters that have negative left bearing (so they extend to the left over the character that precedes them).  Modern browser will position combining characters automatically, whether they are zero-width or not (and they do vertical positioning so that accents are placed over both lower-case and capital letters properly).
MathJax expects the browser to respect the widths of the characters in the font, so when the browser makes it zero-width automatically, MathJax misplaces the accent.  This PR makes sure that the accents are properly placed regardless of whether the character is zero-width or not, and regardless of whether the browser forces zero-width …

Work around combining characters being handled as 0-width automatically by some browsers

---

ts/input/tex/ams/AmsMethods.ts

This PR fixes the vertical separation between `\xrightarrow` and the item above it.  It was due to the depth of the strut used to make sure that all the over items are aligned vertically on their baselines, but the value of the depth was based on earlier font handling, where the stretchy characters had the height of their extender, not the assembly as a whole.  The new font settings have all elements in the assembly having the same height and depth in order to improve alignment among the parts, and that is the maximum of the heights and depths of all the parts.  That makes the arrows taller than they were, and so a smaller strut is needed.
Resolves issue mathjax/MathJax#2981.

Fix vertical separation for x-arrows (#mathjax/MathJax#2981).

---

ts/output/chtml/Wrappers/mpadded.ts

This PR fixes a bug in CHTML output for `mpadded` elements that have no content.  The height and/or depth was not being properly handled in the output unless there was content, so this PR adds an empty box so that the depth shows properly.
For example:
``` html
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
<mpadded height="1em" depth="1em" width="1em" background="red" />
<mi>x</mi>
</math>
```
would not have the proper depth before this PR.

Fix CHTML so that depth is correct for empty mpadded elements.

---

ts/output/chtml/FontData.ts
ts/output/chtml/Wrappers/mo.ts
ts/output/common/Wrappers/mo.ts

This PR fixes two problems with stretchy characters.  
The first is that when a character stretches to one of the fixed-size alternatives, its bounding box needs to be recomputed, but that wasn't the case.  This caused the incorrect offset reported in mathjax/MathJax#2981, e.g., for `\xrightarrow{ab}`.
The second is when a multi-character assembly is needed for horizontal stretchy character:  if the size needed for the extenders is smaller than the width of the character used for the extender, then in CHTML, the extender would be too large (the size of the original character).  For example, with `\overparen{xxxxxxxx}` and `\overbrace{xxxxxxxx}`.  The CSS change solves that problem.
Finally, there was a missing jsdoc parameter in a FontData file.
Resolves second issue from …

Fix problems with horizontal stretchy characters (mathjax/MathJax#2981)

---

ts/components/startup.ts
ts/output/chtml/FontData.ts
ts/output/chtml/fonts/tex.ts
ts/output/common/FontData.ts
ts/output/common/Wrapper.ts
ts/output/common/fonts/tex.ts
ts/output/svg/FontData.ts
ts/output/svg/fonts/tex.ts

This PR adds the ability to specify font extensions that will be loaded dynamically when less-used characters are needed. You can specify any number of extensions, and these can contain characters from any number of variants, or additional delimiters.  The specification for a dynamic extension includes the file to load for the extension, along with the ranges of characters that it provides in each variant that it modifies.  When an output jax needs one of these characters or delimiters, the extension is loaded and set up, and the expression is reprocessed.

Provide support for dynamically loading font data

---

ts/output/common/Wrapper.ts
ts/output/common/Wrappers/mrow.ts
ts/output/common/Wrappers/mtable.ts
ts/output/common/Wrappers/mtr.ts
ts/output/common/Wrappers/scriptbase.ts

This PR fixes a problem reported by Peter where some horizontally stretched characters are stretched to the wrong length.  For example:
``` latex
\bbox[red]{\begin{smallmatrix}
- \otimes _k tk \\
\xleftarrow {\hspace{50pt}}\\
\xleftarrow {\hspace{50pt}}\\
\xleftarrow {\hspace{50pt}}\\
\operatorname {Hom}_k(tk,-)
\end{smallmatrix}}
```
in SVG output.  An incorrect relative scaling value was being used (with an embellished operator, the relative scaling of the core has to include all the nesting parent elements).

Make sure stretchy embellished operators use the proper scaling when determineing their widths

---

ts/input/tex/base/BaseMethods.ts

Currently, `\underset`, `\overset`, and `\underoverset` force `accent="false"` on `mo` elements that are set on top or bottom of the base.  This PR allows a (possibly embellished) operator that has an explicit `accent="true"` to set the `accent` or `accentunder` attributes of the `munder`, `mover`, or `munderover` that is produced.  That allows, for example
``` latex
\underset{\mmlToken{mo}[accent="true"]{⎵}}{abcabc}
```
to properly handle the underbrace as an accent (i.e., without reducing its scale).   (Without this PR, the accent always gets `accent="false"`, and so is reduced in size.  There is an additional but where that causes the stretchy character not to stretch sufficiently, but that is treated in the fix-stretchy-widths` branch.)

Allow (embellished) operators in \underset, \overset, and \underoverset to specify accent="true"

---

ts/output/common/Wrapper.ts
ts/output/svg/Wrapper.ts

This PR resolves a problem where borders that don't specify an explicit color were getting the wrong color in SVG output due to using 'currentColor', which caused them to get the color of the text surrounding the math as a whole.  Instead, they should just not set the fill color and let it be inherited.
Resolves issue mathjax/MathJax#2939.

Allow borders to inherit surrounding color in SVG (mathjax/MathJax#2939)

---

ts/core/MmlTree/MmlNodes/math.ts
ts/core/MmlTree/MmlNodes/mstyle.ts
ts/output/common/Wrapper.ts

This PR moves the checking of `scriptminsize` to later in the calculation of the scaling factor so that `mathsize` and `font-size` CSS are included in the test, and also changes the default value to a better one (see mathjax/MathJax#2975).
Resolves issue mathjax/MathJax#2975.

Better handling of scriptminsize (mathjax/MathJax#2975)

---

ts/input/tex/colortbl/ColortblConfiguration.ts

This PR allows `\columncolor` to be used in an array environment preamble (where it is supposed to be used).  We allowed it in the top row in previous versions because we were not processing all the preamble options until now.  This PR allows it to be used both in the preamble and the first row of the array.
Resolves issue mathjax/MathJax#2955.

Allow \columncolor in the array preamble.  (mathjax/MathJax#2955)

---

ts/input/tex/Tags.ts

This PR adds an option to specify the vertical placement of tags in TeX expressions.  The main purpose is to center the tags for long expressions that have line breaks.
Resolves issue mathjax/MathJax#2977.

Provide an option for placement of equation numbers in TeX input.  (mathjax/MathJax#2977)

---

ts/input/tex/base/BaseMappings.ts
ts/input/tex/base/BaseMethods.ts

When used in prefix or postfix positions, the operator dictionary gives `|` TeX class of OPEN or CLOSE, but TeX creates it as ORD in these locations.  This PR forces the TeX input jax to make it ORD, while still allowing MathML to treat them as OPEN and CLOSE in a construction like `<mrow><mo>|</mo><mi>x</mi><mo>|</mo></mrow>` that corresponds to `\left|x\right|` (where they *do* have OPEN and CLOSE class).
Resolves issue mathjax/MathJax#2938 and part of mathjax/MathJax#2894.

Make vertical bar have the correct TeX class.  (mathjax/MathJax#2938)

---

ts/core/MmlTree/MmlNodes/maction.ts
ts/output/chtml/Wrappers/maction.ts
ts/output/svg/Wrappers/maction.ts

This PR fixes a problem where the scaling for `mtext` elements in tooltips is wrong when `mtextInheritFont` is true (or `mtextFont` is set).  This was due to the CSS `font-size: 70%`, which wasn't being taken into account with the measuring of the font size of the inherited font.  The solution used here is to remove the 70% scaling and setting the `scriptlevel` to 1 (which is a 70.7% scaling).

Fix scaling of tooltips when text font is inherited. (mathjax/MathJax#2957)

---

ts/handlers/html/HTMLDomStrings.ts

This PR adds `<select>` and `<option>` tags to the `skipHtmlTag` list, since the contents of `<option>` is text-only, and shouldn't be modified by MathJax.
Resolves issue mathjax/MathJax#3006.

Don't typeset within <select> or <option> nodes. (mathjax/MathJax#3006)

---

ts/output/common/Wrapper.ts

When automatic inline breaking is turned off, a forced line break in an inline expression ends up using the `displayAlign` and `displayIndent` values rather than being left aligned and unindented.  This PR forces left alignment and 0 indent in that case.
Resolves one issue from mathjax/MathJax#3005.

Use left alignment and no indent for forced inline breaks when inline breaking is off. (mathjax/MathJax#3005)

---

components/bin/build
ts/output/chtml.ts
ts/output/chtml/DynamicFonts.ts
ts/output/chtml/FontData.ts
ts/output/chtml/Wrapper.ts
ts/output/chtml/Wrappers/TextNode.ts
ts/output/chtml/Wrappers/math.ts
ts/output/chtml/Wrappers/mo.ts
ts/output/chtml/fonts/tex.ts
ts/output/common.ts
ts/output/common/FontData.ts
ts/output/common/Wrappers/mspace.ts
ts/output/svg.ts
ts/output/svg/Wrappers/math.ts

This PR finalizes the updates needed for additional font support by updating the CHTML output to handle the alternate fonts being prepared in the fonts repository.
* Provide for updating the CSS when a new font is loaded
* Creates an `addFontIds()` function that inserts the needed font ID data into a font definition (to save hading the same `f` option in each of the character's data).
* Updates the creation of CSS for the stretchy characters to include the font explicitly, when needed
* Assumes the ZERO font will have a space that is one em wide (making it easier to handle in-line breakpoints for linebreaking).  This affects both SVG and CHTML output, and it will make it not work with the current MathJax_Zero font, whose space is .25 em, so the spacing will be too small when used with …

Updates to support alternate fonts in CHTML

---

ts/output/common.ts
ts/output/common/Wrapper.ts
ts/output/svg.ts
ts/output/svg/Wrappers/TextNode.ts

This PR provides a configuration option that controls the stroke-width used for characters in SVG output.  This allows the author to adjust the thickness to better match he surrounding font, if needed.  The current default is 3, but I prefer values more like 10 or even 15 on MacOS.  But the AMS would like to use 0.
This is accomplished by providing a per-wrapper function that adds the wrapper-specific CSS so that it can use the output jax options to control the styles.
Resolves isses mathjax/MathJax#2859.

Allow SVG character stroke-width to be specified. (mathjax/MathJax#2859)

---

ts/input/tex/ParseUtil.ts
ts/input/tex/ams/AmsMethods.ts
ts/input/tex/base/BaseMethods.ts
ts/input/tex/empheq/EmpheqConfiguration.ts
ts/input/tex/mathtools/MathtoolsMethods.ts

This PR redoes the check for improperly nested AMS environments, which currently allows them to be used in situations where they are not allowed in LaTeX (e.g., there is no error if they are not a top-level environments, so `align` can be used inside an array, for example, where it shouldn't be allowed).  So we introduce a test for being at the top level (the task top must be a `start` item with no stored nodes).
On the other hand, `gather` should allow nested `align` and other environments (but not another `gather`), so we use a `nestable` property and ad an extra parameter to tell if the current environment is a second `gather`.
All of this makes the `eqnenv` global property no longer necessary.
Resolves issue mathjax/MathJax#1892.

Better checking of improperly nested AMS environments. (mathjax/MathJax#1892)

---

ts/a11y/assistive-mml.ts

This PR adjusts the CSS for the assistive MathML output so that it fits the space of the math expression exactly, as the current arrangement sometimes allows it to be larger than the MathJax output.  It also adds a `clip-path` since `clip` is deprecated.  Leaving the `clip` CSS allows for support of IE11 (though I'm not sure how much of MathJax still works in IE).

Update CSS for assistive-mml. (mathjax/MathJax#2936)

---

ts/input/tex/base/BaseMethods.ts

This PR makes `|` non-stretchy when not used as a delimiter, restoring its behavior from before #907, which implemented the `Bar` method for it.

Prevent vertical bar from being stretchy unless used as a delimiter.

---

ts/output/common/Wrapper.ts

This PR fixes an issue that can cause a crash during line-breaking when a fraction or square root needs to be broken and it is inside an `mstyle` element that is also broken.  For example
``` xml
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
<mstyle>
<mtext>aaaaaa</mtext>
<mo>+</mo>
<msqrt>
<mi>x</mi>
<mo>+</mo>
<mi>y</mi>
<mo>+</mo>
<mi>z</mi>
<mo>+</mo>
<mi>z</mi>
<mo>+</mo>
<mi>z</mi>
<mo>+</mo>
<mi>z</mi>
</msqrt>
</mstyle>
</math>
```
when the container is smaller than the width of the square root.
The change at 594 prevents `this.lineBBox[i]` from being undefined, which it seems to be when the `getOuterBBox()` call is in the `LineBBox.from()` for some reason.  I could not figure out why.  It happened for the outermost `math` element with the example above, and …

Fix potential crash with linebreaks.  (mathjax/MathJax#3015)

---

ts/output/common/Wrappers/mtable.ts

This PR takes the label and padding properly into account for deciding the width for a table when determining column break widths.  In particular, it does the right thing for centered tables.

Allow space for labels when deciding on a table's width for line breaking its columns.

---

ts/handlers/html/HTMLDocument.ts

This PR refactors the `HTMLDocument.findMath()`method so that the order of the math is preserved properly.  This is done by changing the order of the nested loops.  In the past, the outer loop was on the containers, and then each Jax was called to find its math and the results were merged into the document list.  This failed to work properly because the sorting is based on the index of the string in which the math was found, but the list of strings is separate for each container, so they get interleaved when merged.  (See mathjax/MathJax#2999 for an example.)
Now the order is to loop over the jax first, and then over the containers, so that all the strings for all the containers are in one larger list, and there is no interleaving.  At least not for a single typeset call.
Resolves issue …

Make sure multiple elements are typset in order. (mathjax/MathJax#2999)

---

ts/output/common/Wrappers/TextNode.ts
ts/output/svg/Wrapper.ts
ts/output/svg/Wrappers/TextNode.ts

This PR groups runs of unknown characters into a single `<text>` element in SVG output, just as was implemented in CHTML in #734 in commit 115c5423.  It also makes the computation of the bounding box consistent with that, since text with combining characters will have a different width when grouped together than when handled separately.  (The bounding box computations were wrong for CHTML, but since most of the CHTML doesn't depend on those computations, not wasn't caught.)  For example, with `\text{🇦🇩}`, the output was correct but the bounding box computation was wrong.
Resolves issue mathjax/MathJax#2672.

Combine unknown characters into a common <text> element.  (mathjax/MathJax#2672)

---

ts/core/MmlTree/MmlNodes/mo.ts
ts/output/chtml/Wrapper.ts
ts/output/chtml/Wrappers/math.ts
ts/output/chtml/Wrappers/mrow.ts
ts/output/common.ts
ts/output/svg.ts
ts/output/svg/Wrappers/math.ts
ts/output/svg/Wrappers/mrow.ts

This PR fixes a number of problems with inline breaks in SVG and CHTML output.
* The old approach of using `font-size` to scale a 1em space to the proper size turns out not to work as well as hoped, since it runs into the minimum font size settings of most browsers.  Instead, we now use `letter-spacing` to adjust the size of the space without scaling.  The space is still 1em, so we are usually removing space from it.
* For CHTML output, the `mjx-linestack` and `mjx-linebox` nodes were not being set to `display: inline` as needed for inline breaks because the math node wasn't setting the `breakable` attribute on its children.  This was due to a change in the property name from `breakable` to `process-breaks` in an earlier PR that missed changing the name in the math wrapper, and also to …

Fix several issues with inline breaks. (mathjax/MathJax#3005)

---

ts/input/tex/ParseUtil.ts
ts/input/tex/autoload/AutoloadConfiguration.ts
ts/input/tex/base/BaseMethods.ts
ts/input/tex/textmacros/TextMacrosMappings.ts
ts/input/tex/unicode/UnicodeConfiguration.ts
ts/util/string.ts

This PR implements a version of the low-level `\char` command for inserting characters by number (decimal, octal, or hex) or by character (e.g., `\char'\%` or `\char'A`).  In actual TeX, these are font positions in TeX fonts, and are limited to 0 to 127, but here, they are Unicode code points, and can be 1 to 6 hex digits.  So `\char"222B` is the integral sign, for example.  These are mapped to MathML nodes using the `Other()` function from the base methods (so uses the `RANGES` list from the operator dictionary to determine the node type to use).
We also add a `\U` macro for inserting a character into the TeX input string by Unicode hex code point.  So `\U{222B}` is the integral sign.  This is different from `\unicode{x222B}` as the latter always produces an `mtext` node, while the …

Implement \char and add \U for raw unicode characters.

---

ts/input/tex.ts
ts/input/tex/ParseOptions.ts
ts/input/tex/base/BaseMappings.ts
ts/input/tex/base/BaseMethods.ts

This PR adds a number of macros and environments that have been requested in the past, now that we have fonts that contain the needed characters.  These include `\AA`, `\iddots`, `\oiint` and `\oiiint`, plus I added `\dddot` and `\ddddot` accents, and the missing `\ointop`.  The `TEXCLASS.OP` has been removed from the big operators, since those will be inherited from the operator dictionary, so no need to waste the space on redundant values.  The unicode value for `\backslash` has been changed to just `\`. 
The new environments are `darray` for an array in display mode, and `math` and `displaymath`.  Since `\begin{xyz}...\end{xyz}` are parsed as math-mode delimiters, and these default to display mode, the `math` environment requires the ability to change the MathItem's `display` property …

Add requested macros and environments now that we can support them.

---

components/src/node-main/node-main.js
ts/output/common/Direction.ts
ts/output/common/FontData.ts
ts/output/common/fonts/tex/delimiters.ts

This PR adds methods to support creating an extension that modifies an existing font.  For example, an extension could override the characters used for the letters and numbers while leaving all the other characters in place, or could add coverage for special symbols that are missing from the font originally.
There are two new `addExtension()` methods:  a static one on the `FontData` class that modifies the class defaults before it is instantiated, and one on the `FontData` instance that modifies the data for a given font instance.  This allows a font to be extended before it is used, or to be extended dynamically once it is in place.
The font tools (currently under construction) will create the needed data and extension files that call the new `addExtension()` methods.

New methods to add to a font via an extension

---

ts/input/tex/base/BaseMethods.ts

This PR prevents `\overrightarrow` and similar macros from treating the stretchy character as a math accent (which doesn't contribute to the width even if it extends beyond the base).  The arrow should count in the width when the base is smaller than the arrow.
Resolves issue mathjax/MathJax#3010.

Don't treat \overrightarrow as a mathaccent.  (mathjax/MathJax#3010)

---

ts/core/MmlTree/MmlNodes/mrow.ts

This PR fixes a problem where an `mrow` that comes from `\left...\right` isn't treated as TeX class `INNER` by the item that follows it.  The fix is to return the `mrow` itself (not the last child of the `mrow`) in the `setTeXclass()` method.
For example, the spacing is wrong for `a\left(b\right)c` without this PR.
Resolves issue mathjax/MathJax#3018

Handle mrow with class INNER as a unit.  (mathjax/MathJax#3018)

---

ts/output/common/Wrappers/mo.ts

This PR causes null delimiters to get the font's `nulldelimiterspace` that TeX specifies should be used in place of the null delimiter.  We identify a null delimiter as one whose width is 0 (easy first check that will rule out most delimiters), whose text is blank, show TeX class is OPEN or CLOSE, and that has an explicit `fence` attribute (which will have come from the `\left..\right` processing).  We add the extra `nulldelimiterspace` to the box on the right.
Resolves issue mathjax/MathJax#985

Add nulldelimiterspace for null delimiters.  (mathjax/MathJax#985)

---

ts/input/tex/ColumnParser.ts
ts/input/tex/base/BaseItems.ts
ts/input/tex/base/BaseMethods.ts
ts/input/tex/colortbl/ColortblConfiguration.ts
ts/output/chtml/Wrappers/mtable.ts
ts/output/common/Wrappers/mtable.ts
ts/output/svg/Wrapper.ts
ts/util/Styles.ts

This PR allows tables to have frames where some sides are dashed rather than solid.  In the past, if all four sides of the table frame were included, they all had the style of the left edge (solid or dashed).  If not all the sides where included, then they were all solid.  Now that border CSS styles are implemented in both output jax, we use dashed or solid borders when needed.  When all the borders are included and the same style, the `frame` attribute is used, as before.  If not all the sides are included, but they are all solid, we use the `menclose` element with the proper sides, as before.  Otherwise (mixed styles, or all are dashed but not all side are included), we use a new `data-frame-style` to record the styles.  These are converted to real styles in the common output jax.  The …

Properly handle arrays with dashed frame borders. (mathjax/MathJax#2972)

---

ts/output/chtml.ts

This CSS hack is no longer needed in v4.  See issue mathjax/MathJax#3023.

Remove Safari hack that is not needed with v4.  (mathjax/MathJax#3023)

---

ts/input/tex/ams/AmsConfiguration.ts

This PR removes backward-compatibility code from a previous version that would move the `multlineWidth` option to its new location in that version.  This is not needed for v4.

Remove backward-compatibility code from previous version

---

ts/core/MathDocument.ts
ts/core/MathItem.ts
ts/output/common.ts

This PR removes `lineWidth` from the `Metrics` object, since it is never used (it was targeted for line-breaking, but it turns out that it wasn't needed).
This will need documentation.

Remove lineWidth from the Metrics object, since it is never used.

---

ts/input/tex/ParseUtil.ts
ts/input/tex/base/BaseMappings.ts

This PR reduces multiple spaces to a single space in `\text{}` and other math-mode material, as would happen in actual TeX, and simplifies the definition of `\ ` (since TeX doesn't seem to break expressions at this space, it can be teated as a non-breaking space in math mode).

Handle multiple spaces in \text{}.

---

ts/core/MmlTree/MmlNodes/math.ts

The MathML spec says `math` elements can't be nested, so this PR adds that check to the `verifyTree()` tests.

Verify that math elements are not nested.

---

ts/core/MmlTree/MmlNode.ts

This PR adds a tooltip to the `merror` element that gives the full error message when short errors are being used.  This brings it in line with the "Math input error" and "Math output error" messages, which show the full message as a tooltip.

Add a tooltip for MathML verification short errors to show the full error.

---

ts/core/MmlTree/MmlNode.ts
ts/input/mathml/MathMLCompile.ts
ts/output/common/Wrapper.ts

Because the mathvariant is critical to the operation of the output jax, having an incorrect math variant will lead to "Math output error" messages.  This PR adds checks within the MathML input jax and the common output jax to make sure that the variant exists in the output font in use.  This allows the output to be produced, but still gives the user information that something is wrong.

Add checks for valid mathvariant

---

ts/input/tex/base/BaseConfiguration.ts

This fixes a bug introduced by #900 where the `mathvariant` for unmapped characters in ranges that specify a variant wasn't being used.  This was due to missing parentheses that cause the `||` to be part of the hypothesis for the `?` rather than the `?:` structure being the second argument for `||`.
This prevented Chinese characters from being rendered in normal variant, for example.

Fix mathvariant bug introduced by #900

---

ts/output/chtml.ts
ts/output/common.ts
ts/output/svg.ts

Normally, when an expression has equation numbers or tags, the `mjx-container` gets a minimum width wide enough to hold the equation with its numbers (to prevent the numbers from overlapping the equation).  But when the `overflow` attribute is `scroll` or `truncate`, we don't want the minimum width.  This PR moves the settings for scroll and truncate into CSS and overrides the `min-width` in that case.

Move handling of scrolling to CSS and allow tagged expressions to scroll

---

components/bin/build

This PR fixes a problem with the `prefix` option added in commit d34a9bb by making sure the prefix is included in the directory path when the `lib` files are created.

Properly include prefix in build paths

---

ts/input/mathml/mml3/mml3.ts

This PR addresses a problem with WebKit/Blink browsers where MathML that contains `&#xA0;` fails to be processed by the XSLT transform used by the `mml3` extension.  The issue seems to affect parsing of HTML, but not XML, so the solution seems to be to convert the HTML to XML.  But doing that converts `&#xA0;` to `&nbsp;`, which isn't parsed in XML, and so we also have to convert `&nbsp;` back to `&#xA0;` before parsing as XML.
I'm not sure if this is compatible with the new HTML-in-MathML extension, but since `mml3` is experimental, I think that is OK.  It is better to have this work on input that has `&#xA0;`.
Note that this PR also includes a change that if the transformation fails, the original MathML is used.
Resolves issue mathjax/MathJax#3030.

Convert to XML and replace &nbsp; to avoid WebKit bug. (mathjax/MathJax#3030)

---

package-lock.json
package.json

Some cleanup of package files:
* Removes merge conflict markers that must have been introduced when `post-linebreaks` was merged.
* Updates to version number to 4.0.0-alpha.1
* Updates `mathjax-modern-font` to new beta.2

Removes merge conflicts from package files.

---

ts/core/MmlTree/MmlNodes/mspace.ts
ts/input/tex/base/BaseItems.ts
ts/input/tex/base/BaseMethods.ts
ts/output/chtml/Wrapper.ts
ts/output/chtml/Wrappers/math.ts
ts/output/common.ts
ts/output/common/LinebreakVisitor.ts
ts/output/common/Wrapper.ts
ts/output/common/Wrappers/mspace.ts
ts/output/svg.ts
ts/output/svg/Wrappers/math.ts

This PR changes `\allowbreak`, `\goodbreak`, etc. to use `mspace` elements rather than `mo` elements, since `mo` can become embellished, which can cause strange behavior.  In particular since `mtext` elements are space-like (because they can sometimes be all spaces, but the spec doesn't make an exception for when they contain non-space characters), that means that `\text{abc}\break\text{def}` would produce `<mtext>abc</mtext><mo linebreak="newline"/><mtext>def</mtext>`, and that would be an embellished operator, and the break would occur *outside* the embellished operator, so *before* the first `mtext`.  That is not what most people would intend.  Using `mspace` avoids that problem.
This has been a perennial problem with how `mtext` is treated as space-like even it is not all space …

Use mspace for \allowbreak, etc., and fix issues with mspace breaking.

---

ts/output/chtml/FontData.ts
ts/output/chtml/Wrappers/TextNode.ts
ts/output/chtml/Wrappers/mo.ts
ts/output/svg/Wrappers/mo.ts

This PR improves the handling of multi-character assemblies for stretchy characters, mostly in CHTML output, but a small change in SVG.  It makes the horizontal and vertical stretchies work more consistently (horizontals used to be fake tables).  Now both are handled using extenders that are 100% (or 50% for assemblies with a middle piece like braces), with transparent borders of the proper size where the end pieces go.  The ends are in 0-height or width boxes and are positioned to overlap the borders properly.  When there is a middle piece, the two extenders are 50% width, and the borders have to cover half the middle piece (this wasn't being properly handled before).
For CHTML, if a combining character is used in the assembly, we run into the issue with some browsers handling …

More reliable handling of stretchy assemblies

---

ts/output/common.ts

This PR removes the `force break` property that SVG uses to manage in-line line breaks so that when switching from SVG to CHTML, we don't get unwanted line breaks.
To test, use an in-line expression with potential line breaks using SVG output and use the menu to switch to CHTML.  Without this PR, the CHTML in-line expression will have forced breaks at each potential break.  With the PR, it should render properly in CHTML.

Remove forced breaks that SVG inserted when switching to CHTML

---

ts/input/tex/ParseMethods.ts
ts/input/tex/ams/AmsConfiguration.ts
ts/input/tex/ams/AmsMethods.ts
ts/input/tex/base/BaseConfiguration.ts
ts/input/tex/base/BaseMethods.ts

This PR fixes a conflict with the usage of `multiLetterIdentifiers` between `\operatorname` and font-changing macros like `\mathsf`.  The solution is to preserve the `multiLetterIdentifiers` value if it exists when the font changes, so that an outer `\operatorname` setting will be inherited by an inner font change.
I've also added a check for a failing match of the `multiLetterIdentifiers`, though that really shouldn't happen (but did in this case because of the wrong pattern being used).
Resolves issue mathjax/MathJax#3038.

Handle dash during font-change in `\operatorname`. (mathjax/MathJax#3038)

---

ts/output/chtml/Wrappers/mfrac.ts
ts/output/chtml/Wrappers/mo.ts
ts/output/chtml/Wrappers/msqrt.ts
ts/output/common/FontData.ts
ts/output/common/Wrapper.ts
ts/output/common/Wrappers/msqrt.ts
ts/output/svg/Wrappers/msqrt.ts

This PR improves the handling of the `rule_thickness` and `surd_height` font parameters.  In the past, the `rule_thickness` was used where `surd_height` should be (TeX uses `rule_thickness` for both, but we allow them to be different), and the rule in fractions was not using `rule_thickness` since the MathML default for the `linethickness` attribute is `medium`, which was fixed at .06em.
Here, we modify the `length2em()` method of the `common/Wrapper.ts` to use the font's `rule_thickness` as the default for `medium` (and use percentages to get `thin` and `thick` values).  This allows `mfrac` to get the correct line thickness.  We also change the `msqrt` wrappers to use `surd_height` for the thickness of the line over the radicand.
It turns out that the results in CHTML is thinner than in …

Honor the rule_thickness and surd_height font parameters

---

ts/output/chtml/FontData.ts
ts/output/common.ts
ts/output/common/FontData.ts
ts/output/common/Wrappers/mo.ts

This PR changes the vertical spacing for horizontal stretchy assemblies.  In TeX, these have the height and depth of the extender character, but in MathML, they are the maximum height and depth of any character in the assembly.  MathJax implements the latter, but this makes things like `\overrightarrow` have more height and separation from the base than TeX does.  In the TeX fonts, some of the characters used for extenders have height/depth that is different from their inked area in order to adjust the spacing, but the fonts used in MathJax don't have that (though potentially it could be added by hand).
This PR adds a font parameter that controls how MathJax uses the extender height/depth versus the total assembly's.  Its value is a linear interpolation value between the two values, …

Vertical spacing for horizontal stretchy characters more like TeX

---

ts/output/common/Wrappers/scriptbase.ts

This PR fixes a problem where superscripts and subscripts aren't placed properly on an operator that has been stretched.  There is an example in the initial issue
Resolves issue mathjax/MathJax#3049.

Properly place super- and subscripts for stretched operators. (mathjax/MathJax#3049)

---

ts/output/chtml/FontData.ts
ts/output/chtml/Wrappers/TextNode.ts
ts/output/chtml/Wrappers/msubsup.ts
ts/output/common/FontData.ts
ts/output/common/Wrappers/TextNode.ts
ts/output/common/Wrappers/msubsup.ts
ts/output/common/Wrappers/scriptbase.ts
ts/output/svg/Wrappers/msubsup.ts
ts/util/BBox.ts

This PR fixes spacing issues with the `-tex-mit` pseudo variant used for `\mathit` and `\it` by adding italic correction information in a property `oc` (other correction) that is only used by the last character in a string of characters in that variant.  That is, `\mathit{office}` and `{\it office}` will have the italic correction only on the last letter rather than between every letter, as in `office`, where the spacing between the f's is too wide, for example.  This allows superscripts and subscripts to be placed properly after such characters (e.g., `\mathit{f}^0` used to be too close).
This PR also fixes an inconsistency with TeX's placement of super and subscripts when the base is multi-character.  In TeX, `{UU}_0^1` has the scripts vertically aligned above each other, whereas in …

Properly handle italic correction for -tex-mit, and for subscripts with multi-character bases

---

ts/input/tex/base/BaseItems.ts
ts/input/tex/base/BaseMethods.ts
ts/input/tex/braket/BraketItems.ts
ts/input/tex/braket/BraketMappings.ts
ts/input/tex/braket/BraketMethods.ts
ts/input/tex/physics/PhysicsItems.ts
ts/input/tex/physics/PhysicsMethods.ts

This PR modifies the braket and physics packages so that they properly handle `\over` constructs as the actual LaTeX packages do.  Although `\frac` is recommended, `\over` can still be used, and the current code for these packages doesn't handle that properly.  (For bracket, `\Set{a\over b}` includes braces around the a as well as the whole fraction, and for physics, `\sin(a\over b)` generates an error message about missing delimiters.)  This PR also fixes some spacing issues with `\Set`.
Because braket and physics use `BraketItem` and `AutoOpen` items that have `isOpen` set to `true`, they act as delimiters for `\over`, and need to take that into account.  Because `\over` works by collecting the current node list from the preceding open `StackItem` using its `toMml()` method, and saving …

Properly handle \over within braket and physics packages. (mathjax/MathJax#3000)

---

ts/core/MmlTree/MmlNodes/mo.ts

This PR prevents `` ` ``  from being translated to U+2035 so that `\grave` accents work properly.

Don't remap U+0060 to U+2035 so \grave works properly

---

ts/output/chtml/Wrappers/munderover.ts
ts/output/common/Wrapper.ts
ts/output/common/Wrappers/munderover.ts
ts/output/common/Wrappers/scriptbase.ts
ts/output/svg/Wrappers/munderover.ts

This PR adjusts how some accents are placed.  The skew values stored in the font are used to move an accent to its proper position over a base character (e.g., to move the accent over the point in *A* rather than over the center of the width of the *A*).  These values re being taken from the Opentype MATH table accent data, but that table specifies that both the base skew and the accent skew should be used (these two skewed positions are to be aligned).  But currently, MathJax only uses the base skew.  This PR adds the ability to use the accent skew as well.  It also fixes an error where the skewed position for the top accent was also used for the bottom character in `munderover` causing the bottom to the improperly shifted to the left.
his makes it possible to resolve issue …

Update use of skew values from accents to allow better placement. (mathjax/MathJax#3051)

---

ts/input/tex/textmacros/TextMacrosConfiguration.ts
ts/input/tex/textmacros/TextParser.ts

This PR fixes a memory leak that occurs when the `textmacros` extension is used.  It was caused by not clearing the node lists that are part of the `ParseOptions` object, and not removing the parsers from the `parsers` list when they are done.  That means these will continue to build up over time.  We fix the problem by clearing these lists when the `mml()` function is called, and clearing the configuration itself when `internalMath` first starts parsing text-mode material.
In addition, since we are using a separate `ParseOptions` object, and the node lists are stored there, the nodes created for text elements are not being added to the main `TexParser` node lists, so we add code to copy the lists over from our parser to the parent TeX parser.
Resolves issue mathjax/MathJax#3061.

Fix memory leak in textmacros package.  (mathjax/MathJax#3061)

---

package-lock.json
package.json
ts/ui/menu/mj-context-menu.ts

This PR replaces #963 since it had file conflicts due to the ES6/ES5 updates.  Here we are updating the mj-context-menu to version 0.9.0.

Update mj-context-menu to 0.9.1

---

ts/output/common/Wrappers/mrow.ts

This is a fix for the bussproofs issue that occurs during abstract bounding box computation. The problem here is that some of the `mrow` elements introduced for measuring width will not have a parent. So I introduced two guards for methods that throw errors otherwise.
I assume setting `isStack` to `true` is reasonable, as for the time being, we don't really want line breaking in proof tree expressions.

Fix bussproofs

---

ts/output/chtml.ts
ts/output/chtml/Wrapper.ts
ts/output/chtml/Wrappers/mrow.ts
ts/output/common.ts
ts/output/common/Wrapper.ts
ts/output/common/Wrappers/mrow.ts
ts/output/svg.ts

This PR allows `mrow` nodes that were added by SRE to include in-line line breaks, so that TeX output will work as expected even after enrichment.  For example,
```
\(f(x+y+z+x+y+z+x+y+z+x+y+z+x+y+z+x+y+z)\)
```
should allow line breaks when it appears in a container with a small width.
We also fix some problems with SVG output when the top-level element is an `mstyle` or `semantics`, as in
```
\(\large x+y+z+x+y+z+x+y+z+x+y+z+x+y+z+x+y+z\)
```
When an `mstyle`, `semantics`, or `mrow` with `data-semantics-added` is encountered during in-line break processing, it is marked with the `inline-breaks` property, and that is used in CHTML output to add an attribute that is used to set `display: inline` in the CSS so that the breaks will be able to take effect (the default `inline-block` doesn't …

Allow inline-breaking within top-level nodes added by SRE

---

components/mjs/node-main/node-main.js
components/root-pack.js
components/webpack.common.cjs
components/webpack.config.cjs
components/webpack.config.mjs
package-lock.json
package.json
ts/components/cjs/root.ts
ts/components/mjs/root.ts
ts/components/version.ts
ts/input/mathml/mml3/cjs/xsltFilename.ts
ts/input/mathml/mml3/mjs/xsltFilename.ts
ts/output/svg/Wrappers/zero.ts
ts/ui/menu/mj-context-menu.ts
ts/util/asyncLoad/esm.ts

This PR includes several changes needed for version 4.0.0-beta.3.  These fixes include:
* Using the correct root path for webpacked node-main.js (for when you use `require("mathjax")` or `import "mathjax"` or the same for `mathjax-full`.
* Replacing `mjs/root.js` in the webpacked combined configuration files with a new `components/root-pack.mjs` that does the same thing as `__dirname` does in CommonJS webpacking (it replaces it with the directory `/`).  This is not ideal, but it prevents the inclusion of the directory name where the webpacked file was created (e.g., `/home/travis/mathjax/MathJax-src/...`).  The v3 versions had a broken default directory in node as well, so this is no worse than in the past.
* Fixing some comments (in particular some copyright dates that should not have …

Update version to beta.3

---

ts/input/tex/textmacros/TextParser.ts

This PR fixes a problem introduced by a last minute change in respond to PR review where I didn't change `keys()` to `entries()` as I should have, and apparently failed to test the result.  Argh!
Resolves issue mathjax/MathJax#3082.

Fix bug with \text{} in textmacros package. (mathjax/MathJax#3082)

---

ts/input/tex/ams/AmsMethods.ts
ts/output/chtml/Wrappers/mtable.ts

This PR fixes a problem with the `multline` environment where it was incorrectly getting a frame.  That was due to changes with how the `frame` attribute was being handled, and the fact that I had used an empty `frame` attribute to add the `framespacing` without a frame.  That was a misuse of the `frame` attribute, which I knew would come back to bite me, and now it did.
The fix is to change `multline` to use `data-array-padding` instead of `framespacing` for the spacing.  This also requires a fix in the CHTML output to properly handle that change as well.
Resolves issue mathjax/MathJax#3083.

Remove incorrect frame from multline environment. (mathjax/MathJax#3083)

---

ts/core/MmlTree/MmlNodes/mpadded.ts

This PR fixes the spacing before `\vcenter`, `\vtop`, and `\vbox` macros.  The problem was that the previous element's class wasn't being properly recorded, so nob spacing was being computed for it (the TeX spacing is based on the TeX classes of adjacent pairs of nodes).
Resolves issue mathjax/MathJax#3085

Fix spacing before \vcenter, \vtop, \vbox.  (mathjax/MathJax#3085)

---

ts/output/svg/Wrapper.ts

This PR removes the code that adds `mjx-linestrut` node to embellished operators in SVG output for in-line math with line-breaks allowed.  It seems to have been left over when copying the CHTML output `toEmbellishedCHTML()` to make the SVG version.
Resolves issue mathjax/MathJax#3087.

Remove errant mjx-linestrut from SVG output. (mathjax/MathJax#3087)

---

ts/input/tex/base/BaseMethods.ts

This PR fixes an incorrect error message about nested environments whenever the `equation`, `displaymath`, or `math` environments are used.  There were two calls to `parser.Push(begin)` in
https://github.com/mathjax/MathJax-src/blob/49db078a876cce1f2157c9c58fb98bb145a09068/ts/input/tex/base/BaseMethods.ts#L1709-L1722
but the first was supposed to have been removed:
https://github.com/mathjax/MathJax-src/commit/7bb5fbd541c88234eae9092e0f075f3eadf2219b#diff-8b54d4a07ba56e1e6678245687ace65d468dd87cb4c8770a11b261c94d0231a0
Not sure how it got restored (maybe a bad merge or merge conflict resolution).  In any case, the first one needs to be removed, as it forces the "Erroneous nesting" message to be produced whenever `\begin{equation}...\end{equation}` is used (and also affects the …

Fix incorrect flagging of nested environments. (mathjax/MathJax#3070)

---

components/mjs/node-main/node-main.js

This PR adds the default font to the default configuration for `node-main` so that when an output jax is loaded, it will load the default font automatically (rather than the "no-font" that is built into the `input/chtml` and `input/svg` components).  This allows you to do
``` js
require("mathjax-full").init({loader: {load: ['input/tex', 'output/svg']}}).then(...)
```
without having to include configuration for the font by hand.  You can still override the font by setting the `loader.paths` and `output.font` values in the argument to `init()` if you want to use a different font.

Include default font configuration so that it will be loaded when input/chtml or input/svg is loaded

---

ts/input/tex/ColumnParser.ts

This PR implements the `*{n}{...}` column specifier for use in array environment preambles.   It repeats the columns given in the second argument the number of times specified in the first argument.
Resolves issue mathjax/MathJax#3090.

Add support for *{n}{...} in array preamble.  (mathjax/MathJax#3090)

---

ts/input/tex/base/BaseItems.ts

This PR fixes a problem with the `align` and similar environments where if a second set of aligned columns are used, then initial minus signs (and other operators) will be treated as infix rather than prefix operators.  This is because the additional empty `mi` nodes are being inserted for all columns but the first one.  The fix proposed here is to not insert for right-justified columns (which will be the ones that start the second or later set of alignments).  We can't use the column number itself, since `align` repeats after two columns, while `eqnarray` repeats after 3.
Resolves issue mathjax/MathJax#3089.

Don't insert <mi/> on right-aligned columns.  (mathjax/MathJax#3089)

---

components/bin/build
components/bin/pack
components/webpack.common.cjs

This PR makes minor changes to the build tools so that they work better for third-party extensions.
The first change makes the build command have a better default for the `ts` directory (is it now next to the `js` directory, no matter what its name is).
The changes to `pack` produce better results for the file list when packing a file (the `[build]` files, which are the ones from the actual extension, will be at the top of the list, and the `[js]` will now be applied to file even if they are not in a mjs/cjs directory.
The change to `webpack.common.cjs` makes sure that *all* references to `mathjax-full/js` are remapped to the appropriate mjs/cjs version (without this, some were not getting caught, causing unwanted mathjax files to be included in the final packed file).
Resolves some issue …

Improve build tools for use with third-party extensions.  (mathjax/MathJax#3086)

---

ts/core/MmlTree/MmlNodes/mo.ts
ts/core/MmlTree/OperatorDictionary.ts
ts/input/tex/base/BaseConfiguration.ts

In version 2, an `mo` with multiple letters, like `<mo>Hom</mo>`, would be given the TeX class of OP when it doesn't appear explicitly in the operator table.  This was lost in the v3 translation, and this PR reinstates that.  In addition, it refactors the code that does the checking, since it is used in two places (the `get texClass()` getter, and the `checkOperatorTable()` initialization routine.  It also adjusts the `getRange()` function in the `OperatorTable.ts` to always return a value.
The pattern used to identify a multi-letter operator is a property of the `MmlMo` object, so that it can be adjusted during initialization, if desired.
Resolves issue mathjax/MathJax#3095.

Set TeX class OP for multi-letter mo elements, as in v2.  (mathjax/MathJax#3095)

---

ts/output/common/Wrappers/msubsup.ts

This PR fixes a problem with the placement of `msubsup` scripts when when the depth of either script is large.  The problem was due to the `getU()` method using `this.scriptChild`, where `sciptChild` was always set to `childNodes[1]`; for `msubsup` nodes, it should be `childNodes[2]`, the superscript.  The solution is to override `scriptChild` in the `CommonMsubsupMixin` wrapper.  (I also cached the superscript depth and subscript height values that are used in several places).
The issue would show up if the superscript has large depth, as in 
```
$$\int_0^{\Rule{3pt}{0pt}{20pt}}$$
```
which produces
or if the subscript has large depth, as in
```
$$x_{\Rule{3pt}{0pt}{20pt}}^2$$
```
which produces
With this PR, both produce the proper results:
Resolves issue mathjax/MathJax#3097.

Use superscript for scriptChild in msubsup.  (mathjax/MathJax#3097)

---

ts/output/common/Wrappers/scriptbase.ts

This PR fixes a problem where super- and subscripts were not placed properly on the results of `\vcenter`, `\vbox`, and `\vtop` elements.  These are implemented using `mpadded` nodes with `data-vertical-align` attributes and a `vbox` property to mark them as vboxes.  The problem is that the `getBaseCore()` method should stop at an `mpadded` element being used as a vbox, but was continuing down into it incorrectly if there was only one child element.  The fix is to stop when the `mpadded` has the `vbox` property.
Resolves issue mathjax/MathJax#3091.

Propery handle placement of scripts on \vcenter, \vbox, and \vtop (mathjax/MathJax#3091)

---

ts/components/global.ts

This PR resolves a problem that occurs when `combineConfig()` or `combineWithMathJax()` are used to merge an object into the `MathJax._` object and the item to be set is already set and has a getter.  This occurs due to the way exports are handled in ESM modules, where the exports are in an object each with a getter (so that they can't be modified, as imports are supposed to be immutable).  That didn't seem to be the case for the CJS components we used to use.  As a consequence, changing the renderer now causes an error since both the CHTML and SVG components include the common output code, and both set the properties of `MathJax._.output.common`, which are all getters.  This produces errors.
Resolves the console error issue from mathjax/MathJax#3098.

Prevent setting a propery that has a getter.  (mathjax/MathJax#3098)

---

ts/output/chtml/Wrapper.ts
ts/output/common.ts

This PR fixes a problem with CHTML output where in-line expressions with explicit line breaks could end up with extra vertical space at the explicit break if the part after it starts with an operator and is too wide for the container.  To do with, we mark the nodes with explicit linebreaks, and if we are just after an explicit line break, we don't mark an operator as breakable (preventing an extra line break from occurring right after an explicit one).  In the CHTML output, we don't insert breakpoints before explicit linebreaks (preventing an extra line break from occurring before that).
A test case is to use 
``` html
<div style="width:5em; border: 1px solid black">
\(a + \text{bbbbbbbbbbbbbbbbb} \\ = \text{cccccccccccccccc} + d\)
</div>
```
to see that there are no extra blank lines in …

Don't include extra linebreak positions after an explicit break.

---

components/bin/link-full
components/mjs/fullpath.cjs
components/webpack.common.cjs

This PR resolves the problem where the webpacking failed when building the cjs bundle without having first build the mjs files.  It was due to the `webpack.common.cjs` file using `require.resolve()` command to get full path names; since `webpack.common.cjs` is in the `components` directory, it was using the main `package.json` file, and so the pseudo-packages like `#js` were resolving to the `mathjax-full/mjs` direcrtory rather than the `mathjax-full/cjs` directory.
This resolves the problem by moving the `fullPath()` function to a separate `fullpath.cjs` file in the `components/mjs` and `components/cjs` directories, so that the cjs file will use the `components/cjs/package.json` mappings instead.
It also adds a test to the `link:full` script to only make the link if it is not already …

Fix make-cjs-components script to work without mjs files being built first

---

components/bin/build
components/bin/makeAll
components/mjs/dependencies.js
components/mjs/output/util.js
components/webpack.common.cjs

All `substr` to `substring` rewrites are obvious here. Even the one on the `font` string.

Refactors substr to substring on component files.

---

ts/output/chtml.ts
ts/output/svg.ts

This PR fixes a problem with determining the width of text that is in a system font rather than in the MathJax fonts.  These come from `\text{}` then `mtextInheritFont` is true, or from error messages (when `merrorInheritFont` is true, which it is by default), or from characters that aren't in the MathJax fonts, like Chinese characters, or when a `font-family` is specified in a `\style{}` command or MathML `style` attribute.
You can't test this in the lab, as the issue only occurs when the math is typeset outside the DOM via `MathJax.tex2chtml()` or one of the other conversion functions, and then inserted into a container with a `font-size` that is other than 100%.

Better measuring of text that is in a native font rather than MathJax fonts

---

ts/components/startup.ts

This PR fixes a problem with `defaultPageReady()` where the typesetting could be done at the wrong time.  With this PR, it should be performed when the `then()` is triggered, whereas before it was done when the `defaultPageReady()` call was made (OOPS!).
Resolves issue mathjax/MathJax#3130.

Proper handling of typesetPromise in defaultPageReady. (mathjax/MathJax#3130)

---

ts/input/tex/unicode/UnicodeConfiguration.ts

This PR adds a check that the font name doesn't include semicolons in the `\unicode` macro.  This prevents extra CSS from being inserted into the styles for the resulting output.
Resolves issue mathjax/MathJax#3129.

Have \unicode check for illegal font name.  (mathjax/MathJax#3129)

---

ts/ui/menu/Menu.ts
ts/ui/menu/MmlVisitor.ts

This PR adds a menu option to remove the `data-latex` and `data-latexItem` attributes from the "Show Math As MathML" menu item, as these can get quite long, making it hard to see the MathML structure.  We also reorganize the Math Settings submenu to push the MathML filters into an additional submenu level.  Finally, we move the filtering of the SRE attributes into the `MmlVisitor` so the attributes are never added, rather than using a string replacement after the fact.

Add ability to not show latex attributes, and reorganize settings menu

---

ts/output/chtml/Wrappers/mo.ts
ts/output/common/Direction.ts
ts/output/common/FontData.ts
ts/output/common/Wrapper.ts
ts/output/common/Wrappers/mfrac.ts
ts/output/common/Wrappers/mo.ts

This PR changes the `DIRECTION` enum into a regular object, like all other constants.  This was the only enum that we used, and it apparently is a problem when `--isolatedModules` is used.  This also means we don't need the `DirectionVH` object from `ts/common/Wrappers/mo.ts`.
Resolves issue mathjax/MathJax#3114.

Make const enum into a regular object.  (mathjax/MathJax#3114)

---

ts/output/chtml/Wrappers/menclose.ts

This PR changes how CHTML handles the `longdiv` enclosure so that it doesn't need to use clipping paths.  Apparently Chrome for Android and iOS only implements `clip-path` in very recent versions, and so older versions show a full oval rather than use the right half used for the division symbol.  The solution is to break the half-oval into two parts: the upper and lower halves, and handle each separately.  Each half uses a rounded corner of 100% radius (rather than the 50% radius that was used for the complete oval), with two of the border edges set to `none`.

Update CHTML longdiv output to not require clip-path.

---

ts/input/tex/newcommand/NewcommandMethods.ts
ts/input/tex/newcommand/NewcommandUtil.ts

The current `disassembleToken()` and `assembleToken()` methods produce a new token whose attributes are `{}` when the original had `null` attributes.  This has implications for some tokens where the difference between these are important, as in the `mathchar7` function at
https://github.com/mathjax/MathJax-src/blob/ae389ded62763bb176f797b6bfbb5a997c42dba1/ts/input/tex/ParseMethods.ts#L156-L165
where line 157 provides a default attribute list when `math.attributes` is `null` (but not if it is an empty object).
This leads to the loss of the default attributes when a new control sequence is `\let` equal to one that uses `mathchar7`, as in 
``` latex
\let\percent=\%
\percent\%
```
where the result of `\percent` will be in italics, while `\%` will not.
This PR resolves the issue by actually …

Fix problem with let using attributes of {} when they should be null

---

ts/input/tex/ParseUtil.ts

This PR fixes several issues with the `keyvalueOptions()` utility's handling of braces and control sequences, and adds an extra parameter that controls whether it should do LaTeX3-style processing, or traditional processing.  
The current implementation doesn't handle some control sequences properly, in particular, `\{`, so,
``` js
keyvalueOptions('x = \\{');
```
with throw an error about a missing closing brace or extra open brace.  This PR fixes that issue with the addition of `case '\\'` in the `readValue()` function.
The current implementation doesn't always handle braces properly.  For example
``` js
keyvalueOptions('a = {{x}y}');
```
returns `{ a: "x}" }` rather than `{ a: "{x}y"}`.  This is due to thinking that there are two outer sets of braces to be removed, rather than only one …

Fix keyvalueOptions to process braces and backslahses better

---

ts/core/MmlTree/MmlVisitor.ts
ts/input/tex/TexParser.ts
ts/output/common/FontData.ts
ts/output/svg/FontData.ts

This PR fixes several problems with font extensions that define new font variants, and allows non-standard variants to round-trip through SRE without causing verification errors (now that we are checking `mathvariant` values in `MmlNode`).
Currently, the `ignore-variant` property is used to determine whether a node's non-standard `mathvariant` should produce an error message when used in MathML input, and non-standard variants can be specified using the `data-mjx-variant` attribute.  The presence of that attribute sets the `ignore-variant` properly when a MathML element is created by the MathML input jax, and the serialization of the node via `MmlVisitor` and its subclasses would add the `data-mjx-variant` attribute when `ignore-variant` is set.
In this PR, the `MmlVisitor` is modified to …

Fix font extension handling of extra variants, and handle those variants in enrichment.

---

ts/output/common/Wrapper.ts

This PR fixes a problem with the size of SVG elements for in-lin math when in-line line-breaking is enabled.  It fixes the determination of the node where the line breaking occurs by not descending into unbroken nodes.  The `bbox.start` was not being properly tested, so it would descending into a fraction, for example, and stop at its numerator, giving the wrong scaling factor when the `height` and `width` of the resulting SVG was set.
Resolves issue mathjax/MathJax#3135.

Don't descend into items that aren't broken when looking for the linebreak node.  (mathjax/MathJax#3135)

---

ts/a11y/semantic-enrich.ts
ts/core/MathDocument.ts
ts/ui/safe/SafeHandler.ts

When the document state is reset, the process bits should be reset for the actions that are for higher states.  This wasn't happening for the `attach-speech` bit in the `semantic-enrich` extension.  I did a check to make sure all the other bits are bing properly handled, and the `findMath` bit was not being recent properly, either.  Also, a `safe` bit was being allocated that was never used.  This PR fixes these three problems.
Resolve issues raised in a [user's forum post](https://groups.google.com/g/mathjax-users/c/7vrAnA7SMz0).

Clear process bits for findMath and attach-speech, and remove safe bit that isn't needed.

---

ts/ui/menu/Menu.ts

I just stumbled on this typo (mathjax/MathJax#3140) and thought that as it is so simple to fix I should submit it in a pull request. The change is: 
```diff
-...you can scall all the math...
+...you can scale all the math...
```

Fix typo in MathJax Help Modal

---

ts/input/tex/ParseUtil.ts
ts/input/tex/TexParser.ts

This PR fixes more issues with `keyvalOptions()`, and provides an option to `GetBrackets()` to allow matching of brackets within the argument, as is done in LaTeX packages like siunitx.
One problem was that `keyvalOptions()` was removing trailing spaces when when it shouldn't.  For example, `keyvalOptiouns('x = { }')` should produce `{x: ' '}` with a space, not an empty string or `true`.  Also, `keyvalOptions('x = \\ ')` should return `{x: '\\ '}` with a trailing space, not `{x: '\\'}`.  Finally, `keyvalOptions('x = {}')` should produce `{x: ''}` not `{x: true}`.
The changes to `removeBraces()` are to handle the issue with trimming the result inappropriately.  The changes to `readValue()` fix the handling of empty braces and braces containing just spaces.  It turns out the the `stopCount` …

More updates to keyvalOptions, and add GetBrackets() option to match brackets.

---

ts/adaptors/linkedomAdaptor.ts

This PR adds the missing `splitText()` method to the linkedom `Text` object, which we need since it is used to split the text around TeX and AsciiMath delimiters so that the math can be removed and replaced by the typeset math.

Add Text.splitText() method to linkedom.  (mathjax/MathJax#3134)

---

ts/input/tex/TexParser.ts

Fixes [MathJax issue #3120](https://github.com/mathjax/MathJax/issues/3120), by checking for the underscore command case.

Fixes issue https://github.com/mathjax/MathJax/issues/3120

---

ts/input/tex/ParseUtil.ts

This PR adds optional type checking and conversion to the `keyvalueOptions()` function.  Currently, the `allowed` argument gives an object that says what keys are allowed (ones with non-zero values in that object).  Here, we extend the use of the `allowed` object to provide data for type checking and converting the values of the given keys.
This is done through a new `KeyValueType` object that has `validate()` and `convert()` methods (and a name, for potential error reporting).  There is a `KeyValueTypeDefinition()` function that makes creating these objects easier, and a `KeyValueTypes` object that holds predefined definitions for the standard types (boolean, number, string) and some variations (integer, dimen, and `oneof()` that gives a collection of valid option for the string).  These …

Add ability to do typechecking and conversion on the values of key-value options

---

ts/input/tex/Stack.ts
ts/input/tex/braket/BraketConfiguration.ts
ts/input/tex/braket/BraketMethods.ts

This PR fixes a problem where the `BraketMethods.Bar()` function doesn't find the enclosing `braket` item properly when there are certain types of enclosing elements (like style or color changes).
To do this, we add a function to the `Stack` object to get its current height (the number of elements on the stack), and save that in the `braket` item's `env` object, which will be available in the parser stack's `env` object.  Then the `BraketMethods.Bar()` function can use `parser.stack.env.braketItem` to find the matching `braket` item without having to look through the stack items to find it.  (The current approach doesn't work if there are intervening items other than an `over` item).
We also set the `braket` package priority so that it is searched before the `base` package, guaranteeing …

Update handling of braket bars so that the enclosing braket can be more accurately found. (mathjax/MathJax#3164)

---

ts/ui/lazy/LazyHandler.ts

This PR resolves a problem when the lazy typesetter is used with the assistive MathML extension and the initial typesetting is disabled with SVG output.  In that case, any math that is showing initially will get a bad `viewBox` for their `svg` element due to the fact that the metrics for the surrounding font haven't been computed.  We fix this by checking whether the metrics are available and setting the state to before the measuring of metrics in that case.
Resolves issue mathjax/MathJax#3167.

Make sure math item have their metrics set before lazy typesetting.  (mathjax/MathJax#3167)

---

ts/output/common/LineBBox.ts
ts/output/common/Wrappers/mspace.ts
ts/output/svg.ts

This issue fixes several issues with in-line line breaking in SVG mode that arise when extra spacing is placed around operators, as is done by `\implies`, or `A\;+\;B`, for example.  When in-line breaks are allowed, SVG output will lose the spacing around the operator (both the extra spacing as well as the normal operator spacing).
Both issues are cause primarily by the `computeLineBBox()` function for the SVG `mspace` wrapper.  The size of the space was lost because the width was not being added to the `LineBBox`, and the operator spacing was lost because the `isFirst` property was assuming that the mspace had no width (i.e., was used for line-breaking only).
I also moved `* scale` inside a conditional since there is no need to multiply 0 by the scale.
The `LineBBox.append()` is modified …

Fix issues with line breaks and spacing in SVG output. (mathjax/MathJax#3166)

---

ts/components/startup.ts
ts/ui/menu/Menu.ts

If the MathJax configuration includes `startup {typeset: false}` and also has menu settings that require loading extensions (e.g., if assistive-mml is on) or the user has set the menu so that something needs to be loaded (e.g., the renderer has been changed in the contextual menu), then the math will be typeset despite the `typeset: false` setting (because the Menu code will think a pre-render is necessary because of the menu settings).
This PR adds a `rerenderPromise` to the `ts/components/startup.ts` file that is initially `null` (meaning no typesetting has occurred), and is set to the `MathJax.startup.promise` once typesetting has been requested.  That lets the menu code determine if a re-render is needed (i.e., typesetting has already occurred), and gives it a promise to use to queue …

Fix menu to not rerender if no typesetting has occurred.  (mathjax/MathJax#3167)

---

ts/output/svg.ts

This PR adds the `xmlns` attribute to the `svg` element used for the global font cache.  This is needed in XHTML output for the links to the global definitions to work properly.
Resolves issue mathjax/MathJax-demos-node#58.

Add xmlns for global cache svg element.  (mathjax/MathJax-demos-node#58)

---

ts/adaptors/lite/Parser.ts

This PR fixes two problems with the LiteDOM `serializeXML()` method.  It protects `<` and `>` in attributes, which is not needed for HTML, but is for XHTML, and it adds namespaces for `html`, `svg`, and `math` elements, if they don't already have one.
Resolves an issue from mathjax/MathJax-demos-node#58.

Update LiteParser's serializeXML.  (mathjax/MathJax-demos-node#58)

---

ts/input/tex/ParseUtil.ts

This PR fixes the index being used when `\U{...}` has been found so that it is at the correct location to continue processing.  Without this, two occurrences of `\U` in a row will not process the second one.  E.g., `\text{\U{61}\U{62}}` would produce `a\U{62}` rather than `ab`.

Fix processing of \U{...}.

---

ts/input/tex/base/BaseMappings.ts
ts/input/tex/physics/PhysicsMappings.ts

This PR moves the `\divsymbol` mapping from the `base` package to the `physics` package, where it comes from in actual LaTeX, and adds `\divisionsymbol` as well.  It looks like the LaTeX `physics` package uses `\divisionsymbol`, while `physics2` uses `\divsymbol`.
Resolves issue mathjax/MathJax#3173.

Move \divsymbol to physics package and add \divisionsymbol. (mathjax/MathJax#3173)

---

ts/a11y/SpeechUtil.ts
ts/a11y/complexity/collapse.ts
ts/a11y/explorer.ts
ts/a11y/explorer/ExplorerPool.ts
ts/a11y/explorer/KeyExplorer.ts
ts/a11y/explorer/Region.ts
ts/a11y/semantic-enrich.ts
ts/a11y/speech/GeneratorPool.ts
ts/a11y/speech/SpeechMenu.ts
ts/a11y/speech/SpeechUtil.ts
ts/a11y/sre.ts
ts/ui/menu/Menu.ts
ts/ui/menu/MenuHandler.ts

PR introduces a `GeneratorPool` data structure that 
* coordinates the computation of speech. 
* takes care of async locale loading.
This makes the speech computation considerably cleaner. In particular there is no longer speech computation in the semantic enrichment method. Speech can be computed if the `speech="deep"` option is set. 
All Speech is now computed in the `attachSpeech` method, where originally only the `aria-label` was set. 
Since the `attachSpeech` state is called after rerender, this also takes care of computing speech for the collapsed elements etc. 
Another side effect is that we no longer use the walkers provided by SRE, which makes syncing a lot easier. At the moment only the walking and summary functionality is ported. The rest will be ported in a subsequent PR. …

Introduces a speechgenerator pool

---

package.json
pnpm-lock.yaml
ts/a11y/explorer/KeyExplorer.ts
ts/a11y/semantic-enrich.ts
ts/a11y/speech/GeneratorPool.ts

PR contains some corrections.
* Builds the correct speech string from the SSML also for the `mjx-container` element's `aria-label`.
* No speech is computed when `enableEnrichment` is set to `false`. Also catches error on speech computation when `enableEnrichment` is `true` but the element is actually not enriched. I think this currently only happens in the lab or when an enrichment error is caught.
* Adds missing `enableBraille` option.

Fix and catch speech computation errors, add missing braille option

---

ts/input/tex/require/RequireConfiguration.ts

When `\require{}` is used to load an extension, then if the extension has preprocessors, that means the the expression needs to be re-typeset so that the preprocessors will be run.  This is handled by calling `mathjax.retryAfter()` during the `RegisterExtension()` function.
If the extension has other extensions as dependencies, then they may also cause re-typesetting if they have preprocessors.  That means the `RegisterDependencies()` function may throw a `retry` error, which stops the processing of the dependencies, and prevents the remainder of the `RegisterExtension()` function from completing.
This occurs, for example, when `\require{textcomp}` is processed, as `textcomp` depends on `textmacros`, and the latter has preprocessors, so `retryAfter()` is called when the `textmacros` …

Fix \require to properly handle retries in dependencies.  (mathjax/MathJax#3170)

---

components/mjs/input/tex/extensions/dsfont/config.json
components/mjs/input/tex/extensions/dsfont/dsfont.js
ts/input/tex/dsfont/DsfontConfiguration.ts

Implements the [`dsfont` package](https://ctan.org/pkg/doublestroke)
Requires the `dsfont` from https://github.com/mathjax/MathJax-fonts/pull/2

Adds the dsfont package.

---

ts/input/tex/mathtools/MathtoolsMethods.ts

This PR fixes an issue with the `mathtools` package's paired delimiter implementation.  The used to have the default class of  `INNER`, but now they have class `OPEN` and are followed by an empty item of class `CLOSE`, so the stretchy delimiters now act like regular open and close delimiters, but are stretchy.
Resolves issue mathjax/MathJax#3183.

Make stretchy paried delimiters not be class INNER.  (mathjax/MathJax#3183)

---

ts/input/tex/textmacros/TextMacrosMappings.ts

Adds Angstrom, vdots and ldots macros. Those work in LaTeX text mode, e.g., in `\hbox`, but not yet in MathJax.

Add missing commands to textmacros package

---

ts/input/tex/Stack.ts
ts/input/tex/StackItem.ts
ts/input/tex/TexParser.ts
ts/input/tex/ams/AmsMethods.ts
ts/input/tex/base/BaseConfiguration.ts
ts/input/tex/base/BaseItems.ts
ts/input/tex/base/BaseMethods.ts
ts/input/tex/color/ColorMethods.ts
ts/input/tex/extpfeil/ExtpfeilConfiguration.ts
ts/input/tex/mathtools/MathtoolsMethods.ts
ts/input/tex/newcommand/NewcommandMethods.ts
ts/input/tex/require/RequireConfiguration.ts
ts/input/tex/setoptions/SetOptionsConfiguration.ts

This PR fixes an issue with how `_` and `^` interact with macros that don't push any content (like `\rm`).  In the past, something like `a_\rm{b}c` would not produce an error (as it should), but instead ended up with an `a` having an upright `b` subscript, followed by an upright `c`.  This is because `\rm` doesn't push any nodes onto the parser stack, and so the checking for the `_` is not performed until the next token, `{`, is pushed, and the `b` becomes the subscript.  Because `\rm` set the normal variant, that affects both the `b` and the `c` (and any following characters).  What *should* happen is an error message from the `_` concerning missing braces.
In addition, `a_\rm{b}c` would thrown a `math input error` in the `updateResult()` function, since it was being called before the …

Fix handling of _ and ^ followed by command that doesn't push content (mathjax/MathJax#3184)

---

ts/core/MmlTree/OperatorDictionary.ts
ts/input/tex/base/BaseItems.ts
ts/input/tex/base/BaseMethods.ts

This PR resolves the issues raised in mathjax/MathJax#3202, namely that primes are not placed properly on operators.  E.g., `\sum_n'` should act like `\sum_n^\prime` but doesn't.  The reason is that the `PrimeItem` and `BaseMethods.Prime` function don't treat `munderover` the same as `msubsup`, so this PR fixes that.
This also fixes the problem with `\int\limits'` not working like `\int\limits^\prime`.
It also fixes the problem with `\sum''` and larger numbers of primes not using the proper size in display mode.
Resolves issue mathjax/MathJax#3202.

Handle primes in munderover as in msubsup.  (mathjax/MathJax#3202)

---

ts/core/MmlTree/OperatorDictionary.ts

MathJax's handling of characters that aren't mapped to special functions (like `^` and `_`), or that match the variable or number patterns, is controlled by the `RANGES` and `OPTABLE` in the `OperatorDictionary.ts` file.  When an unmapped character is encountered, the `RANGES` array is searched for a block in which the unknown character is found, and that gives the TeX class and MathML node type to use for the character.
These blocks are just a rough breakdown of the unicode ranges into groups that should be treated similarly, but it is not perfect, and some characters are mischaracterized by it.  Two such are U+00D7 (×) and U+00F7 (÷), which are found in a block of Latin letters, which MathJax marks as TeX class ORD using an `mi` node.  These two *should* be treated as operators, but …

Allow unknown characters to use operator table to determine class and node type.  (mathjax/MathJax#3203)

---

ts/a11y/explorer/Region.ts

This PR makes the various regions be `display: none` when not in use, so that there are not small white "artifacts" floating around when they are not being used.
I've made the non-show versions be just `display: none`, and moved any needed CSS from there to the `_show` version.

Make non-shown regions be display:none

---

ts/input/tex/textcomp/TextcompConfiguration.ts
ts/input/tex/textmacros/TextMacrosConfiguration.ts

This PR causes the `textcomp` package to add itself to the `textmacros` packages automatically.  In order to allow it to work with `\require{textcomp}` (and to work better with the Lab), we do this through the `config()` function of the configuration rather than setting it via `options`.  This is because when `\require{textcomp}` is processed, its dependecies are loaded and added to the configuration first, then `textcomp` is added.  Because `textmacros` is a dependency, it will be added and configured *before* `textcomp` adds to the `textmacros.packages` if it is placed in the `options.textmacros.packages` configuration option.  Here, using `config()`, we know that `textmacros` will already be configured, so we can add to the `textConf` configuration directly.
It may be possible to have …

Make textcomp package register with textmacros automatically.

---

components/mjs/input/tex/extension.js
components/mjs/input/tex/extensions/bbm/bbm.js
components/mjs/input/tex/extensions/bboldx/bboldx.js
components/mjs/input/tex/extensions/dsfont/dsfont.js
ts/input/tex/bboldx/BboldxConfiguration.ts
ts/output/chtml.ts
ts/output/chtml/FontData.ts
ts/output/common.ts
ts/output/common/FontData.ts

This PR makes the changes needed to the font extension infrastructure to allow a TeX font package to be loaded via `\require` (e.g., `\require{dsfont}`) and have it load the needed font.
The `components/mjs/input/tex/extension.js` file exports a function that does the work of loading and adding a font extension, simplifying the `dsfont`, `bbm` and `bboldx` component files.  This sets up the needed path for the extension, and the load hook that loads the font extension and adds it into the output jax when it is loaded.
To do this, the common output jax gets a new `addExtension()` function that looks up the font extension and adds it to the current font for that output jax.  The chtml output jax overrides this so that it can add the needed CSS rules to load the fonts needed for the …

Make tex font packages work with \require

---

components/bin/build
components/mjs/a11y/explorer/config.json
components/mjs/a11y/explorer/explorer.js
components/mjs/a11y/semantic-enrich/config.json
components/mjs/dependencies.js
components/mjs/ui/menu/config.json
ts/a11y/explorer.ts
ts/a11y/explorer/ExplorerPool.ts
ts/a11y/explorer/KeyExplorer.ts
ts/a11y/semantic-enrich.ts
ts/a11y/speech/SpeechMenu.ts
ts/ui/menu/MJContextMenu.ts
ts/ui/menu/Menu.ts
ts/ui/menu/MenuHandler.ts

This PR implements the new menu structure that we discussed over the last few developer meetings.
While updating the menus, we also normalize how the settings are handled, so that the `enableSpeech`, `enableBraille`, `enableEnrichment` and `enableExplorer` document options control whether those actions are taken, and are controlled automatically by the menu settings.  When enrichment is enabled, the accessibility submenus are made active (and the `enable...` options are set to true).  This allows the explorer to run, and whatever settings are present in the `Speech`, `Braille`, and `Explorer` menus to take effect.  Those submenus control the `a11y` settings of the document's options (and the `menuOptions.settings` section, which is what initializes the `a11y` values when the menu code is …

Update MathJax contextual menus for assistive tools

---

components/bin/pack

This is a small PR to improve the output from the `components/bin/pack` command for reporting files included from the `node_modules` directory.  Since `pnpm` uses symbolic links, the filenames reported are not as concise as they could be.  This alters the regex pattern used for the `[node]` prefix to collapse `.pnpm` links for shorter file names.

Handle pnpm node_module paths better in [node] prefix in messages

---

ts/ui/menu/MmlVisitor.ts

This is a small PR to remove the `aria-owns` attributes from SRE when SRE attributes are being filtered from the MathML output in the "Show Math As" menu.

Filter aria-owns attributes from SRE

---

components/bin/build
components/mjs/a11y/explorer/config.json
components/mjs/a11y/explorer/explorer.js
components/mjs/a11y/semantic-enrich/config.json
components/mjs/dependencies.js
components/mjs/ui/menu/config.json
pnpm-lock.yaml
ts/a11y/explorer.ts
ts/a11y/explorer/ExplorerPool.ts
ts/a11y/explorer/KeyExplorer.ts
ts/a11y/explorer/Region.ts
ts/a11y/semantic-enrich.ts
ts/a11y/speech/GeneratorPool.ts
ts/a11y/speech/SpeechMenu.ts
ts/ui/menu/MJContextMenu.ts
ts/ui/menu/Menu.ts
ts/ui/menu/MenuHandler.ts

These are the workarounds for the issues regarding voice events on Firefox.
@dpvc can you have a look if this works for Safari as well?

Fixes issues with firefox and safari.

---

ts/ui/menu/Menu.ts

This PR fixes several issues with the new menus (as discussed in our meeting today).
The first is switching the semantic enrichment on and off, which didn't turn on/off the speech and Braille.  This was due to now setting the `enableSpeech`, `enableBraille`, and `enableExplorer` values, which this now does in lines 941 and 942 of `Menu.ts` in the `setAccessibilityMenus()` function.  Some initialization was moved from the `initMenu()` function to `applySettings()` (old lines 687 to 689 moved to new 824 to 826, with old lines 837 through 837 being removed, as the `setAccessibilityMenus()` call now sets those values properly.
The `enableExplorer` in old line 1004 is not needed, as the `setAccessibilityMenus()` now handled that (new line 942).
Old lines 1019 and 1020 are adjusted to avoid …

Menu fixes

---

ts/output/chtml.ts

This PR fixes a problem with the width of text that is taken from a non-MathJax font when it is in a context where it is scaled in CHTML output.  For example, when `mtextInteritFont` is true,
``` latex
x_{\bbox[red]{\text{xxxxxxx}}}
```
will have an incorrectly sized red background in CHTML.  Other examples are
``` latex
\Large \bbox[red]{\text{xxxxx}}
```
``` latex
\textstyle \frac{1}{\bbox[red]{\text{xxxxx}}}
```
``` latex
\sqrt{\scriptstyle\bbox[red]{\text{xxxxx}}}
```
Resolves issue at the bottom of mathjax/MathJax#3194.

Correct width for unknown fonts in scaled text in CHTML (mathjax/MathJax#3194)

---

pnpm-lock.yaml
tests/length.test.js
ts/input/tex/ColumnParser.ts
ts/input/tex/ParseUtil.ts
ts/input/tex/TexParser.ts
ts/input/tex/UnitUtil.ts
ts/input/tex/ams/AmsMethods.ts
ts/input/tex/base/BaseItems.ts
ts/input/tex/base/BaseMethods.ts
ts/input/tex/bussproofs/BussproofsMethods.ts
ts/input/tex/bussproofs/BussproofsUtil.ts
ts/input/tex/mathtools/MathtoolsMethods.ts
ts/input/tex/mathtools/MathtoolsUtil.ts
ts/input/tex/newcommand/NewcommandMethods.ts
ts/input/tex/newcommand/NewcommandUtil.ts
ts/input/tex/unicode/UnicodeConfiguration.ts

The PR 
* refactors utility functions for units into a separate module. This resolves a circular dependency between `TexParser` and `ParseUtils`. Therefore also the `trimSpaces` function is moved to `UnitUtils` although it does not "topically" fit.
* rewrites `UnitMap` from an extension of `Map` to using an private `Map` property, to avoid problems with ES5.

Refactor Units computation into separate Utils

---

package.json
pnpm-lock.yaml
ts/a11y/explorer.ts
ts/a11y/semantic-enrich.ts
ts/a11y/speech/GeneratorPool.ts

This PR makes the changes we talked about face-to-face today.  I will make the version change to beta.6 when we are ready to release the new version.

Fix issues with GeneratorPool init() looping, and move some a11y options to semantic-enrich.  Add SRE dependencies.

---

ts/output/svg/Wrapper.ts

This PR fixes an issue with the handling of the width of characters that are not in the MathJax fonts in SVG mode that could lead to overlapping characters.  The SVG wrapper's `toSVG()` code has been reordered to make this work properly.  The handling of unknown characters has been moved to the top, and `if-then-else` has been broken into separate `if-then` with returns, with the width of previous unknown characters being taken properly into account (which was what wasn't being done).
This only affects text that is all in the same MathML node, so you can test using `\text{aaa 中文 bbbb}` for the `unknown` and `p` sections of the code.  To get a `c` test, you need to use the `mathjax-tex` font with `\text{aaa\U{220C}bbb}`.
Resolves issue mathjax/MathJax#3224.

Fix handling of unknown characters in SVG output. (mathjax/MathJax#3224)

---

ts/ui/menu/Menu.ts

This PR changes the serialization of SVG elements to use XML rather than HTML rules (so that the xml in the `data-semantic-speech` attribute is properly quoted).
Resolves issue mathjax/MathJax#3226.

Use XML serialization not HTML serialization for SVG images. (mathjax/MathJax#3226)

---

ts/core/MmlTree/MmlNodes/mo.ts
ts/core/MmlTree/MmlVisitor.ts
ts/input/mathml/MathMLCompile.ts
ts/output/common/Wrappers/scriptbase.ts

The `mathaccent` property is used to help produce accents that work more like TeX's accents, but it doesn't get serialized by `SerializeMmlVisitor` since the `mo` object itself sets this properly based on the accent being used (so that MathML will work like TeX without the need for extra data attributes).  So U+2192 (right arrow) get `mathaccent` set by default.  But macros like `\overrightarrow` set `mathaccent` to `false` to prevent them being treated like accents (since the TeX accents take up no horizontal space, whereas the right arrow can extend beyond its base and needs to take up space).  This setting of `false` is lost when we serialize the internal MathML for SRE and then parse it again.
This PR fixes that by having the `MmlVisitor` (the base class for `SerializedMmlVisitor`) …

Update handling of math accents to round-trip through SRE

---

ts/core/MmlTree/MmlNodes/mo.ts
ts/input/tex/base/BaseItems.ts
ts/input/tex/base/BaseMappings.ts
ts/input/tex/base/BaseMethods.ts

This PR fixes a regression introduced in #1069 in which primes are misplaced for `\underline{x}` and give an error about double superscripts for `\overline{x}` and similar macros.  This was du to not taking the `subsupOK` property in account for these `munder` and `mover` constructs.  We add those checks here.
Also, this fixes some non-critical number/boolean issues in the base mappings and macros.  It works the way it is, but the types are wrong, so we straighten that out here.
Resolves issue mathjax/MathJax#3233 and mathjax/MathJax#3234.

Fix regression from #1069 (mathjax/MathJax#3233, mathjax/MathJax#3234)

---

package.json

Fixes an oversight from PR #1100, that retains the `jest` directory name in the `test` lifecycle script.

Fixes incorrect lifecycle script for test

---

components/mjs/input/tex/extension.js
components/mjs/output/chtml/config.json
components/mjs/output/chtml/nofont.js
components/mjs/output/svg/config.json
components/mjs/output/svg/nofont.js
components/mjs/output/util.js
ts/components/loader.ts
ts/components/package.ts
ts/input/tex/require/RequireConfiguration.ts
ts/output/chtml.ts
ts/output/common.ts
ts/output/common/FontData.ts
ts/ui/menu/Menu.ts

This PR is for beta.6.
The addition of the new TeX packages that load various double-struck fonts has broken the previous separation of input and output jax.  There are some assumptions that relied on this separation, so these new TeX packages complicate things somewhat.  In particular, switching renderers when one of these packages has been loaded via `\require` would not necessarily retain the font in the new renderer.  Furthermore, because of the way the extensions hooked into the renderer changes, leading a second font extension would interfere with the loading of the first one when a renderer change occurred.
The component packages for these extensions tried to set things up overcome some of these complications, but were not completely successful.  So this PR includes changes to …

Allow tex packages that load font extensions to work better with \require and renderer changes.

---

ts/input/tex/ParseUtil.ts
ts/input/tex/bussproofs/BussproofsMethods.ts
ts/input/tex/textmacros/TextMacrosMethods.ts

Some cleanup for upcoming l10n efforts.
Some error messages are used multiple times, but differ in the actual message string. This PR corrects this. In particular:
* `IllegalUseOfCommand`: corrects its second use to reflect the actual error
* `MathNotTerminated` unifies message
* `Misplaced` unifies messages to a simple  `"Misplaced %1"`

Corrects Duplicate use of Error Messages

---

ts/a11y/explorer/KeyExplorer.ts
ts/a11y/semantic-enrich.ts
ts/a11y/speech/GeneratorPool.ts
ts/a11y/speech/SpeechUtil.ts
ts/ui/lazy/LazyHandler.ts

This is the PR that we discussed today in our meeting.  I have reworked the handling of the speech-generation loop using the idea I mentioned toward the end:  I record the return value from the `setTimeout()` command and use `clearTimeout()` to prevent the next iteration of the loop from running if the `attachSpeech()` render-action is called (e.g., the page is retypeset) while there are still MathItems waiting to be processed.  That turns out to be much cleaner, and you can even eliminate the `attachSpeechStart()` method along the way.  So I think these are good changes.
Just to have it in the record, this PR:
* Moves the `Timing` values to document options, where a page author can adjust them if needed.
* Changes the `setTimeout()` in the KeyExplorer to a direct call to `attachSeech()` …

Improve speech performance, especially for lazy typesetting

---

testsuite/tests/util/asyncLoad/esm.test.ts
testsuite/tests/util/asyncLoad/node.test.ts
testsuite/tests/util/asyncLoad/system.test.ts
ts/mathjax.ts
ts/output/common/FontData.ts
ts/util/AsyncLoad.ts
ts/util/asyncLoad/esm.ts
ts/util/asyncLoad/node.ts
ts/util/asyncLoad/path.d.ts
ts/util/asyncLoad/system.ts

This PR makes the various `asyncLoad` implementations (`node`, `esm`, and `system`) operate more consistently, and updates their tests.  In particular, relative file names are resolved using the `root` directory, while other names are used as is.  That allows using package names like `mathjax-full`, for example (at least in the implementation where that is possible).
In addition, there is a new flag that indicates whether the asyncLoad command is synchronous, use by the font's dynamic file loading command `loadDynamicFilesSync()` to determine if it can work or not.
There is also a fix to `FontData.js` that resolves a problem with having removed the `.js` from file names, which are needed by `asyncLoad()`.
The `asyncLoad/node.js` implementation is modified to be able to be used by both ESM …

Update the asyncLoad implementations to be more consistent, and update tests.

---

ts/input/tex/bussproofs/BussproofsMappings.ts
ts/input/tex/bussproofs/BussproofsMethods.ts
ts/input/tex/bussproofs/BussproofsUtil.ts

This PR fixes problems with the computation of the left- and right-hand width adjustments that are used to get the correct bounding box for the final proof table.  Currently, the left-hand adjustment can be too big, while the right-hand can be too small or too big.  This is true, for example, with this proof:
``` latex
$$\bbox[orange]{
\begin{prooftree}\AxiomC{}
\RightLabel{Ax}\UnaryInfC{p ⊢ p}
\AxiomC{}
\RightLabel{Ax}\UnaryInfC{¬p ⊢ ¬p}
\RightLabel{E→}\BinaryInfC{¬p, p ⊢ ⊥}
\RightLabel{I→}\UnaryInfC{¬p, p ⊢ ¬ ¬q}
\RightLabel{DNE}\UnaryInfC{¬p, p ⊢ q}
\RightLabel{I→}\UnaryInfC{¬p ⊢ p → q}
\AxiomC{}
\RightLabel{Ax}\UnaryInfC{(p → q) → p ⊢ (p → q) → p}
\RightLabel{E→}\BinaryInfC{(p → q) → p, ¬p ⊢ p}
\AxiomC{}
\RightLabel{Ax}\UnaryInfC{p ⊢ p}
\AxiomC{}
\RightLabel{Ax}\UnaryInfC{¬p ⊢ ¬p} …
```

Compute proper left and right adjustments for bussproof tables. (mathjax/MathJax#3251)

---

ts/output/common/Wrappers/mrow.ts

This PR fixes a bounding box computation for some embellished operators when inline breaking is enabled.  For example:
``` xml
<math xmlns="http://www.w3.org/1998/Math/MathML">
<mn>1</mn>
<mrow data-mjx-texclass="REL" mathbackground="red">
<mover>
<mo stretchy="false">&#x27F5;</mo>
<mi>a</mi>
</mover>
</mrow>
<mn>2</mn>
</math>
```
or 
``` js
1 \style{background-color: red}{\stackrel{a}{\longleftarrow}} 2
```
will show the wrong sized red rectangle in SVG output when in-line breaking is enabled.  This PR fixes that.
Resolves issue mathjax/MathJax#3250.

Fix bounding box computation for some embellished operators.  (mathjax/MathJax#3250)

---

ts/output/chtml/Wrapper.ts
ts/output/chtml/Wrappers/math.ts
ts/output/svg.ts
ts/output/svg/Wrappers/math.ts

This PF works around an issue with Safari where in-line line breaks aren't being honored.  It appears that Safari doesn't break at spaces that are in `content` CSS like all other browsers, so we add the space manually instead.
Resolves issue mathjax/MathJax#3252.

Fix inlkine breaking in Safari. (mathjax/MathJax#3252)

---

ts/a11y/semantic-enrich.ts
ts/components/startup.ts
ts/core/MathDocument.ts

This PR implements the ideas we discussed in our meeting yesterday:
* A new `renderPromises` array is added to the MathDocument that holds promises that are created by the render actions.
* The `typesetPromise()` function now waits for those promises to resolve before its own promise resolves.
* The `attachSpeech()` action now creates a promise that resolves when the speech loop completes so that `typesetPromise()` will wait for it to complete.
* A new `asynchronous` option is added to the `speechTiming` configuration object, initially set to `true`, that controls whether the speech is added synchronously or asynchronously.  (When set to `false`, the speech is added during the `renderAction` processing directly, which will be useful for node-based page preprocessing.)
In addition, a bug …

make typesetPromise() wait for speech to be attached, add synchronous option, and copy ARIA labels to internal MathML

---

ts/a11y/explorer.ts
ts/a11y/explorer/KeyExplorer.ts
ts/a11y/explorer/MouseExplorer.ts
ts/a11y/explorer/Region.ts
ts/a11y/semantic-enrich.ts

In the current incarnation of the explorer, the live regions and other regions associated with an expression are all created and appended to the document body when the expression is processed.  There are 6 such regions for each expression, so the number of these extra divs can get quite large, even for pages with only a moderate number of expressions.  Furthermore, these regions are created during a `convert()` call (like those used in `MathJax.tex2chtml()` or other conversion methods), even when the result is never put into the document DOM.  Finally, these regions are never removed from the page, even if the typeset expressions are removed.  For example, in the situation where an editor has a live preview and re-typesets the input as a user types it, even if the previewer correctly …

Create regions only when needed

---

testsuite/src/setupTex.ts
testsuite/tests/input/tex/Action.test.ts
testsuite/tests/input/tex/Ams.test.ts
testsuite/tests/input/tex/Amscd.test.ts
testsuite/tests/input/tex/Base.test.ts
testsuite/tests/input/tex/Bbox.test.ts
testsuite/tests/input/tex/Boldsymbol.test.ts
testsuite/tests/input/tex/Braket.test.ts
testsuite/tests/input/tex/Bussproofs.test.ts
testsuite/tests/input/tex/Cancel.test.ts
testsuite/tests/input/tex/Colorv2.test.ts
testsuite/tests/input/tex/ConfigMacros.test.ts
testsuite/tests/input/tex/Enclose.test.ts
testsuite/tests/input/tex/Extpfeil.test.ts
testsuite/tests/input/tex/Html.test.ts
testsuite/tests/input/tex/Mhchem.test.ts
testsuite/tests/input/tex/Newcommand.test.ts
testsuite/tests/input/tex/Noerrors.test.ts
testsuite/tests/input/tex/Noundefined.test.ts
testsuite/tests/input/tex/Physics.test.ts
testsuite/tests/input/tex/Tag.test.ts
testsuite/tests/input/tex/Unicode.test.ts
testsuite/tests/input/tex/Verb.test.ts

PR updates tests to work again after PR #1110 and #1115
* Configurations are included in the test files directly, that limits the actual code that is loaded (and not used) during tests.
* Busproofs tests are updated mainly wrt. to new spacings.

Tests cleanup after AllPackage removal.

---

ts/util/Styles.ts

This PR improves the handling of CSS styles, in particular the use of quotation marks and backslashes in CSS style values, and sanitizes CSS values when output as a string, avoiding a potential for CSS insertion.  It also replaces newlines by spaces to avoid some unusual parsing by browsers that newlines can cause.
The parsing of a CSS string now handles quoted material properly, and in the case that a value includes an unmatched quotation mark, one is appended to make sure they are matched.  When outputting a CSS value, the value is trimmed at the first unquoted semi-colon to avoid the possibility of having the value insert additional unexpected CSS rules.
I will make some tests for this in a separate PR.

Better validation of style values

---

.husky/pre-commit
.husky/pre-push
package.json
pnpm-lock.yaml

PR adds `git` hooks for `commit` and `push`. The hooks are run by [husky](https://typicode.github.io/husky/).  Currently the hooks are setup as follows:
1. `pre-commit` runs [lint-staged](https://www.npmjs.com/package/lint-staged) that applies lifecycle scripts to staged files, restages the files and commits. It blocks the commit if the lifecycle scripts fail or would result in an empty commit. Right now I have only added `pnpm format:fix`. Once the code base is fully linted we should also add `pnpm lint:fix`.
2. `pre-push` should run the test suite. But I've committed them out for the time being as this can be pretty annoying...

Add git hooks for commit and push

---

ts/a11y/speech/SpeechUtil.ts
ts/adaptors/NodeMixin.ts
ts/adaptors/lite/Document.ts
ts/adaptors/lite/Parser.ts
ts/components/loader.ts
ts/core/MmlTree/SerializedMmlVisitor.ts
ts/input/tex/TexError.ts
ts/input/tex/base/BaseMethods.ts
ts/input/tex/bbox/BboxConfiguration.ts
ts/input/tex/html/HtmlMethods.ts
ts/output/common/FontData.ts
ts/util/asyncLoad/system.ts
ts/util/string.ts

Remove superfluous slashes from all regular expressions. There is still one bizarre `escape character` error here:
```
ts/input/mathml/mml3/mml3.ts:691:13: Unnecessary escape character: \<. [Error/no-useless-escape]
```

Remove superfluous slashes in reg exps

---

ts/input/tex.ts
ts/input/tex/base/BaseItems.ts

This PR adds a counter to record array template substitutions and an option `maxTemplateSubtitutions` that is used to detect an infinite loop due to a template that includes something like `@{\\}`.  Because the count is incremented for any cell in a column that has a `@` or other similar substitution, the maximum count is set pretty high to accommodate large arrays, but can be configured to be larger in the document options if necessary.  I would have liked to have been able to detect this more directly, but I wasn't able to come up with another reliable method.
Resolves issue #1142.

Add a template substitution count to avoid infinite loop (#1142)

---

ts/core/Tree/Factory.ts
ts/input/tex/ParseMethods.ts
ts/input/tex/empheq/EmpheqUtil.ts
ts/ui/menu/Menu.ts
ts/util/FunctionList.ts
ts/util/Retries.ts

Rewrites all (but one) occurrences of the `Function` type to the correct types to resolve the [no-unsafe-function-type](https://typescript-eslint.io/rules/no-unsafe-function-type) error. Some of them are a catch all function types, of course.

Rewrite general Function type to concrete types

---

eslint.config.mjs
testsuite/tests/input/tex/Amscd.test.ts
testsuite/tests/input/tex/Braket.test.ts
testsuite/tests/input/tex/Physics.test.ts
ts/a11y/explorer/KeyExplorer.ts
ts/a11y/sre.ts
ts/core/MmlTree/MmlNodes/mo.ts
ts/core/Tree/Factory.ts
ts/input/tex/amscd/AmsCdMethods.ts
ts/input/tex/base/BaseItems.ts
ts/input/tex/braket/BraketMethods.ts
ts/input/tex/html/HtmlMethods.ts
ts/input/tex/mathtools/MathtoolsMappings.ts
ts/input/tex/physics/PhysicsMethods.ts
ts/output/common/FontData.ts
ts/output/common/Wrapper.ts
ts/output/common/Wrappers/mtable.ts

PR lints all issues with the exception of 
* rewriting the ES2015 module syntax
* `Unexpected aliasing of 'this'`
In particular it
* irons out the remaining missing jsdocs `@returns` errors,
* adding missing `return` statements
* adding missing `return` types
* adds a `eslint-disable` statements where really necessary
* removes empty blocks
* avoids linting in the `cjs` folder
* adds some tests for `amscd`, `braket`, `physics` as a consequence of the above
* adds complete set of tests for all macros in the `physics` package

Lints the trivial Rest

---

components/bin/package.json
components/mjs/node-main/node-main.js
package.json
ts/output/common/FontData.ts

This PR changes the default front from mathjax-modern to mathjax-newcm, which has more coverage and is slightly darker.  The lightness of mathjax-modern was one of the complaints with v4.
You need to do `pnpm install` to get the new font installed, and need the `lab-extension-update` branch in the `MathJax-dev` repository, and do `npm install` there as well, then relink `node_modules/mathjax-full` to your current `MathJax-src` repository.

Change default font to mathjax-newcm

---

ts/handlers/html/HTMLDocument.ts

This PR fixes a problem with the merging of MathLists when multiple input jax are used.  The index for the location (`start` and `end` objects of the `MathItem` object) were not being set, and so the sorting of math items was not being done properly.  This could lead to the indices within the text nodes containing the math being off when the DOM is updated, as the math is handled in the wrong order, and the text nodes are broken up, changing the character indices of the math that is out of order.
This PR includes indices that can be used to sort the lists properly, and resolves issue mathjax/MathJax#3301.

Improve merging of math lists (mathjax/MathJax#3301).

---

ts/input/tex/base/BaseMappings.ts
ts/input/tex/newcommand/NewcommandMethods.ts

This PR switches the order in which the `\let` command looks up macros and delimiters, so that something like `\let\xyz=\\` will make `\xyz` work as `\\` rather than produce a backslash (which is the delimiter tied to `\\`).  Also removes `\\` as a delimiter, as LaTeX doesn't actually allow that.

Have \let look up macros first then delimiters, and removes \\ delimiter

---

ts/components/startup.ts

Refactors the `Startup` namespace into an `abstract class`. It can't be turned into a `const` object as it contains a number of uninitialised elements. 
I followed the trickery at:
https://stackoverflow.com/questions/13212521/typescript-static-classes

Remove startup namespace

---

ts/core/MmlTree/MmlNode.ts
ts/core/MmlTree/MmlNodes/mo.ts
ts/core/Tree/Factory.ts

Removes all aliasing of `this` in the code.
Note, that the function in `Factory.ts` works because arrow functions preserve lexical scope.

Removes occurrences of aliased `this`

---

ts/a11y/explorer.ts
ts/a11y/explorer/KeyExplorer.ts
ts/a11y/explorer/Region.ts
ts/ui/menu/Menu.ts

This PR fixes a bunch of small issues with the explorer interface.
* It turns off the subtitles and Braille subtitles by default.  Currently, since the assistive tools are on by default, anyone clicking on an expression will get these showing up, and that will be a cause of confusion and questions about how to turn it off.  Since they are mostly for debugging and demonstration purposes, we can turn them on if we want them.
* There were a number of issues centered around the `tabIndex` handling.  For one, if the user turns off the "in tab order" option, reloading the page would cause the expression to get `tabIndex="0"` even though the menu item was still unchecked.  This is due to the fact that the mj-context-menu code doesn't know about the menu setting controlling this, so always sets …

Update explorer to allow drag selection, handle menu tab-order settings better, and a few other fixes

---

ts/input/tex/ParseMethods.ts
ts/input/tex/base/BaseItems.ts
ts/input/tex/base/BaseMethods.ts
ts/input/tex/cases/CasesConfiguration.ts
ts/input/tex/empheq/EmpheqConfiguration.ts
ts/input/tex/empheq/EmpheqUtil.ts
ts/input/tex/newcommand/NewcommandMethods.ts

This PR was started as a way to remove the original line 600 from `BaseItems.ts`, but includes changes to `empheq` and `cases` as well.
The changes to `ParseMethods.ts` are because the `end` property is no longer needed (and never really was).  The `BaseItem.ts` changes remove the test for `end` that isn't needed.
The `EmpheqBeginItem` subclass of `BeginItem` is not needed, as it doesn't actually do anything, and so it is removed, as is the `environment()` function in `EmpheqIUtil` that was used to create it.  The latter has been moved to the `CasesConfiguration.ts` environment, where it is still used.  The `end` property is used in `numcases` environments because it wraps the `empheq` environment, and `end` its used to properly handle producing the end for both environments.  A missing …

Remove need for 'end' property in handling of environments, and refactor numcases and empheq items

---

components/mjs/require/config.json
package.json

This PR causes the `require.mjs` file from the `components` directory to be included in the `bundle` directory, so that it will be part of the `mathjax` npm package.  That way, if someone is loading components by hand in a node application and loads any of the components that use SRE components, they can import the `require.mjs` file that is needed for SRE in node.
The `package.json` file is set up so that `import 'mathjax-full/require.mjs'` will work in `mathjax-full`, just like `import 'mathjax/require.mjs'` will work in the `mathjax` package.

Make a require configuration to include require.mjs in the bundle (so it will be in the mathjax npm package)

---

ts/core/MmlTree/MmlNodes/mo.ts
ts/input/tex/base/BaseMethods.ts

This was an issue reported by Peter, where `\overline{S}^2` would put the superscript too low.  TeX treats `\overline` and `\underline` specially, and not as other accents, but MathJax wasn't doing that.  The changes here make it work more like actual LaTeX.

Make over- and under-lines not be accents, so they operate as in actual TeX

---

testsuite/tests/input/tex/Ams.test.ts
testsuite/tests/input/tex/Amscd.test.ts
testsuite/tests/input/tex/Base.test.ts
testsuite/tests/input/tex/Boldsymbol.test.ts
testsuite/tests/input/tex/Braket.test.ts
testsuite/tests/input/tex/Bussproofs.test.ts
testsuite/tests/input/tex/ConfigMacros.test.ts
testsuite/tests/input/tex/Extpfeil.test.ts
testsuite/tests/input/tex/Mhchem.test.ts
testsuite/tests/input/tex/Physics.test.ts
testsuite/tests/input/tex/Tag.test.ts
testsuite/tests/input/tex/Unicode.test.ts

This PR fixes the tests to handle the changes from #1146 that resolved mathjax/MathJax#3300.  These are mostly changes for the removal of `mstyle` elements that are no longer needed, or the removal of some `displaystyle` or `scriptlevel` attributes that are redundant.
Some `newcommand` tests still fail, but they will pass with the PR that updates the `\let` command (I'm preparing it now).

Update tests to correspond with the changes for mathjax/MathJax#3300

---

testsuite/tests/input/tex/Ams.test.ts
testsuite/tests/input/tex/Amscd.test.ts
testsuite/tests/input/tex/Base.test.ts
testsuite/tests/input/tex/Physics.test.ts
testsuite/tests/input/tex/Tag.test.ts
ts/core/MmlTree/MmlNode.ts
ts/core/MmlTree/MmlNodes/mstyle.ts

The changes in #1146 caused an unintended consequence of not making some tables be in display style, and I accidentally "fixed" the tests to match the wrong results during the massive update I did on the test output.  This PR fixes that problem with tables and returns the tests to their proper values.

Fix more problems from #1146

---

ts/output/chtml.ts
ts/output/chtml/Wrappers/math.ts
ts/output/common.ts
ts/output/svg.ts
ts/output/svg/Wrappers/math.ts

This PR introduces clipping paths for the CHTML characters so that when selected, they highlight region will match the character bounding box (rather than having excessive depth, for example).  It also clips the spaces used for in-line breaking so that they don't show selection, just as the spacing for non-breakpoints doesn't show.
This clipping makes the focus outline match the bounding box better, particularly for the explorer on in-line expressions (the outline used to be excessively below the expression).  This necessitated some changes to the CSS for inline breaking, and requires one more rule to be in the font-specific CSS, so I had to rebuild all the fonts.  You will need to use the woff2 version of the lab to test this (as this is build on top of the woff2 branch).
I also …

Handle clipping of characters in CHTML better and avoid vertical scroll bars for overflow="scroll"

---

components/mjs/input/tex/extensions/mhchem/mhchem.js
testsuite/tests/input/tex/Mhchem.test.ts
ts/input/tex/mhchem/MhchemConfiguration.ts

This PR adjusts the `mhchem` package to provide several stretchy characters that it needed but that weren't in the original MathJax TeX fonts (and two that don't have Unicode equivalents).  This is done by using a separate `mathjax-mhchem` font that has the needed arrows and pieces needed for stretchy assemblies for these characters, based on the `mathjax-newcm` arrows.  In order to make the arrows used in mhchem consistent with these, all the arrows uses in mhchem are included in this new font, so that even when mhchem is used in a setting where a different font is selected, the arrows will not change their look between ones that could have been found in the selected font and ones that are in the `mathjax-mhchem` font.
The new font also includes character used for the bonds that have in …

Add stretchy characters needed by mhchem

---

ts/input/tex/bboldx/BboldxConfiguration.ts
ts/input/tex/bboldx/BboldxMappings.ts
ts/input/tex/bboldx/BboldxMethods.ts

This PR makes the bboldx delimiters into plain characters, as they are in the actual TeX package.
Since the characters used are actual parentheses, brackets, and angles, but just in a different variant, they obtain their TeX class (and other properties) from the operator dictionary.  So the open ones have TeX class OPEN, and the closes have TeX class CLOSE, as expected.
I'm not sure whey the `fence` property was being set to `false`, as the operator dictionary says they should be `true`, so I've removed that.  If there is a reason for it, I can put that back.

Make bboldx delimiters be plain characters, as in the actual package.

---

ts/ui/menu/SelectableInfo.ts

This PR changes from overriding `addEvents()` to overriding `keydown()` to handle the select-all action.  It wasn't working (at least for me in Firefox), and the lack of a `super.addEvents(element)` was preventing other handlers from being added, like the one for ESC to close the dialog.

Use Info's keydown() method to handle ctrl-A (it wasn't working this way).

---

components/mjs/a11y/util.js
components/mjs/input/tex/tex.js
components/mjs/mml-chtml-nofont/mml-chtml-nofont.js
components/mjs/mml-chtml/mml-chtml.js
components/mjs/mml-svg-nofont/mml-svg-nofont.js
components/mjs/mml-svg/mml-svg.js
components/mjs/node-main/node-main.js
components/mjs/output/util.js
components/mjs/startup/init.js
components/mjs/tex-chtml-nofont/tex-chtml-nofont.js
components/mjs/tex-chtml/tex-chtml.js
components/mjs/tex-mml-chtml-nofont/tex-mml-chtml-nofont.js
components/mjs/tex-mml-chtml/tex-mml-chtml.js
components/mjs/tex-mml-svg-nofont/tex-mml-svg-nofont.js
components/mjs/tex-mml-svg/tex-mml-svg.js
components/mjs/tex-svg-nofont/tex-svg-nofont.js
components/mjs/tex-svg/tex-svg.js
ts/components/loader.ts

This PR renames the `loader.preLoad()` method to `loader.preLoaded()` to make it clear that this function doesn't do any actual loading of files itself, but rather just tells the loader that you have preloaded some files.  There is no functionality difference, but the name has always been more confusing than it should be.
It would be possible to have `loader.preLoad()` call `loader.preLoaded()` for backward compatibility.  Do you thin that is necessary?

Rename loader.preLoad() to loader.preLoaded() to make it clear tht this doesn't do any loading itself.

---

testsuite/tests/input/tex/Base.test.ts
ts/input/tex/base/BaseMappings.ts

This PR changes the unicode value assigned to the `\perp` macro.
Resolves issue mathjax/MathJax#3322.

Map \perp to U+27C2 rather than U+22A5 (issue mathjax/MathJax#3322)

---

ts/components/loader.ts

This PR breaks the `normalize` path filter into two separate ones, the first that adds `[mathjax]/` to relative paths, and a second new one to handle the addition of `.js` when it is missing (which used to be part of the `normalize` filter).  The reason for this is so that third-party packages can create a path that includes the complete URL to their package, e.g., xypic can use `[xypic]` to point to the CDN that serves XyJax.  Without this PR, that would be translated to `[xypic].js`, by `normalize` and then the `[xypic]` portion would be replaced.  So if the `xypic` path already included the `.js`, this would be a problem.  (This is actually where I found out about it, as XyJax is being updated.)

Separate adding .js into a separate PathFilter

---

ts/a11y/explorer/KeyExplorer.ts
ts/components/startup.ts
ts/output/common.ts
ts/output/common/Wrapper.ts
ts/ui/menu/MJContextMenu.ts
ts/ui/menu/Menu.ts
ts/ui/menu/MenuUtil.ts

This PR fixes a number of problems that occur when menu values are changed, and in particular, when the menu values are reset to their defaults.
The fixes include the following:
1.  Resetting the menu to default values should force the math to be retypeset, but instead caused the math to disappear.  This was due to the initial typesetting not setting the `MathJax.startup.rerenderPromise`, so that has been added, here.
2.  Turning off inline breaking would not remove the current inline breaks.  This was due to the fact the inline breaks are handled via properties of the internal MathML nodes, and they were not being cleared.  This PR adds code to clear those properties.  It also moves the marker that the math has inline breaks from the `outputData` object (which is cleared when the state …

include a11y in default settings, and fix a number of problems with changing menu values.  (mathjax/MathJax#3310)

---

ts/ui/menu/Menu.ts

This PR allows you to filter attributes from the SVG image generated by the contextual menu "Show As" or "Copy to Clipboard" submenus.  It uses the settings from the "MathML includes" menu, renamed as "MathML/SVG has" (to not make it wider than it was).
This makes it easier to make cleaner SVG images.

Add ability to filter SRE and LaTeX attributes from SVG image

---

testsuite/package.json
testsuite/pnpm-lock.yaml
testsuite/src/index.ts
testsuite/src/setupTex.ts
testsuite/src/texReporter.js
testsuite/src/xmlMatch.ts
testsuite/tsconfig.json

This is the first in a series of PRs that I'm going to be making that add or updates tests for the TeX input jax and its packages.  I have broken down the PRs into separate pieces by tex package, to make them easier to review.  But some rely on some of the open PRs (like `rename-stylelist`, or `woff2`, or `begingroup`) in order to run, and I have not merged those into these branches, other than the `mhchem-stretchies` branch, which is merged into the `test-mhchem` PR that I will be making.  So you may not be able to test these individually without merging some of the other branches.  Many of these PRs include changes to the ts/input/tex package files to either fix bugs that I found while making the tests, or to remove unreachable code that was identified by jest during testing.  I will …

Update test framework

---

testsuite/tests/input/tex/Centernot.test.ts
testsuite/tests/input/tex/Color.test.ts
testsuite/tests/input/tex/Gensymb.test.ts
testsuite/tests/input/tex/Tagformat.test.ts
testsuite/tests/input/tex/Textcomp.test.ts
testsuite/tests/input/tex/Upgreek.test.ts

This PR adds new test files for the `centernot`, `gensymb`, `tagformat`, `textcomp`, and `upgreek` packages.  No code changes were needed in their corresponding `ts/input/tex package` files.
The remainder of the test PRs will include changes in the `ts/input/tex` files.

Add tests for the centernot, gensymb, tagformat, textcomp, and upgreek packages

---

testsuite/tests/input/tex/Tex.test.ts
ts/core/MmlTree/MmlNode.ts
ts/input/tex.ts
ts/input/tex/ColumnParser.ts
ts/input/tex/Configuration.ts
ts/input/tex/FilterUtil.ts
ts/input/tex/MapHandler.ts
ts/input/tex/NodeUtil.ts
ts/input/tex/ParseMethods.ts
ts/input/tex/ParseUtil.ts
ts/input/tex/StackItem.ts
ts/input/tex/TexError.ts
ts/input/tex/TexParser.ts

This PR adds a `Tex.test.ts` file that is intended to complete the coverage of the TeX input jax main files for lines that aren't run by other package-based tests.  Therefore, it is a bit of a hodge-podge of miscellaneous tests.
It also includes modifications to a number of the core TeX files in order to either correct bugs, or remove unreachable code, as described below:
* In `tex.ts`, the `globalEnv` is no longer used.  It was part of handling the `multline` environment, but that was changed some time ago in the `ams` package, while this code was never removed.
* in `ColumnParser.js`: 
- the `codePointAt()` function never returns undefined. (line 142)
- the `getBraces()` function always returns a string, so no need for `|| ''`. (line 265)
- we want to stop at the end of the string, not …

Miscellaneous tests for core tex files, and update code

---

testsuite/tests/input/tex/Ams.test.ts
ts/input/tex/ams/AmsMethods.ts

This PR updates the tests for the `ams` package, and adjusts `AmsMethods.ts` as follows:
* The `!taggable` at line 192 is always true, since if `taggable` is true, the block at lines 167-177 will run and `return` a value before this.
* Split up the `let` at lines 390-391.
* You are right, `MultiIntegral` is only used for `\idotsint`, so lines 532-538 can be simplified.
* The `xArrow` function gets a new parameter for the minimum width (so that `xlongrightarrow` can be implemented better, for example).
If you look at the `Ams.test.ts` file, it is probably best to hide whitespace changes.

Update ams tests and code

---

testsuite/tests/input/tex/Autoload.test.ts
ts/input/tex/autoload/AutoloadConfiguration.ts

This PR adds tests for the `autoload` package, and converts the configuration to use the `ConfigurationType` values rather than explicit names.

Add tests for autoload Package

---

testsuite/tests/input/tex/Bbm.test.ts
testsuite/tests/input/tex/Bboldx.test.ts
testsuite/tests/input/tex/Dsfont.test.ts
ts/input/tex/bboldx/BboldxMappings.ts
ts/input/tex/bboldx/BboldxMethods.ts

This PR adds tests for the three black-board bold font extensions.  It also includes the changes from `bboldx-delimiters` to change the delimiters to plain character macros.  In `BboldxMethods.ts`, the `parser.options.bboldx` object is set up during the package initialization, so will always be available at line 135.

Add tests for the bbm, bboldx, and dsfonts packages, and update code

---

testsuite/tests/input/tex/Boldsymbol.test.ts
ts/input/tex/boldsymbol/BoldsymbolConfiguration.ts

This PR updates the tests for the `boldsymbol` package, and its configuration file.
In the configuration file, the `NodeUtil.getAttribute(node, 'mathvariant')` on line 99 never is `null` because it will return the default value if it is not explicitly set, so the conditional is removed.

Update tests for the boldsymbol package and update code

---

testsuite/tests/input/tex/Cases.test.ts
testsuite/tests/input/tex/Empheq.test.ts
ts/input/tex/cases/CasesConfiguration.ts
ts/input/tex/empheq/EmpheqConfiguration.ts
ts/input/tex/empheq/EmpheqUtil.ts

This PR adds tests for the `cases` and `empheq` packages, and updates their code.
In `CasesConfiguration.ts`,
* The `subnumber` is non-zero only in `subnumcases`, which is handled in the condition above, so technically, this `if` should always be true and could be removed, but we don't really want increment the tag counter during the processing of the left-hand material, so we leave it with that condition only.
* In order to use the `\empheqlbrace` at line 105, we would need to load the `empheq` extension and add it to the `package` list.  Rather than force the user to do that, we use `\mmlToken` to create a stretchy brace instead.
* In line 200, we check that the `cs` is defined, which it might not be if the `\\` is at the end of the line.
In `EmpheqConfiguration.ts`,
* Since …

Add tests for the cases and empheq packages and update code

---

testsuite/tests/input/tex/Colortbl.test.ts
ts/input/tex/colortbl/ColortblConfiguration.ts

This PR adds tests for the `colortbl` package.  The `ColortblConfiguration.ts` file adds lines 98-100 to skip over an `mstyle` that may have been added to set the `scriptlevel` for the table.  The comments from the configuration object itself are moved to before it so that prettier can be run on the configuration.

Add tests for the colortbl package, and update its code

---

testsuite/tests/input/tex/Newcommand.test.ts
ts/input/tex/newcommand/NewcommandUtil.ts

This PR updates the test for the `newcommand` extension.  In the `NewcommandUtil.ts`, the case where `j < 0` does not occur, as `j` is reduced only on line 213, and that is only when `hasBraces` is true.  For that to be the case, there would have had to have been an initial open brace, in which case line 206 would have called `GetArgument()`, which would find a matching close brace, so there must be at least two characters (the two braces), and `j` would be at least 2 before it is decremented.  So it never gets below 0.

Update tests for the newcommand package, and update code

---

testsuite/tests/input/tex/Noundefined.test.ts
ts/input/tex/noundefined/NoUndefinedConfiguration.ts

This PR updates the tests for the `noundefined` package.  It also removes `|| {}` in its configuration, since the `parser.options.noundefined` will always be defined when the package is initialized.

Update test format for the noundefined package and fix coverage

---

testsuite/lib/error.js
testsuite/tests/input/tex/Require.test.ts
ts/input/tex/require/RequireConfiguration.ts

This PR adds tests for the `require` package.  For one test, we need an extension that has a dependency that fails to load due to an error in the dependency's code, so there is a new `lib/error.js` file that does that.
In `RequireConfiguration.ts`, lines 181-183 are restructured to avoid the `?.` constructions (which didn't get individual coverage for each `?.`).  The other changes are to use `ConfigurationType` rather than explicit property names.

Add tests for the require package and fix code

---

testsuite/tests/input/tex/Setoptions.test.ts
ts/input/tex/setoptions/SetOptionsConfiguration.ts

This PR adds tests for the `setoptions` package, and updates its configuration file.
The changes to the configuration include:
* Breaking the error message at 82-86 into two messages, one for the TeX options, and one for package options, mirroring the messages in (original) lines 91-103.
* To do that, the `isTex`variable is moved earlier to line 78.
* The `filterValue()` function is extended to handle RegExp values (like the one for the ams parameter `operatornamePattern`).
* The `setoptions` command map is now created within the `setoptionsConfig()` function.  This means that the map will be recreated for each instance of the `setoptions` package, so if there are two TeX input jax created, one with `[tex]/require` includes and one without it, the first will get the updated `\require` …

Add tests for the setoptions package and fix code

---

testsuite/tests/input/tex/Texhtml.test.ts
ts/input/tex/texhtml/TexHtmlConfiguration.ts

This PR adds tests for the `texhtml` package, and fixes a typo in the comments of its configuration.

Add tests for the texhtml package and update code

---

testsuite/tests/input/tex/Textmacros.test.ts
ts/input/tex/textmacros/TextMacrosMethods.ts
ts/input/tex/textmacros/TextParser.ts

This PR adds tests for the `textmacros` package, and makes two small adjustments to the code:
* In `TextMacrosMethods.ts`, the `GetNext()` method already skips spaces, so there is no need for the loop here.
* In `TextParser.ts`, the addition of the TeXAtom is moved to after the checking for size and color attributes, otherwise they will be hidden inside the TeXAtom and never seen.

Add tests for the textmacros package and update code

---

testsuite/tests/input/tex/Unicode.test.ts
ts/input/tex/unicode/UnicodeConfiguration.ts

This PR updates the format of the tests for the `unicode` and fixes one issue in the configuration file:  since `GetBrackets()` always returns a string, there is no need for the `|| ''`.

Update unicode tests and code

---

testsuite/tests/input/tex/Units.test.ts
ts/input/tex/units/UnitsConfiguration.ts

This PR adds tests for the `units` package, and adjusts the configuration file:
* The `GetBrackets()` method always returns a string, so no need for `|| ''`.
* The `GetBrackets()` method has an optional parameter for the default value, so we use that in line 74.

Add tests for the units package and update code

---

components/mjs/dependencies.js
testsuite/tests/input/tex/Mathtools.test.ts
ts/input/tex/mathtools/MathtoolsConfiguration.ts
ts/input/tex/mathtools/MathtoolsItems.ts
ts/input/tex/mathtools/MathtoolsMappings.ts
ts/input/tex/mathtools/MathtoolsMethods.ts
ts/input/tex/mathtools/MathtoolsTags.ts
ts/input/tex/mathtools/MathtoolsUtil.ts

This PR adds tests for the `mathtools` package and updates its code.
It turns out that `mathtools` got an update in 2022, and some things have changed, so I've updated the code to reflect those changes.  In particular, there are some breaking changes to `\coloneq` and three other colon macros.  A new `legacycolonsymbols` option controls which set to use (jsut as in actual `mathtools`).  I also added support for `\MakeAboxedCommand` which was missing from the current package.  This includes a non-standard starred version that handles box commands whose contents are in math-mode rather than text-mode, like `\bbox` and `\boxed` versus `\fbox` and `\fcolorbox`.  Finally, several new extensible arrows were added in 2022 and 2024, and I've added those as well.
To handle `legacycolonsymbols`, we …

Add tests for the mathtools package, and update code

---

components/bin/copy

This PR provides a method for specifying multiple copy operations in a component's `config.json` file.  The `copy` property can now be an array of copy configurations (or still a single one).  This will allow the sre component to copy both its map files and the webwork files using a single configuration file.

Add ability in config.json to specify mutiple copy configurations

---

testsuite/tests/input/tex/Amscd.test.ts
ts/input/tex/amscd/AmsCdMethods.ts

This PR updates the tests for the `amscd` package and its code.
Here, the `if (a || b)` on line 127 is always true due to lines 124 to 126 that set `a` when it is not set.  The `if` is removed, and the block indentation is adjusted.
The change at line 204 is because the table and row arrays are always defined.
Again, viewing without white-space changes is useful, here.

Update tests for amscd

---

testsuite/tests/input/tex/UnitUtil.test.ts
ts/input/tex/UnitUtil.ts

This PR updates the tests for `UnitUtil.ts` and adjusts the code:
* In original line 98, since we know (from line 94) that we have `mu` units, that means `value` will not be an empty string, and so the `|| '1'` is not needed.
* In original line 146, we know `factor` is defined, since the `UNIT_CASES.get()` function in the previous line will return the value for 'pt' (line 65) if the unit itself is not found.  So unless someone deletes the 'pt' value, the `factor` should always be defined, and if it turns out to be 0, then `factor * m` will be 0, so there is no need for the test.

Update UnitUtil tests and code

---

testsuite/tests/input/tex/Html.test.ts
ts/input/tex/html/HtmlMethods.ts

Apparently I pushed this branch but forgot to make the PR for it.
This PR updates the tests for the HTML package and adjust the code.
* The changes to `oldStyle` are because the `;` was being added in the wrong place.
* Lines 154-157 are removed because they can't be reached in our current code.  The reason is that `arg` comes from `ParseArg()`, which returns the `mml()` value of the parsed argument.  That in turn returns the top stack item's first `mml` node.  But `mml` nodes are created by the StackItem's `toMml()`, and that already removes top-level rows if they contain only one child node, expect if the `forceRow` argument is true.  The only call where that is the case is in `BracketItems.ts` line 62, where the resulting inferred mrow is unpacked immediately by the spread operator on …

Update tests for the html pacakge and fix code

---

ts/output/svg/Wrapper.ts

This PR fixes an issue where superscripts (or other scaled items) that have IDs are not positioned properly in SVG output.  For example, `10^4` has the 4 too high.  This is due to the correction being done to try to allow elements with IDs to be targets of a link and have the browser scroll to them properly.  Unfortunately, the position adjustement wasn't being properly scaled.

Fix position adjustment for scaled svg items with ids

---

ts/output/svg/Wrappers/msqrt.ts

This PR changes the order of the root and the radicand in the SVG output for `mroot` elements, as requested by the AMS in mathjax/MathJax#3335.

Change order of root and radicand. (mathjax/MathJax#3335)

---

ts/core/MmlTree/MmlNodes/mo.ts
ts/output/common/Wrapper.ts

This PR fixes an issue with operator spacing when MathML spacing is being used and the operator isn't found in the operator dictionary.  The work done to find the TeX class for such operators interfered with the spacing in MathML spacing mode.  Here, we mark such nodes with a property that can be used to help determine the MathML spacing.
Resolve issue mathjax/MathJax#3288.

Update default spacing for mo elements that aren't in the operator dictionary (mathjax/MathJax#3288)

---

testsuite/tests/input/tex/Unicode.test.ts
ts/input/tex/unicode/UnicodeConfiguration.ts

This PR fixes an error in the `\char` command where it was using `\char'\x` where it should have been using ``\char`\x``.  It also updates the tests accordingly.

Fix incorrect character for \char`\x (was incorrectly set to \char'\x)

---

testsuite/tests/util/Context-browser.test.ts
testsuite/tests/util/Context-node.test.ts
ts/util/asyncLoad/esm.ts
ts/util/asyncLoad/system.ts

This PR adds a `Context-browser.test.ts` file that tests the `ts/util/context.ts` file in a browser by including a fake `window` object, and a `Context-node.test.ts` to test `ts/util/context.ts` when used in node.
Also, two `asyncLoad` files are adjusted so that the coverage is properly computed.

Add tests for util/context.ts and fix coverage for asyncLoad

---

components/mjs/a11y/semantic-enrich/config.json
components/mjs/a11y/semantic-enrich/semantic-enrich.js
components/mjs/a11y/sre/sre.js
components/mjs/a11y/util.js
components/mjs/mml-chtml-nofont/mml-chtml-nofont.js
components/mjs/mml-chtml/mml-chtml.js
components/mjs/mml-svg-nofont/mml-svg-nofont.js
components/mjs/mml-svg/mml-svg.js
components/mjs/tex-chtml-nofont/tex-chtml-nofont.js
components/mjs/tex-chtml/tex-chtml.js
components/mjs/tex-mml-chtml-nofont/tex-mml-chtml-nofont.js
components/mjs/tex-mml-chtml/tex-mml-chtml.js
components/mjs/tex-mml-svg-nofont/tex-mml-svg-nofont.js
components/mjs/tex-mml-svg/tex-mml-svg.js
components/mjs/tex-svg-nofont/tex-svg-nofont.js
components/mjs/tex-svg/tex-svg.js

This is the PR that I promised that removes the `cherckSre()` function from the `a11y/util.js` file.  It removes its usage in all the combined components.
In addition, it remove the SpeechUtil, GeneratorPool, and WebWorker targets from the semantic-enrich build configuration, since they are not used there (they are loaded by the speech component), and removes the `sreReady()` call from there.  Instead, that is being made in the `sre` commponent itself (just to make sure that SRE is ready to go when the components are finished loading).

Remove checkSre() calls in combined configurations

---

components/mjs/dependencies.js
components/mjs/output/chtml/config.json
components/mjs/output/svg/config.json
components/webpack.common.cjs
package.json
ts/components/global.ts
ts/input/tex/require/RequireConfiguration.ts

This PR makes miscellaneous updates to various component configurations and related changes.
* A `ui/menu` dependency on `a11y/sre` is added (since `SpeechMenu.ts` uses it).
* The `output/chtml` and `output/svg` config files now target `common.ts`, so that that will be included in the `MathJax._` tree, and the `components/src/startup/lib` is added so that `ts/components/package.ts` will be shared properly.  (Otherwise this leads to two separate copies of the `Package` class that don't know about what the other one has loaded.)
* The `webpack.common.js` and `package.json` are modified to allow `compoments/js` to obtain `compoments/mjs` or `components/cjs` depending on whether it is used in an `import` or a `require()`.  (The older `components/src` is still there for backward compatibility …

Fix miscellaneous issues with components

---

ts/core/MathDocument.ts
ts/handlers/html/HTMLDomStrings.ts
ts/input/mathml/MathMLCompile.ts
ts/input/tex/FindTeX.ts
ts/output/common.ts
ts/ui/menu/Menu.ts

This PR makes a few miscellaneous changes that I found while updating the documentation.
* In `MathDocument.ts`, you only need to set the `mtextFamily` and `merrorFamily` if we are inheriting the them.
* In `HTMLDomStrings.ts`, the `skipHtmlTags` array is simplified (`math` is added and annotation nodes are removed, since they shoudl be inside `math` nodes).
* In `MathMLCompile.ts`,  any `data-mjx-` attribute that isn't otherwise handled is added as an attribute (e.g., `data-mjx-hdw`, `data-mjx-error`, etc., for example).
* In `FindTeX.ts`, escaped MathItems now get a `\` as their opening delimiter, so that if the Math is inserted back into the page (e.g., when setting `state()` back to 0), the escaped character will be replaced properly.
* In `common.ts`, the `display` value is now …

Miscellaneous small updates

---

testsuite/tests/input/tex/Ams.test.ts
testsuite/tests/input/tex/Amscd.test.ts
testsuite/tests/input/tex/Base.test.ts
testsuite/tests/input/tex/Texhtml.test.ts
ts/input/tex/FilterUtil.ts

This PR makes sure that when adjacent `mo` elements with TeX class `REL` are combined into a single `mo`, they are given the `data-mjx-texclass="REL"` attribute, so that when they pass through SRE, they will remain TeX class REL.  Because the multiple-character `mo` will not be in the operator dictionary, without this attribute, they will come back as BIN class operators, so get the wrong spacing.
Most of the changes here are to adjust the tests to include the new attributes, so you can ignore them.  Only the last file is the code change, and that is just one line.

Add texClass REL when combining mo nodes so they round-trip through SRE properly, and adjust tests to match

---

ts/core/MmlTree/MmlNodes/mspace.ts
ts/output/common.ts

This PR prevents negative spaces from being considered as valid breakpoints.  This is particularly important for in-line breaks, but affects both in-line and display breaking.

Don't allow inline breaks at negative spaces

---

ts/output/common/FontData.ts

The "Lookbehind in JS regular expressions" feature is not widely supported in browsers, and this lack of support is causing issues when using MathJax in certain scenarios.
Resolve issue https://github.com/mathjax/MathJax/issues/3352

Fix Lookbehind assertions was not widely supported in browser

---

components/bin/pack

The error messages emitted by spawned webpack were not printed, which caused difficulties in adapting the script. 
Simply print stderr.
Before
After

Add more log print when pack failed

---

ts/input/tex/ParseUtil.ts

This PR changes the regexp used to trim spaces from the content of `mtext` elements generated by the `internalText()` command.  The `\s` pattern used originally would match non-breaking spaces (U+00A0), which should not be collapsed into other spaces.  So this uses just the actual space character, not all other space-like characters matched by `\s`.
Resolves issue mathjax/MathJax#3353.

Use actual space rather than \s to trim mtext content (to not match U+00A0). (mathjax/MathJax#3353)

---

testsuite/tests/util/Retries.test.ts
ts/a11y/speech.ts
ts/components/startup.ts
ts/core/MathDocument.ts
ts/ui/menu/Menu.ts
ts/util/Retries.ts

Now that both speech and output (when font data is loaded) use promises and retries, it seems appropriate to add promise-based calls to the core MathDocument for typesetting and conversion, like the ones in the Startup module.
This PR adds those functions.  In particular, new `renderPromise()`, `rerenderPromise()`, and `convertPromise()` methods are added to the `MathDocument` class, and the Startup module now takes advantage of these when creating `MathJax.typesetPromise()` and the various conversion functions like `MathJax.tex2chtmlPromise()`.
The old `MathJax.typesetPromise()` and conversion functions had been modified to use the `MathJax.startup.promise` to make sure that they operated serially.  The new MathDocument methods now do that using a new `_readyPromise`, and a new …

Add core promise-based typeset and convert functions, and simplify those in Startup.

---

ts/a11y/explorer/TreeExplorer.ts
ts/a11y/sre.ts

Refactors code for tree coloring from SRE to the actual explorer. This reduces the footprint of code that is pulled in from SRE. I will remove more dependencies once PR #1241 is merged.
Note, that commit 04775ebbe35a00344dc28eab0d2220637554d450 only contains changes from automatic formatting and linting.

Refactor Tree Colorer

---

package.json
pnpm-lock.yaml
ts/a11y/speech/GeneratorPool.ts

Corrects following issues:
* Updates `package.json` to the correct SRE package. Also removes an unused linting option that crashes the `lint:fix` lifecycle script.
* Makes cancel calls on webworker more secure, to avoid error that occurs, for example, when using lazy typesetting.

Corrects worker issues

---

components/bin/link-full
components/bin/package.json
components/mjs/fullpath.cjs
components/webpack.common.cjs
package.json

This PR moves `mathjax-full` to a scoped package, `@mathjax/src`, as we have discussed.  The fonts are already scoped, and this completes the move to `@mathjax`.

Change to using @mathjax/src rather than mathjax-full

---

components/bin/makeAll
components/bin/pack
ts/a11y/assistive-mml.ts
ts/adaptors/lite/Element.ts
ts/components/package.ts
ts/components/startup.ts
ts/input/tex/require/RequireConfiguration.ts
ts/output/chtml/Wrappers/mmultiscripts.ts

This is a collection of miscellaneous fixes that I have accumulated while updating the documentation for v4.
The `makeAll` and `pack` changes are to handle building of fonts and third-party extensions better.
The `assistive-mml` change is to prevent the assistive MathML representation from being pushed outside the bounding box of the MathJax output.
The `lite/Element.ts` changes are to prevent the version mismatch error when a node application uses MathJax components rather than direct calls, and the loader uses the `MathJax.loader.load()` command.
The `components/package.ts` change is to get the proper result returned when `require()` is used in `MathJax.loader.load` (e.g., when `MathJax = {loader: {require: require}}` is used in CommonJS applications).
The `components/startup.ts` change …

Misc fixes

---

ts/a11y/explorer.ts
ts/a11y/explorer/KeyExplorer.ts
ts/a11y/speech/GeneratorPool.ts
ts/output/svg.ts
ts/output/svg/Wrappers/math.ts
ts/ui/menu/MJContextMenu.ts
ts/ui/menu/Menu.ts
ts/ui/menu/MmlVisitor.ts

This PR is an update to `update/explorer` that fixes some problems with refocusing the selected item when the menu is use from within the explorer, particularly when the menu selection opens a dialog.  It also moves the `roleDescription` option to the explorer's `a11y` options, so it can be configured even when the menu component is not loaded, and removes the `internalSpeechTitles` option, which is no longer supported since the speech is added to the DOM elements after the output is created.
The changes in `explorer.ts` make `roleDescription` an `a11y` option for the document.
In `KeyExplorer.ts`, we clear the `nofocus` setting after it is used, and change the button checking from `button !== 0` to `button === 2` when checking for right mouse buttons that will cause context-menu events. …

Update refocus from menu actions, and adjust some options

---

ts/util/Styles.ts

This PR fixes a problem where `border-radius` CSS was being dropped.  The fix is to make sure that when the parent name is found, it has the child name as an actual child (e.g., the `border` data doesn't have `border-radius` as a child).
Resolves issue mathjax/MathJax#3365.

Fix cssText creation to handle border-radius and similar values. (mathjax/MathJax#3365)

---

ts/handlers/html/HTMLDocument.ts
ts/output/chtml.ts
ts/output/common.ts
ts/output/svg.ts

This PR adds support for an extension having styles.  E.g., the explorer has styles, and if it is loaded by the menu after the page is already running, those style wouldn't get set.  This PR fixes that.

Add an `insertStyles()` method to update styles when an extension is loaded

---

ts/components/startup.ts

This PR adds a `defaultOptionError` that can be used if the `optionError` configuration option is used so that the original action can be taken after the user's actions are performed (e.g., recording the error).
It also moves the `hasTypeset` indicator to be outside the promise call in `typesetPromise()`, so that if the promise code is put off for later, the inidicator still knows that the typeset has been queued.  (This gets used in the menu to tell if a rerender is needed.)

Fix timing of hasTypeset and make defaultOptionError for easier configuration

---

ts/a11y/explorer.ts
ts/a11y/explorer/KeyExplorer.ts
ts/ui/menu/Menu.ts

This PR adds a menu item to control whether tabbing to an expression focuses on the whole expression, or on the last explored node, as per Volker's request.  It is in the *Options* submenu in the accessibility section of the main contextual menu.

Add menu item to control what tabbing will focus on

---

ts/a11y/complexity/collapse.ts
ts/a11y/explorer.ts
ts/a11y/explorer/KeyExplorer.ts
ts/a11y/speech/WebWorker.ts
ts/output/chtml/Wrappers/math.ts
ts/output/svg.ts
ts/ui/menu/Menu.ts
ts/ui/menu/MenuHandler.ts

This PR implements some changes to the explorer that makes it work better with Orca in Linux, particularly with Orca 46.1 in Ubuntu 24.04.  It removes the need to clone the container element that was part of #1249 and #1251, and makes the process used more browser and OS independent (the only OS dependency now is the role used on the temporary speech elements).  I will close the two older PRs in favor of this one.
The details about the changes will be added below, but I wanted to get it out for testing and not wait for that.

Fix a number of explorer and menu issues, and update to work with Orca 46

---

package.json
pnpm-lock.yaml
ts/a11y/explorer/Explorer.ts
ts/a11y/explorer/ExplorerPool.ts
ts/a11y/explorer/Highlighter.ts
ts/a11y/explorer/KeyExplorer.ts
ts/a11y/explorer/Region.ts
ts/a11y/speech/GeneratorPool.ts
ts/a11y/speech/SpeechMenu.ts
ts/a11y/speech/WebWorker.ts
ts/a11y/sre.ts
ts/a11y/sre/speech-worker.ts
ts/ui/menu/MJContextMenu.ts
ts/ui/menu/Menu.ts

**Only works with the latest versions of SRE, v5-alpha.3 and above. Make sure to run `pnpm install` first!**
The PR does 4 main things:
1) Fixes the auto voicing option
2) Reinstates the functionality of the Clearspeak submenu
3) Ensures that consistent ruleset/preference changes on an element. 
4) Removes `ChromeVox` menu entry
Auto voicing with synchronised highlighting uses the `SemAttr.SPEECH_SSML` attributes to compute speech, pauses and the highlighting marks. It also depends on these being available at all levels of the expression.
* The container gets the ssml attribute form the speech structure from SRE (latest version!)
* We compute SSML not just for summary but also for regular speech in `SsmlAttributes`.
* Hiding the `SpeechRegion` cancels the speech.
Since some of the …

Autovoicing and Clearspeak menu

---

testsuite/tests/util/Styles.test.ts
ts/util/Styles.ts

This PR fixes a problem with the `util/Styles.ts` file where the use of a sub-style could cause a parent style to be created with an undefined value.  For example, defining `border-radius: 3px` causes `border` to be created but be undefined.  That leads `Styles.cssText` to produce `border-radius: 3px; border: undefined;`.
The fix checks that the sub-style is one of the child styles of the parent style before trying to connect it to the parent (which creates the parent style).

Fix a problem with substyles generating undefined base styles.

---

testsuite/tests/input/tex/Base.test.ts
ts/input/tex/TexParser.ts

This PR fixes the crash that occurs when `\overline` or `\underline` is used with a braced subscript that has a space between the underscore and the open brace.  It also adds a test for that condition.
Resolves issue mathjax/MathJax#3372.

Fix problem with overline with subscript with space after the underscore. (mathjax/MathJax#3372)

---

package.json
pnpm-lock.yaml
testsuite/src/setupTex.ts
ts/input/tex/unicode/UnicodeConfiguration.ts

Addresses issue discussed at the end of PR #1271 :
* explicitly installs `@eslint/js` package (see https://typescript-eslint.io/getting-started/#step-1-installation)
* ensures the `@ts-ignore` lines are not linted

Fixes problems with eslint

---

components/bin/build
ts/a11y/explorer/Highlighter.ts
ts/a11y/sre.ts
ts/handlers/html/HTMLDocument.ts

This PR fixes a problem with building the `ui/menu` component.  The `components/bin/build` command is modified to handle `export async function` which was causing an error during the build phase.  The `ts/a11y/sre.ts` function also was causing problems when webpacking the `ui/menu` component.  The the SRE functions for the preferences were not being found by webpack for some reason that I could not fully determine.  I don't see anything wrong in any of the files, but it seems to be connected to the direct `export` of those methods in `ts/a11y/res.ts`, so I've change those to an import followed by exports, which seems to do the trick.
In addition, I've added a generic highlighter in `ts/a11y/explorer/Highlighter.ts` so that it can work in the absense of an output jax (I have an example in …

Update build and ui/menu so its builds with new highligher

---

testsuite/tests/input/tex/Newcommand.test.ts
ts/input/tex/newcommand/NewcommandUtil.ts

This PR fixes a problem with parsing the arguments of a macro with template where braces could be removed incorrectly.  For example, with `\def\text#1\stop{#1}`, if used with `\text{a}{b}\stop`, you currently will get an error about missing open braces.  That is because the parameter `#1` will end up containing `a}{b` rather than `{a}{b}` as expected.
The solution is to set `hasBraces` to false when a second braced argument is used.  I also changed `hasBraces` to a boolean rather than a number.
Two new tests are added to check for this issue.  There should probably be some more tests for when `hasBraces` gets unset, for completeness.

Fix incorrect removal of braces in template macros

---

ts/adaptors/lite/Element.ts

This PR fixes a problem with the changes in b7f1942 that cause an error in node applications that use direct loading of the MathJax modules, where the `MathJax` variable is not defined.  I thought the `MathJax?.loader` would check for that, but it turns out that isn't the case, and  a more explicit check for being defined is needed.

Fix problem with MathJax reference in liteDOM

---

components/mjs/a11y/speech/speech.js
components/mjs/dependencies.js
components/mjs/source.js
lab/build/init.js
lab/build/sre.js
package.json
pnpm-lock.yaml
ts/a11y/speech.ts
ts/a11y/sre/speech-worker.ts
ts/a11y/sre/worker_threads.d.ts
ts/adaptors/HTMLAdaptor.ts
ts/adaptors/liteAdaptor.ts

This PR adds a `worker.maps` configuration option that specifies where the mathmaps are located.  This allows node applications that are using direct loading of MathJax or loading the MathJax components from source to get the correct location for the maps.  It also also gives the ability to specify an alternate location for the maps during testing and development, if needed.
The defaults are set so that even when loading from the `mjs/a11y/sre` or `cjs/a11y/sre`, the mathmaps will be taken from the `bundle/sre` directory, since they don't exist in the `[mc]js/a11y/sre` directories.  For the web, or when components are used, the `[sre]` and the new `[mathmaps]` prefixes determine these.  When loading components from source (with the `source.js` file), the `[mathmaps]` are directed to the …

Improve mathmap configuration

---

components/mjs/input/tex/extension.js

This PR fixes an error with the font-extension URLs, which failed to include the `@mathjax` scope.
Resolves issue mathjax/MathJax#3387.

Fix font-extension URLs to include @mathjax (mathjax/MathJax#3387)

---

components/mjs/a11y/speech/speech.js
components/mjs/a11y/sre/worker/config.json
components/mjs/a11y/sre/worker/webpack.cjs
ts/a11y/sre/package.json
ts/a11y/sre/speech-worker.ts
ts/adaptors/HTMLAdaptor.ts

This PR fixes a problem with importing the worker code from a page the was loaded from a `file://` URL with Mathjax coming from the CDN.  The problem only seems to affect Chrome, which won't allow the cross-origin load, even though the CDN marks the script as allowed.
The solution is to use `importScripts()` rather than `import()` to get the worker code.  That means the worker can't be loaded as a module, as `importScripts()` isn't allowed there.  
The `package.json` file is no longer needed, and the worker doesn't need to be a module anymore (that could have been removed when the worker-pool was removed, as that was only needed for the iframe hack to the liteDOM).
The v4-lab needs a new way to detect the need for the `sre-lab.js` file, as the `importScripts()` can't load an ES6 module, …

Allow Chrome to load speech worker from CDN in a page from a file:// URL

---

ts/output/common.ts

When a page has SVG rendering on by default when loaded, and inline breaks are enabled, then when we switch to CHTML output, all the inline breaks are forced to occur.  The is due to the way the SVG output has to be broken into separate SVG nodes, so it had marked the nodes for forced breaks, and those marks aren't removed.
This refactors the old code to unmark the breaks if they were set before and we don't want breaks (i.e., the inline breaks menu setting has changed) or the force-break setting is changing (i.e., the render changed).  Then we check if breaks are needed and make them again with the new settings.  The unsetting and breaking are no longer one-or-the-other, and only the needed actions are taken.

Clear forced inline breaks when switching between renderers, when needed

---

components/bin/pack
components/webpack.common.cjs

The `+` was missing from the regex for quoting file and directory names (argh!).
This causes these to not properly match directories in `node_modules` when pnpm is used to install dependencies, since it uses hidden directories in `.pnpm` that include plus signs.

Fix regex for quoting file names to include

---

ts/adaptors/lite/Parser.ts

This PR makes the parsing of tags and attributes more compliant with he HTML5 spec, which has much looser parameters for tag and attribute names.  XML parsing is more restrictive, but since the parser must work for both (it is not very sophisticated), it needs to use the less restrictive version (HTML5).
The main change is that attribute names don't have to start with a letter.  The other restrictions remove the control characters and the other disallowed characters.  See #1297 for some discussion of the specs.

Changes the TAG and ATTR patterns to be more in line with HTML5 (#1297)

---

ts/util/Retries.ts

This PR adds more detail to the "MathJax retry" error message so that programmers who use the synchronous functions and don't trap this error will get more details about what is happening.  (There is also a completely new section in the v4 documentation about this error, so I'm hoping this PR and that new page will reduce the questions about this.)
The error message is never actually used internally (just the `.retry` property), so the actual message is immaterial from the standpoint of the code.

Make the retry error message more descriptive

---

ts/input/asciimath/legacy/jax/element/MmlNode.js

This makes the legacy AsciiMath internal format to v3/v4 internal format properly mark the text elements as `#text` rather than `text`.

Make sure AsciiMath text elements are of kind #text

---

ts/handlers/html/HTMLDocument.ts

This PR changes where the `MathDocument` puts additional elements into the page.  Currently, only the SVG output has any of these, and they are the `svg` element used to store the global font cache (in a `defs` element).  This should be at the top of the document, not the bottom, so that the definitions are in place before the elements that use them (important when the document is preprocessed on the server).

Place the hidden svg/defs elements at the beginning of the document, not the end.

---

ts/a11y/speech.ts

This PR makes sure that enrichment is being performed before trying to add speech or Braille.  This avoids an error in node applications that load a combined configuration with speech, but turn off enrichment while leaving the speech or Braille defaults (which are on).

Check that enrichment is enabled before starting webworker

---

ts/components/startup.ts

This PR changes the handling of the `options` object in the typesetting and conversion commands created by the Startup module so that they use a copy of the options rather than the original object.  This prevents the changes we make to `options` from being made to the original object passed to the functions (in case they are used again later by the calling program).

Don't alter the typeset option lists in case they are reused

---

testsuite/tests/util/FunctionList.test.ts
ts/core/InputJax.ts
ts/core/OutputJax.ts
ts/input/mathml.ts
ts/input/tex.ts
ts/output/common.ts
ts/util/FunctionList.ts

This PR adds the ability to have pre- and post-filters for the input and output jax be included in their configuration objects, rather than having to use the `startup.ready()` function to add them.  It also adds a pre-filter to the output jax, for symmetry (and because it may be easier to do filtering there than to have to add a post-filter onto each of the input jax if there are multiple input formats).
To facilitate this, a new `addList()` method is added to the `FunctionList` object, and for good measure this is used in the TeX input jax to add its filters.  You can also now pass a function list to the `FunctionList` constructor.  A new test is added to the `FunctionList` tests to cover the new code.

Add configuration options for pre- and post-filters

---

ts/adaptors/liteAdaptor.ts

This PR fixes a problem where the LiteDOM incorrectly adds a space at the beginning of the `className` of LiteElements.  That is because when the `className` is empty, the split produces `['']`, not an empty list, so when more classes are added or removed, and the joined with a space, there is an empty name at the beginning, giving a space at the front of the list.
This also uses `indexOf()` and `includes()` rather than `find()` and `findIndex()`, as these should be more efficient.

Fix addClass() and similar to not add extra blank in class

---

ts/a11y/explorer/KeyExplorer.ts

In the key explorer, when enter is pressed on a node with a link, we currently send a click event to the parent node, which is expected to be the anchor taking you to the linked file.  It is possible, however, that the parent may be some other node that the CHTML output needs for the layout, and so the click goes to the wrong node. 
This PR has the explorer look higher up until it finds the associated anchor rather than assume it is the parent element.
Resolves issue mathjax/MathJax#3398.

Have the explorer look harder for the associated anchor node.  (mathjax/MathJax#3398)

---

ts/output/common/Wrapper.ts

Currently, when `mathmlSpacing` is used, an error can be thrown for an `mo` that doesn't have a parent node.  Such elements occur when special characters are needed, like the surd for a square root.  Changing original line 1079 to use `(!n)` rather than `n !== 0` would prevent the error message, but in that case the default spacing for `mo` elements would give the surd spacing on the left and right, which throws off the display.  Instead, we move the test for no parent to before when the MathML spacing is added to avoid both the error message and the wrong display.

Handle mml spacing for mo with no parent (like surd for root).

---

components/bin/build

This PR makes sure a component's `lib` directory is created so its main control file can be written, even if there are no other imports.  This file contains the version check, and so it is useful to build even when there are no imports, or if all the imports are to other library files.

Make sure the build command makes the lib directory even if there are no imports

---

testsuite/tests/util/string.test.ts
ts/util/string.ts

This PR fixes an issue with the string utility's `replaceUnicode()` function that prevented it from processing two adjacent `\U{}` calls, so `replaceUnicode('\U{A0}\U{A0}')` would only replace the first `\U`, not the second.  That was due to the requirement of having a non-`\` character preceding the `\U` which blocked it from matching the second `\U`, as that character can't be part of a previous replacement.  That requirement was part of an attempt to avoid escaped backslashes like `\\U`.  But, in addition to the problem it caused for replacing the `\U{}`, the escaped backslashes were never converted to single backslashes.  The new code now properly does that as well.
The tests are adjusted to accommodate the translation of `\\` to `\`, and to add a pair of adjacent `\U`.

Update `replaceUnicode()` to handle two `\U{}` calls in a row.

---

components/mjs/input/tex/register.js

This PR fixes the component utility that marks preloaded TeX packages so that it will properly merge the new packages into the existing package list if the old list was an array (rather than `{'[+]': [...]}`).

Fix `registerTex()` to handle `tex.packages` that is already an array

---

ts/core/MmlTree/MmlNodes/mo.ts

This PR fixes a problem with `mathmlSpacing` when an `mo` element has a default spacing of 0, a with `<mo>&#x2062;</mo>`.  In the past, this would get extra spacing that it should not have.  Now, if the default spacing is 0, we take away the extra `+ 1` that is being added to get the proper number of 1/18th ems from the operator dictionary.

Don't increase the spacing size for MathML spacing if it is 0

---

ts/components/loader.ts
ts/components/package.ts

This PR fixes a problem when combined components are loaded via the `loader.load` configuration array in node applications and one of the preloaded components needs to perform additional loads (like when the output jax needs to load a font).  In the past, the load of the combined component would complete before the extra components are loaded, and so MathJax could process the page with the wrong font, for example.
In the current `develop` branch, the code
``` js
#! node
import {init} from '@mathjax/src/source';
await init({
loader: {load: ['tex-chtml']},
output: {font: 'mathjax-tex'},
options: {enableSpeech: false, enableBraille: false},
})
const node = await MathJax.tex2chtmlPromise('x');
console.log(MathJax.startup.adaptor.outerHTML(node));
```
produces
```
<mjx-container …
```

Better support for Loader.preLoaded() when used in combined components in node

---

components/mjs/output/util.js
ts/output/common.ts

This PR adds a `fontExtensions` configuration that makes it easier to specify a font extension to load (e.g., `mathjax-euler`).  It sets up the `extraLoads` package data to make sure the extension loads after the font itself.  The current method of including the extension in the `loader.load` array doesn't work properly as it can be loaded before the font arrives.  That can be handled by setting up dependencies and paths in the loader configuration, but it is harder than it should be, so this makes it easy.
Resolves issue mathjax/MathJax#3410.
The original section that was used to configure a font has been moved to a `configFont()` function, and a new `configExtensions()` function uses it to set up the font extensions.

Add  `fontExtensions` configuration option. (mathjax/MathJax#3410)
