v3/lib/fs.js
v3/test.html
v3/test.js

These changes are needed to make the test.js and test.html files be able to load the TreeJax code.

Load tree jax in test.js and test.html

---

v3/TreeJax/package.json
v3/TreeJax/ts/external.ts
v3/TreeJax/ts/index.ts
v3/TreeJax/ts/json_visitor.ts
v3/TreeJax/ts/mathml_visitor.ts
v3/TreeJax/ts/semantic_visitor.ts
v3/TreeJax/ts/tree.ts
v3/TreeJax/ts/tree_node.ts
v3/TreeJax/ts/visitor.ts
v3/TreeJax/tsconfig.json

to develop both typescript libraries on the version.

Upgrades typescript version of TreeJax to 2.1.* for compatibility.

---

mathjax3-ts/util/FunctionList.ts
mathjax3-ts/util/PrioritizedList.ts

These are a couple of small things I found while writing tests for the utility functions.

Misc fixes

---

mathjax3-ts/core/MathDocument.ts
mathjax3-ts/core/MathItem.ts
mathjax3-ts/core/MmlTree/JsonMmlVisitor.ts
mathjax3-ts/util/Options.ts
mathjax3-ts/util/string.ts

I don't think these will be controversial...

Fix some minor linting issues.

---

package-lock.json
package.json

add package-lock.json

---

mathjax3-ts/output/chtml/Wrapper.ts

This fixes some problems drawing the bounding box when the element who's box is drawn is scaled.
Since this is just a debugging routine, I'll merge this without review.

Scale bboox in drawBBox if the element is scaled.

---

lib/Mml-lab.js

* Captilisation in mathml.js filename.
* Trims input string that leads to an error for me.

Fixes filename and spacing problems.

---

mathjax3-ts/adaptors/chooseAdaptor.ts

Fixes incorrect lowercase filename.

---

mathjax3-ts/output/chtml/Wrappers.ts
mathjax3-ts/output/chtml/Wrappers/mmultiscripts.ts

This implements the output for the `mmultiscripts` MathML element.

Add support for mmultiscripts

---

mathjax3-ts/core/InputJax.ts
mathjax3-ts/input/mathml.ts
mathjax3-ts/input/mathml/MathMLCompile.ts
mathjax3-ts/util/Options.ts

Fixes some typos.

---

mathjax3-ts/input/tex.ts
mathjax3-ts/input/tex/Configuration.ts
mathjax3-ts/input/tex/FindTeX.ts
mathjax3-ts/input/tex/StackItem.ts
mathjax3-ts/input/tex/ams/AmsConfiguration.ts
mathjax3-ts/input/tex/ams/AmsMethods.ts
mathjax3-ts/input/tex/base/BaseMappings.ts
mathjax3-ts/input/tex/newcommand/NewcommandConfiguration.ts
tests/parser-ams-tests.js

* Adds an initialisation method to configurations. 
* Init methods are collated as `FunctionList` objects.
* Integrated init methods into `newcommand` and `ams` package to initialise extension configuration.
* Completes one related item in issue #166

Configuration setup

---

mathjax3-ts/input/tex/color/ColorUtil.ts

Missed that one in my last review. Sorry!

Changes getColor to public.

---

mathjax3-ts/output/common/OutputJax.ts
mathjax3-ts/output/svg/Wrapper.ts

Just some typos I found reading things up during code reviews.

Some typos and style fixes.

---

lib/v3-lab.js
v3-lab.html

This PR updates the v3-lab extensively, and hooks in the contextual menu, the explorer, and the other a11y extensions.  It now uses the render actions list that is new in #204 (update components), and the startup module to load the extensions.

V3 lab updates

---

mathjax3-ts/util/BitField.ts

Fix maximum bits allowed in BitFields (since javascript bit operations are on signed 32-bit numbers).

Fix maximum bits in BitFields

---

mathjax3-ts/handlers/html/HTMLDocument.ts
tests/parser-tests.js

Removes TestMath method from HTMLDocuments.

---

tools/test-diff.el

Just a couple of elisp functions that help with the tests. Does not really need a review.

Add emacs tools

---

mathjax3-ts/input/tex/autoload/AutoloadConfiguration.ts

This PR adds the ability to configure the `autoload` TeX package to autoload an extension when an environment is first used.  This allows `amsCd` to be autoloaded.

Add ability to autoload based on an environment

---

mathjax3-ts/input/tex.ts
mathjax3-ts/input/tex/FilterUtil.ts

As discussed in the meeting:
* Adds filter for setting inherited attributes.
* Removes the special case for errors.

Set inherited attributes in an explicit filter.

---

tests/parser-tests.js

Adapts spelling of mathjax in parser tests.

---

mathjax3-ts/a11y/explorer.ts
mathjax3-ts/a11y/explorer/Explorer.ts
mathjax3-ts/a11y/explorer/Region.ts
mathjax3-ts/a11y/sre_browser.d.ts

Correctly implements the goal directed keyboard magnifier.
Adds options for alignment: `top`, bottom, center`.

A11y keyboard magnifier

---

mathjax3-ts/a11y/complexity/visitor.ts
mathjax3-ts/a11y/explorer.ts
mathjax3-ts/ui/menu/Menu.ts

Correct typos

---

ts/a11y/explorer/KeyExplorer.ts

__Old behaviour:__
* speech attributes were computed during walker initialisation.
* explorer could immediately access pre-computed speech
SRE's newest version will lazily compute the elements of a walker, which in particular reduces the initial parse time for the enriched nodes that are passed as strings. That's moot if the explorer immediately computes the speech on initialisation (at page load).
__New behaviour:__
* speech is only computed when explorer is started.
* we add a init flag to see if the explorer has already initialised
* while this slightly reduces the startup speed for the individual walkers (only noticable with very large equations) it reduces the load time on pages.

Moves speech generation to first initialisation of walker.

---

ts/core/MmlTree/MmlNode.ts

Capitalisation problem I must have missed during code review. Sorry.

Corrects Capitalisation of imported module.

---

ts/input/tex/FilterUtil.ts
ts/input/tex/ParseUtil.ts
ts/input/tex/base/BaseMethods.ts

Solves https://github.com/mathjax/MathJax/issues/2239

Issue 2239

---

ts/output/chtml/fonts/tex.ts
ts/output/common/FontData.ts
ts/output/common/OutputJax.ts
ts/output/svg.ts

Reverts mathjax/MathJax-src#449

Revert "Add ability to include MJXZERO to font-family used for undefined characters"

---

ts/output/chtml/fonts/tex.ts
ts/output/common/FontData.ts
ts/output/common/OutputJax.ts
ts/output/svg.ts

This is the redo of the font-prefix PR but to develop instead of master.

Font prefix

---

README.md

I only added a space between two words.

fixed small error (apply fix to develop as well)

---

ts/input/tex/FindTeX.ts

This PR allows the TeX `FindMath` module to locate `\begin`, `\end`, and `\ref` even if they have spaces after them.  (Currently, the braces must follow the control sequence immediately.)
Resolves issue mathjax/MathJax#2494.

Allow spaces after \begin, \end, and \ref when finding math delimiters. (mathjax/MathJax#2494)

---

components/bin/makeAll
package-lock.json
package.json
ts/core/MmlTree/MmlNode.ts
ts/core/MmlTree/MmlNodes/TeXAtom.ts
ts/core/MmlTree/MmlNodes/menclose.ts
ts/core/MmlTree/MmlNodes/merror.ts
ts/core/MmlTree/MmlNodes/mfenced.ts
ts/core/MmlTree/MmlNodes/mglyph.ts
ts/core/MmlTree/MmlNodes/mi.ts
ts/core/MmlTree/MmlNodes/mn.ts
ts/core/MmlTree/MmlNodes/mphantom.ts
ts/core/MmlTree/MmlNodes/mroot.ts
ts/core/MmlTree/MmlNodes/ms.ts
ts/core/MmlTree/MmlNodes/mspace.ts
ts/core/MmlTree/MmlNodes/msqrt.ts
ts/core/MmlTree/MmlNodes/mtable.ts
ts/core/MmlTree/MmlNodes/mtext.ts
ts/core/Tree/Node.ts
ts/output/common/FontData.ts

Updates `package-lock.json` to reflect the latest version `3.1.2`.

Updates package-lock file to latest version.

---

ts/ui/menu/Menu.ts

Fixes an embarrassing typo in the menu labels.

Fix menu typo reported by pkra.

---

ts/a11y/explorer.ts

A11y italian

---

ts/output/svg/Wrapper.ts

This targets the correct branch for what was PR #589.

Make sure hitbox is translated along with the hit-able element. (mathjax/MathJax#2530)

---

ts/input/tex/base/BaseMappings.ts
ts/input/tex/require/RequireConfiguration.ts

* Adds `\divsymbol` as per discussion on the [board](https://groups.google.com/g/mathjax-users/c/ZHd0xqBIMSs)
* Fixes a typo.

Adds the div symbol.

---

ts/input/tex/ams/AmsConfiguration.ts
ts/input/tex/ams/AmsMappings.ts

Fixes typo on AMS table names.

---

ts/util/Styles.ts

Improves consistency of serialization across adaptors.
Resolves mathjax/MathJax#2726

refactor(util/Styles.ts): consistent serialization

---

components/src/input/asciimath/build.json

asciimath: fix a typo in build.json

---

ts/input/asciimath/mathjax2/legacy/jax/element/MmlNode.js
ts/input/asciimath/mathjax2/legacy/jax/input/AsciiMath/jax.js

This PR makes some variables local that were accidentally global variables in the AsciiMath code.
Resolves issue mathjax/MathJax#2748.

Make variables local in legacy code.  (mathjax/MathJax#2748)

---

README.md

Changed "node-based application" to "node-based applications" in line 104

Changing "node-based application" to "node-based applications"

---

ts/input/tex/color/ColorMethods.ts

Add support for color models to \colorbox

---

ts/input/tex/newcommand/NewcommandMethods.ts

This PR changes how the `\end` is handled for a user-defined environment so that `parser.Parse()` isn't called, avoiding a potential infinite loop.
In this PR, the end material from the `\newenvironment` is inserted into the parser string (with `addArgs()` so buffer overflow is checked) along with a following `\end{...}`, but we record the fact that we have already added the end material by setting a stack environment value so that the second `\end{}` will actually finish the environment.  This avoids the recursive loop triggered by something like
``` latex
\newenvironment{a}{x}{y\end{a}}
\begin{a} ... \end{a}
```
and it now generates the proper error about `\end{a}` without a `\begin{a}`.

Adjust how \end{...} is handled for user-defined environments to avoid a potential recusion loop

---

ts/a11y/explorer.ts

This PR sets the `enableExplorer` option to `false` if there is no `window` variable, so that it is only activated in interactive contexts, and puts off creating the RegionPool until it is needed (in case it is not enabled).  Now that the explorer is included as part of the combined components, it needs to play nice with node-based applications that use the combined configurations, so references to the `window` and to HTML element properties can cause problems.
I started to convert the explorer files to use generics rather than explicit `HTMLElement` references and use the DOMAdaptor to handle the HTML interaction.  But because some pieces of SRE itself use HTMLElements directly, that probably is not worth it, as even if the MathJax portions are properly handled, the SRE parts could still …

Only activate explorer if in a browser

---

ts/input/tex/configmacros/ConfigMacrosConfiguration.ts

This PR adds the ability for the `configmacros` extension to create active characters tied to macros.  The new `active` option in the `configmacros` block of the `tex` configuration defines active characters in the same way as `macros` does for control sequences.
Resolves issue mathjax/MathJax#2967.

Add ability to define active characters as macros. (math/MathJax#2967)

---

ts/components/startup.ts

The promise-based calls like `MathJax.typesetPromise()` and `MathJax.tex2chtmlPromise()` currently shouldn't be called in parallel; that is, you should wait for the first promise to resolve before calling the second one.  Users don't always take this into account, and that can cause problems if the typesetting from the first call requires an extension to be loaded, since the second will run while the first waits for the extension.  That can cause problems with things like automatic equation numbering and macro definitions that must be done in sequence.  With the fact that fonts now can cause extensions to be loaded (for less-used groups of characters), this means the problem will be more severe in version 4.
This PR uses the existing `MathJax.startup.promise` to chain the promise-based …

Make promise-based call use startup.promise to avoid concurency

---

.travis.yml
package-lock.json
package.json

This PR will address and close #984.

Remove install script

---

ts/util/Styles.ts

This PR fixes a typo in one of the patterns in the Styles handling.

Fix a typo 'ulta' to 'ultra'.

---

ts/output/common/FontData.ts

This PR provides a mechanism for font extensions to set the SMP remapping data for new variants that the extension defines.  It also adds a new options section to the `SmpData` type that allows additional mappings, and uses that to set the extra mappings for the bold variant that were hard-coded into the `remapSmpChars()` method.  Finally, it allows the SMP mapping for a new variant to be defined in terms of previous SMP mappings by specifying the string name of a variant whose mapping is the same.  That way, fonts like `dsfonts` that is a double-struck font can simply specify that the `double-struck` mapping is to be used rather than duplicating the data for that.

Add ability for extensions to set the SMP mappings for new variants

---

components/mjs/input/tex/extensions/bbm/config.json

This PR fixes the config file for this font.

Update config file and dependencies (bbm)

---

components/mjs/input/tex/extensions/dsfont/config.json

This PR fixes the font's config file.

Update config file and dependencies (dsfont)

---

components/mjs/input/tex/extensions/bbm/bbm.js
components/mjs/input/tex/extensions/bbm/config.json
ts/input/tex/bbm/BbmConfiguration.ts

Implements the [bbm package](https://ctan.org/pkg/bbm).
Requires the bbm fonts from https://github.com/mathjax/MathJax-fonts/pull/3

Adds the bbm package.

---

ts/a11y/semantic-enrich.ts
ts/adaptors/lite/Parser.ts
ts/core/MmlTree/SerializedMmlVisitor.ts
ts/core/MmlTree/TestMmlVisitor.ts
ts/input/tex/amscd/AmsCdMethods.ts
ts/input/tex/base/BaseMethods.ts
ts/input/tex/physics/PhysicsMethods.ts
ts/output/chtml/Wrappers/menclose.ts
ts/output/common/Wrappers/maction.ts
ts/output/svg/Wrappers/mo.ts
ts/output/svg/Wrappers/mtable.ts
ts/ui/menu/MmlVisitor.ts

This PR is solely to eye-ball the changes from string concatenation to template strings in PR #1123.
Changes were done with the ELisp script at https://github.com/mathjax/MathJax-dev/blob/tools/rewrite_templates/tools/template.el

string corrections for PR #1123

---

ts/a11y/complexity/collapse.ts
ts/adaptors/lite/Parser.ts
ts/adaptors/liteAdaptor.ts
ts/components/loader.ts
ts/components/package.ts
ts/core/MathDocument.ts
ts/core/MmlTree/Attributes.ts
ts/core/MmlTree/MmlNode.ts
ts/core/MmlTree/MmlVisitor.ts
ts/handlers/html/HTMLDomStrings.ts
ts/input/tex/ColumnParser.ts
ts/input/tex/ParseUtil.ts
ts/input/tex/TexParser.ts
ts/input/tex/empheq/EmpheqUtil.ts
ts/input/tex/mathtools/MathtoolsTags.ts
ts/input/tex/require/RequireConfiguration.ts
ts/input/tex/setoptions/SetOptionsConfiguration.ts
ts/input/tex/tagformat/TagFormatConfiguration.ts
ts/output/common/FontData.ts
ts/output/common/Wrappers/mo.ts
ts/ui/lazy/LazyHandler.ts
ts/ui/menu/Menu.ts
ts/util/Options.ts
ts/util/Styles.ts
ts/util/lengths.ts
tsconfig/common.json

* Rewrites all occurrences of `hasOwnProperty` to use `Object.hasOwn`
* Adds `ES2022` library support

rewrite occurrences of hasOwnProperty

---

ts/util/Styles.ts

Convert style values to strings before passing them to setStyle.

---

ts/a11y/explorer/Region.ts
ts/adaptors/chooseAdaptor.ts
ts/components/loader.ts
ts/components/startup.ts
ts/input/tex/ParseMethods.ts
ts/input/tex/cases/CasesConfiguration.ts
ts/input/tex/empheq/EmpheqConfiguration.ts
ts/ui/menu/MenuUtil.ts

This PR is the result of running `ppm -s format:fix` on the current `develop` branch.  IT fixes a number of small formatting issues introduced by recent PRs.

Fix prittier issues from recent commits

---

testsuite/tests/input/tex/Tag.test.ts

This PR just updates the `Tags.test.ts` file format and adds new tests to complete the coverage of the `Tags.ts`.
Best to view with hidden whitespace.

Update tag test format and add new tests

---

package.json
pnpm-lock.yaml

Updates SRE version to v5.0.0-alpha.5

updates sre to latest version

---

package.json
pnpm-lock.yaml

SRE version bump

---

README.md

This PR updates the README to v4, which I forgot to do.  Argh!

Update readme for v4
